sudo: false

language: java

env:
  global:
    - GRADLE_OPTS=-Xmx512m
    - PROTOBUF_VERSION=3.5.1
    - LDFLAGS=-L/tmp/protobuf/lib
    - CXXFLAGS=-I/tmp/protobuf/include
    - LD_LIBRARY_PATH=/tmp/protobuf/lib

before_install:
  - mkdir -p $HOME/.gradle/caches &&
    ln -s /tmp/gradle-caches-modules-2 $HOME/.gradle/caches/modules-2
  - mkdir -p $HOME/.gradle &&
    ln -s /tmp/gradle-wrapper $HOME/.gradle/wrapper
    # Work around https://github.com/travis-ci/travis-ci/issues/2317
  - if \[ "$TRAVIS_OS_NAME" = linux \]; then jdk_switcher use oraclejdk8; fi
  - buildscripts/make_dependencies.sh # build protoc into /tmp/protobuf-${PROTOBUF_VERSION}
  - ln -s "/tmp/protobuf-${PROTOBUF_VERSION}/$(uname -s)-$(uname -p)" /tmp/protobuf
  - mkdir -p $HOME/.gradle
  - echo "checkstyle.ignoreFailures=false" >> $HOME/.gradle/gradle.properties
  - echo "failOnWarnings=true" >> $HOME/.gradle/gradle.properties
  - echo "errorProne=true" >> $HOME/.gradle/gradle.properties

install:
  - ./gradlew assemble generateTestProto install
  - pushd examples && ./gradlew build && popd
  - pushd examples && mvn verify && popd

before_script:
  - test -z "$(git status --porcelain)" || (git status && echo Error Working directory is not clean. Forget to commit generated files? && false)

script:
  - ./gradlew check :grpc-all:jacocoTestReport

after_success:
  - if \[ "$TRAVIS_OS_NAME" = linux \]; then ./gradlew :grpc-all:coveralls; fi
  - bash <(curl -s https://codecov.io/bash)

os:
  - linux

notifications:
  email: false

cache:
  directories:
    - /tmp/protobuf-${PROTOBUF_VERSION}
    - /tmp/gradle-caches-modules-2
    - /tmp/gradle-wrapper

before_cache:
  # The lock changes based on folder name; normally $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm /tmp/gradle-caches-modules-2/gradle-caches-modules-2.lock
  - find $HOME/.gradle/wrapper -not -name "*-all.zip" -and -not -name "*-bin.zip" -delete
