// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/tracer/message.proto

package tracer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_Message_         MessageType = 0
	MessageType_Message_Request  MessageType = 1
	MessageType_Message_Response MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "Message_",
	1: "Message_Request",
	2: "Message_Response",
}

var MessageType_value = map[string]int32{
	"Message_":         0,
	"Message_Request":  1,
	"Message_Response": 2,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30bd59f929831d10, []int{0}
}

type RecordType int32

const (
	RecordType_Record_       RecordType = 0
	RecordType_RecordSend    RecordType = 1
	RecordType_RecordReceive RecordType = 2
)

var RecordType_name = map[int32]string{
	0: "Record_",
	1: "RecordSend",
	2: "RecordReceive",
}

var RecordType_value = map[string]int32{
	"Record_":       0,
	"RecordSend":    1,
	"RecordReceive": 2,
}

func (x RecordType) String() string {
	return proto.EnumName(RecordType_name, int32(x))
}

func (RecordType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30bd59f929831d10, []int{1}
}

type FaultType int32

const (
	FaultType_Fault_     FaultType = 0
	FaultType_FaultCrash FaultType = 1
	FaultType_FaultDelay FaultType = 2
)

var FaultType_name = map[int32]string{
	0: "Fault_",
	1: "FaultCrash",
	2: "FaultDelay",
}

var FaultType_value = map[string]int32{
	"Fault_":     0,
	"FaultCrash": 1,
	"FaultDelay": 2,
}

func (x FaultType) String() string {
	return proto.EnumName(FaultType_name, int32(x))
}

func (FaultType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_30bd59f929831d10, []int{2}
}

type Record struct {
	Type                 RecordType `protobuf:"varint,1,opt,name=type,proto3,enum=tracer.RecordType" json:"type,omitempty"`
	Timestamp            int64      `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MessageName          string     `protobuf:"bytes,3,opt,name=message_name,json=messageName,proto3" json:"message_name,omitempty"`
	Uuid                 string     `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd59f929831d10, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetType() RecordType {
	if m != nil {
		return m.Type
	}
	return RecordType_Record_
}

func (m *Record) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Record) GetMessageName() string {
	if m != nil {
		return m.MessageName
	}
	return ""
}

func (m *Record) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Trace struct {
	Id                   int64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Records              []*Record `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	Rlfi                 *RLFI     `protobuf:"bytes,20,opt,name=rlfi,proto3" json:"rlfi,omitempty"`
	Tfi                  *TFI      `protobuf:"bytes,21,opt,name=tfi,proto3" json:"tfi,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Trace) Reset()         { *m = Trace{} }
func (m *Trace) String() string { return proto.CompactTextString(m) }
func (*Trace) ProtoMessage()    {}
func (*Trace) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd59f929831d10, []int{1}
}

func (m *Trace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trace.Unmarshal(m, b)
}
func (m *Trace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trace.Marshal(b, m, deterministic)
}
func (m *Trace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trace.Merge(m, src)
}
func (m *Trace) XXX_Size() int {
	return xxx_messageInfo_Trace.Size(m)
}
func (m *Trace) XXX_DiscardUnknown() {
	xxx_messageInfo_Trace.DiscardUnknown(m)
}

var xxx_messageInfo_Trace proto.InternalMessageInfo

func (m *Trace) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Trace) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *Trace) GetRlfi() *RLFI {
	if m != nil {
		return m.Rlfi
	}
	return nil
}

func (m *Trace) GetTfi() *TFI {
	if m != nil {
		return m.Tfi
	}
	return nil
}

type RLFI struct {
	Type                 FaultType `protobuf:"varint,1,opt,name=type,proto3,enum=tracer.FaultType" json:"type,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Delay                int64     `protobuf:"varint,3,opt,name=delay,proto3" json:"delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RLFI) Reset()         { *m = RLFI{} }
func (m *RLFI) String() string { return proto.CompactTextString(m) }
func (*RLFI) ProtoMessage()    {}
func (*RLFI) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd59f929831d10, []int{2}
}

func (m *RLFI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RLFI.Unmarshal(m, b)
}
func (m *RLFI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RLFI.Marshal(b, m, deterministic)
}
func (m *RLFI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RLFI.Merge(m, src)
}
func (m *RLFI) XXX_Size() int {
	return xxx_messageInfo_RLFI.Size(m)
}
func (m *RLFI) XXX_DiscardUnknown() {
	xxx_messageInfo_RLFI.DiscardUnknown(m)
}

var xxx_messageInfo_RLFI proto.InternalMessageInfo

func (m *RLFI) GetType() FaultType {
	if m != nil {
		return m.Type
	}
	return FaultType_Fault_
}

func (m *RLFI) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RLFI) GetDelay() int64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

type TFI struct {
	Type                 FaultType `protobuf:"varint,1,opt,name=type,proto3,enum=tracer.FaultType" json:"type,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Delay                int64     `protobuf:"varint,3,opt,name=delay,proto3" json:"delay,omitempty"`
	After                []string  `protobuf:"bytes,4,rep,name=after,proto3" json:"after,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TFI) Reset()         { *m = TFI{} }
func (m *TFI) String() string { return proto.CompactTextString(m) }
func (*TFI) ProtoMessage()    {}
func (*TFI) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bd59f929831d10, []int{3}
}

func (m *TFI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TFI.Unmarshal(m, b)
}
func (m *TFI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TFI.Marshal(b, m, deterministic)
}
func (m *TFI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TFI.Merge(m, src)
}
func (m *TFI) XXX_Size() int {
	return xxx_messageInfo_TFI.Size(m)
}
func (m *TFI) XXX_DiscardUnknown() {
	xxx_messageInfo_TFI.DiscardUnknown(m)
}

var xxx_messageInfo_TFI proto.InternalMessageInfo

func (m *TFI) GetType() FaultType {
	if m != nil {
		return m.Type
	}
	return FaultType_Fault_
}

func (m *TFI) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TFI) GetDelay() int64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *TFI) GetAfter() []string {
	if m != nil {
		return m.After
	}
	return nil
}

func init() {
	proto.RegisterEnum("tracer.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("tracer.RecordType", RecordType_name, RecordType_value)
	proto.RegisterEnum("tracer.FaultType", FaultType_name, FaultType_value)
	proto.RegisterType((*Record)(nil), "tracer.Record")
	proto.RegisterType((*Trace)(nil), "tracer.Trace")
	proto.RegisterType((*RLFI)(nil), "tracer.RLFI")
	proto.RegisterType((*TFI)(nil), "tracer.TFI")
}

func init() { proto.RegisterFile("core/tracer/message.proto", fileDescriptor_30bd59f929831d10) }

var fileDescriptor_30bd59f929831d10 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4f, 0x8b, 0xd4, 0x30,
	0x14, 0x37, 0x4d, 0x77, 0xd6, 0x79, 0x1d, 0xc7, 0xee, 0x73, 0x84, 0x08, 0x0a, 0x75, 0x40, 0x29,
	0x7b, 0x98, 0x85, 0xf1, 0xe0, 0xc5, 0x9b, 0x32, 0xb0, 0xa0, 0x1e, 0x62, 0xc1, 0xe3, 0x12, 0xdb,
	0x37, 0x5a, 0x68, 0xa7, 0x35, 0x49, 0x85, 0xb9, 0x0a, 0x7e, 0x6f, 0x49, 0xd2, 0xce, 0xb8, 0x1f,
	0xc0, 0xdb, 0xfb, 0xfd, 0xc9, 0xcb, 0xfb, 0xbd, 0x04, 0x9e, 0x95, 0x9d, 0xa6, 0x1b, 0xab, 0x55,
	0x49, 0xfa, 0xa6, 0x25, 0x63, 0xd4, 0x77, 0xda, 0xf4, 0xba, 0xb3, 0x1d, 0xce, 0x02, 0xbb, 0xfe,
	0xc3, 0x60, 0x26, 0xa9, 0xec, 0x74, 0x85, 0xaf, 0x21, 0xb6, 0xc7, 0x9e, 0x04, 0xcb, 0x58, 0xbe,
	0xdc, 0xe2, 0x26, 0x38, 0x36, 0x41, 0x2d, 0x8e, 0x3d, 0x49, 0xaf, 0xe3, 0x73, 0x98, 0xdb, 0xba,
	0x25, 0x63, 0x55, 0xdb, 0x8b, 0x28, 0x63, 0x39, 0x97, 0x67, 0x02, 0x5f, 0xc2, 0x62, 0xbc, 0xe9,
	0xee, 0xa0, 0x5a, 0x12, 0x3c, 0x63, 0xf9, 0x5c, 0x26, 0x23, 0xf7, 0x59, 0xb5, 0x84, 0x08, 0xf1,
	0x30, 0xd4, 0x95, 0x88, 0xbd, 0xe4, 0xeb, 0xf5, 0x6f, 0x06, 0x17, 0x85, 0xbb, 0x10, 0x97, 0x10,
	0xd5, 0x95, 0x1f, 0x82, 0xcb, 0xa8, 0xae, 0x30, 0x87, 0x4b, 0xed, 0x47, 0x30, 0x22, 0xca, 0x78,
	0x9e, 0x6c, 0x97, 0xf7, 0x27, 0x93, 0x93, 0x8c, 0x19, 0xc4, 0xba, 0xd9, 0xd7, 0x62, 0x95, 0xb1,
	0x3c, 0xd9, 0x2e, 0x4e, 0xb6, 0x8f, 0xbb, 0x5b, 0xe9, 0x15, 0x7c, 0x01, 0xdc, 0xee, 0x6b, 0xf1,
	0xd4, 0x1b, 0x92, 0xc9, 0x50, 0xec, 0x6e, 0xa5, 0xe3, 0xd7, 0x5f, 0x21, 0x76, 0x66, 0x7c, 0x75,
	0x6f, 0x13, 0x57, 0x93, 0x6f, 0xa7, 0x86, 0xc6, 0xfe, 0xb3, 0x08, 0x84, 0xd8, 0x47, 0x8c, 0x42,
	0x0e, 0x57, 0xe3, 0x0a, 0x2e, 0x2a, 0x6a, 0xd4, 0xd1, 0xe7, 0xe6, 0x32, 0x80, 0x75, 0x03, 0xbc,
	0xf8, 0x0f, 0x7d, 0x1d, 0xab, 0xf6, 0x96, 0xb4, 0x88, 0x33, 0x9e, 0xcf, 0x65, 0x00, 0xd7, 0x3b,
	0x48, 0x3e, 0x85, 0x75, 0xbb, 0xa6, 0xb8, 0x80, 0x87, 0x23, 0xbc, 0x4b, 0x1f, 0xe0, 0x13, 0x78,
	0x3c, 0x21, 0x49, 0x3f, 0x07, 0x32, 0x36, 0x65, 0xb8, 0x82, 0xf4, 0x4c, 0x9a, 0xbe, 0x3b, 0x18,
	0x4a, 0xa3, 0xeb, 0x77, 0x00, 0xe7, 0xc7, 0xc7, 0x04, 0x2e, 0x03, 0x72, 0x5d, 0x96, 0x93, 0xf4,
	0x85, 0x0e, 0x55, 0xca, 0xf0, 0x0a, 0x1e, 0x8d, 0xaf, 0x41, 0x25, 0xd5, 0xbf, 0xdc, 0xe9, 0xb7,
	0x30, 0x3f, 0x05, 0x43, 0x80, 0x99, 0x07, 0xe3, 0x59, 0x5f, 0xbf, 0xd7, 0xca, 0xfc, 0x48, 0xd9,
	0x09, 0x7f, 0x70, 0x91, 0xd2, 0xe8, 0xdb, 0xcc, 0xff, 0xd0, 0x37, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xc2, 0x81, 0x02, 0x6f, 0xbe, 0x02, 0x00, 0x00,
}
