// Code generated by protoc-gen-go. DO NOT EDIT.
// source: context_bus.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	context_bus.proto

It has these top-level messages:
	Condition
	PrerequisiteMessage
	PrerequisiteLogic
	PrerequisiteNode
	PrerequisiteTree
	PrerequisiteSnapshot
	FaultDelayParam
	TrafficBalanceParam
	TrafficRoutingParam
	ReactionConfigure
	Path
	AttributeConfigure
	TimestampConfigure
	StackTraceConfigure
	LoggingConfigure
	TracingConfigure
	MetricsConfigure
	ObservationConfigure
	Configure
	CPUProfile
	MemProfile
	NetProfile
	HardwareProfile
	LanguageGo
	LanguageJava
	LanguageProfile
	EnvironmentalProfile
	EventWhen
	AttributeValue
	Attributes
	EventWhere
	EventRecorder
	EventMessage
	LibrariesMessage
	EventWhat
	EventRepresentation
	ParentChildPointers
	EventMetadata
	EventData
	Record
	LineageSnapshot
	Payload
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ConditionOperator int32

const (
	ConditionOperator_ConditionOperator_ ConditionOperator = 0
	ConditionOperator_LT                 ConditionOperator = 1
	ConditionOperator_GT                 ConditionOperator = 2
	ConditionOperator_LE                 ConditionOperator = 3
	ConditionOperator_GE                 ConditionOperator = 4
	ConditionOperator_EQ                 ConditionOperator = 5
	ConditionOperator_NE                 ConditionOperator = 6
)

var ConditionOperator_name = map[int32]string{
	0: "ConditionOperator_",
	1: "LT",
	2: "GT",
	3: "LE",
	4: "GE",
	5: "EQ",
	6: "NE",
}
var ConditionOperator_value = map[string]int32{
	"ConditionOperator_": 0,
	"LT":                 1,
	"GT":                 2,
	"LE":                 3,
	"GE":                 4,
	"EQ":                 5,
	"NE":                 6,
}

func (x ConditionOperator) String() string {
	return proto1.EnumName(ConditionOperator_name, int32(x))
}
func (ConditionOperator) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ConditionType int32

const (
	ConditionType_ConditionType_ ConditionType = 0
	ConditionType_NumOfInvok     ConditionType = 1
	ConditionType_Latency        ConditionType = 2
)

var ConditionType_name = map[int32]string{
	0: "ConditionType_",
	1: "NumOfInvok",
	2: "Latency",
}
var ConditionType_value = map[string]int32{
	"ConditionType_": 0,
	"NumOfInvok":     1,
	"Latency":        2,
}

func (x ConditionType) String() string {
	return proto1.EnumName(ConditionType_name, int32(x))
}
func (ConditionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PrerequisiteNodeType int32

const (
	PrerequisiteNodeType_PrerequisiteNodeType_ PrerequisiteNodeType = 0
	PrerequisiteNodeType_Message               PrerequisiteNodeType = 1
	PrerequisiteNodeType_Logic                 PrerequisiteNodeType = 2
)

var PrerequisiteNodeType_name = map[int32]string{
	0: "PrerequisiteNodeType_",
	1: "Message",
	2: "Logic",
}
var PrerequisiteNodeType_value = map[string]int32{
	"PrerequisiteNodeType_": 0,
	"Message":               1,
	"Logic":                 2,
}

func (x PrerequisiteNodeType) String() string {
	return proto1.EnumName(PrerequisiteNodeType_name, int32(x))
}
func (PrerequisiteNodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PrerequisiteLogicType int32

const (
	PrerequisiteLogicType_PrerequisiteLogicType_ PrerequisiteLogicType = 0
	PrerequisiteLogicType_And                    PrerequisiteLogicType = 1
	PrerequisiteLogicType_Or                     PrerequisiteLogicType = 2
)

var PrerequisiteLogicType_name = map[int32]string{
	0: "PrerequisiteLogicType_",
	1: "And",
	2: "Or",
}
var PrerequisiteLogicType_value = map[string]int32{
	"PrerequisiteLogicType_": 0,
	"And":                    1,
	"Or":                     2,
}

func (x PrerequisiteLogicType) String() string {
	return proto1.EnumName(PrerequisiteLogicType_name, int32(x))
}
func (PrerequisiteLogicType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ReactionType int32

const (
	ReactionType_ReactionType_ ReactionType = 0
	// fault injection
	ReactionType_FaultCrash ReactionType = 1
	ReactionType_FaultDelay ReactionType = 2
	ReactionType_FaultDrop  ReactionType = 3
	// traffic (e.g., load-balancing, traffic shaping)
	ReactionType_TrafficBalance ReactionType = 101
	ReactionType_TrafficRouting ReactionType = 102
)

var ReactionType_name = map[int32]string{
	0:   "ReactionType_",
	1:   "FaultCrash",
	2:   "FaultDelay",
	3:   "FaultDrop",
	101: "TrafficBalance",
	102: "TrafficRouting",
}
var ReactionType_value = map[string]int32{
	"ReactionType_":  0,
	"FaultCrash":     1,
	"FaultDelay":     2,
	"FaultDrop":      3,
	"TrafficBalance": 101,
	"TrafficRouting": 102,
}

func (x ReactionType) String() string {
	return proto1.EnumName(ReactionType_name, int32(x))
}
func (ReactionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type PathType int32

const (
	PathType_PathType_   PathType = 0
	PathType_Application PathType = 1
	PathType_Library     PathType = 2
)

var PathType_name = map[int32]string{
	0: "PathType_",
	1: "Application",
	2: "Library",
}
var PathType_value = map[string]int32{
	"PathType_":   0,
	"Application": 1,
	"Library":     2,
}

func (x PathType) String() string {
	return proto1.EnumName(PathType_name, int32(x))
}
func (PathType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type MetricType int32

const (
	MetricType_MetricType_ MetricType = 0
	MetricType_Counter     MetricType = 1
	MetricType_Gauge       MetricType = 2
	MetricType_Histogram   MetricType = 3
	MetricType_Summery     MetricType = 4
)

var MetricType_name = map[int32]string{
	0: "MetricType_",
	1: "Counter",
	2: "Gauge",
	3: "Histogram",
	4: "Summery",
}
var MetricType_value = map[string]int32{
	"MetricType_": 0,
	"Counter":     1,
	"Gauge":       2,
	"Histogram":   3,
	"Summery":     4,
}

func (x MetricType) String() string {
	return proto1.EnumName(MetricType_name, int32(x))
}
func (MetricType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type LanguageType int32

const (
	LanguageType_LanguageType_ LanguageType = 0
	LanguageType_Other         LanguageType = 1
	LanguageType_Golang        LanguageType = 2
	LanguageType_Java          LanguageType = 3
)

var LanguageType_name = map[int32]string{
	0: "LanguageType_",
	1: "Other",
	2: "Golang",
	3: "Java",
}
var LanguageType_value = map[string]int32{
	"LanguageType_": 0,
	"Other":         1,
	"Golang":        2,
	"Java":          3,
}

func (x LanguageType) String() string {
	return proto1.EnumName(LanguageType_name, int32(x))
}
func (LanguageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type AttributeValueType int32

const (
	AttributeValueType_AttributeValueType_ AttributeValueType = 0
	AttributeValueType_AttributeValueStr   AttributeValueType = 1
	AttributeValueType_AttributeValueAttr  AttributeValueType = 2
)

var AttributeValueType_name = map[int32]string{
	0: "AttributeValueType_",
	1: "AttributeValueStr",
	2: "AttributeValueAttr",
}
var AttributeValueType_value = map[string]int32{
	"AttributeValueType_": 0,
	"AttributeValueStr":   1,
	"AttributeValueAttr":  2,
}

func (x AttributeValueType) String() string {
	return proto1.EnumName(AttributeValueType_name, int32(x))
}
func (AttributeValueType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type EventRecorderType int32

const (
	EventRecorderType_EventRecorderType_          EventRecorderType = 0
	EventRecorderType_EventRecorderServiceHandler EventRecorderType = 1
	EventRecorderType_EventRecorderFunction       EventRecorderType = 2
	EventRecorderType_EventRecorderThirdParty     EventRecorderType = 3
)

var EventRecorderType_name = map[int32]string{
	0: "EventRecorderType_",
	1: "EventRecorderServiceHandler",
	2: "EventRecorderFunction",
	3: "EventRecorderThirdParty",
}
var EventRecorderType_value = map[string]int32{
	"EventRecorderType_":          0,
	"EventRecorderServiceHandler": 1,
	"EventRecorderFunction":       2,
	"EventRecorderThirdParty":     3,
}

func (x EventRecorderType) String() string {
	return proto1.EnumName(EventRecorderType_name, int32(x))
}
func (EventRecorderType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// ******************* from 3mb WIP
type MessageType int32

const (
	MessageType_MessageType_     MessageType = 0
	MessageType_Message_Request  MessageType = 1
	MessageType_Message_Response MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "MessageType_",
	1: "Message_Request",
	2: "Message_Response",
}
var MessageType_value = map[string]int32{
	"MessageType_":     0,
	"Message_Request":  1,
	"Message_Response": 2,
}

func (x MessageType) String() string {
	return proto1.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type RecordType int32

const (
	RecordType_RecordType_   RecordType = 0
	RecordType_RecordSend    RecordType = 1
	RecordType_RecordReceive RecordType = 2
)

var RecordType_name = map[int32]string{
	0: "RecordType_",
	1: "RecordSend",
	2: "RecordReceive",
}
var RecordType_value = map[string]int32{
	"RecordType_":   0,
	"RecordSend":    1,
	"RecordReceive": 2,
}

func (x RecordType) String() string {
	return proto1.EnumName(RecordType_name, int32(x))
}
func (RecordType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type Condition struct {
	Type  ConditionType     `protobuf:"varint,1,opt,name=type,enum=context_bus.ConditionType" json:"type,omitempty"`
	Op    ConditionOperator `protobuf:"varint,2,opt,name=op,enum=context_bus.ConditionOperator" json:"op,omitempty"`
	Value int64             `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
}

func (m *Condition) Reset()                    { *m = Condition{} }
func (m *Condition) String() string            { return proto1.CompactTextString(m) }
func (*Condition) ProtoMessage()               {}
func (*Condition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Condition) GetType() ConditionType {
	if m != nil {
		return m.Type
	}
	return ConditionType_ConditionType_
}

func (m *Condition) GetOp() ConditionOperator {
	if m != nil {
		return m.Op
	}
	return ConditionOperator_ConditionOperator_
}

func (m *Condition) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PrerequisiteMessage struct {
	Type        PrerequisiteNodeType `protobuf:"varint,1,opt,name=type,enum=context_bus.PrerequisiteNodeType" json:"type,omitempty"`
	MessageName string               `protobuf:"bytes,2,opt,name=message_name,json=messageName" json:"message_name,omitempty"`
	Conds       []*Condition         `protobuf:"bytes,3,rep,name=conds" json:"conds,omitempty"`
	Parent      int64                `protobuf:"varint,100,opt,name=parent" json:"parent,omitempty"`
	List        []int64              `protobuf:"varint,101,rep,packed,name=list" json:"list,omitempty"`
}

func (m *PrerequisiteMessage) Reset()                    { *m = PrerequisiteMessage{} }
func (m *PrerequisiteMessage) String() string            { return proto1.CompactTextString(m) }
func (*PrerequisiteMessage) ProtoMessage()               {}
func (*PrerequisiteMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PrerequisiteMessage) GetType() PrerequisiteNodeType {
	if m != nil {
		return m.Type
	}
	return PrerequisiteNodeType_PrerequisiteNodeType_
}

func (m *PrerequisiteMessage) GetMessageName() string {
	if m != nil {
		return m.MessageName
	}
	return ""
}

func (m *PrerequisiteMessage) GetConds() []*Condition {
	if m != nil {
		return m.Conds
	}
	return nil
}

func (m *PrerequisiteMessage) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *PrerequisiteMessage) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

type PrerequisiteLogic struct {
	Type   PrerequisiteLogicType `protobuf:"varint,1,opt,name=type,enum=context_bus.PrerequisiteLogicType" json:"type,omitempty"`
	Parent int64                 `protobuf:"varint,100,opt,name=parent" json:"parent,omitempty"`
	List   []int64               `protobuf:"varint,101,rep,packed,name=list" json:"list,omitempty"`
}

func (m *PrerequisiteLogic) Reset()                    { *m = PrerequisiteLogic{} }
func (m *PrerequisiteLogic) String() string            { return proto1.CompactTextString(m) }
func (*PrerequisiteLogic) ProtoMessage()               {}
func (*PrerequisiteLogic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PrerequisiteLogic) GetType() PrerequisiteLogicType {
	if m != nil {
		return m.Type
	}
	return PrerequisiteLogicType_PrerequisiteLogicType_
}

func (m *PrerequisiteLogic) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *PrerequisiteLogic) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

type PrerequisiteNode struct {
	Id      int64                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type    PrerequisiteNodeType `protobuf:"varint,2,opt,name=type,enum=context_bus.PrerequisiteNodeType" json:"type,omitempty"`
	Message *PrerequisiteMessage `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Logic   *PrerequisiteLogic   `protobuf:"bytes,4,opt,name=logic" json:"logic,omitempty"`
}

func (m *PrerequisiteNode) Reset()                    { *m = PrerequisiteNode{} }
func (m *PrerequisiteNode) String() string            { return proto1.CompactTextString(m) }
func (*PrerequisiteNode) ProtoMessage()               {}
func (*PrerequisiteNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PrerequisiteNode) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PrerequisiteNode) GetType() PrerequisiteNodeType {
	if m != nil {
		return m.Type
	}
	return PrerequisiteNodeType_PrerequisiteNodeType_
}

func (m *PrerequisiteNode) GetMessage() *PrerequisiteMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PrerequisiteNode) GetLogic() *PrerequisiteLogic {
	if m != nil {
		return m.Logic
	}
	return nil
}

// prerequisite tree
type PrerequisiteTree struct {
	Pres    []*PrerequisiteNode `protobuf:"bytes,1,rep,name=pres" json:"pres,omitempty"`
	LeafIDs []int64             `protobuf:"varint,2,rep,packed,name=leafIDs" json:"leafIDs,omitempty"`
}

func (m *PrerequisiteTree) Reset()                    { *m = PrerequisiteTree{} }
func (m *PrerequisiteTree) String() string            { return proto1.CompactTextString(m) }
func (*PrerequisiteTree) ProtoMessage()               {}
func (*PrerequisiteTree) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PrerequisiteTree) GetPres() []*PrerequisiteNode {
	if m != nil {
		return m.Pres
	}
	return nil
}

func (m *PrerequisiteTree) GetLeafIDs() []int64 {
	if m != nil {
		return m.LeafIDs
	}
	return nil
}

type PrerequisiteSnapshot struct {
	Value []int64 `protobuf:"varint,1,rep,packed,name=value" json:"value,omitempty"`
	Acc   bool    `protobuf:"varint,2,opt,name=acc" json:"acc,omitempty"`
}

func (m *PrerequisiteSnapshot) Reset()                    { *m = PrerequisiteSnapshot{} }
func (m *PrerequisiteSnapshot) String() string            { return proto1.CompactTextString(m) }
func (*PrerequisiteSnapshot) ProtoMessage()               {}
func (*PrerequisiteSnapshot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PrerequisiteSnapshot) GetValue() []int64 {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PrerequisiteSnapshot) GetAcc() bool {
	if m != nil {
		return m.Acc
	}
	return false
}

type FaultDelayParam struct {
	Ms int64 `protobuf:"varint,1,opt,name=ms" json:"ms,omitempty"`
}

func (m *FaultDelayParam) Reset()                    { *m = FaultDelayParam{} }
func (m *FaultDelayParam) String() string            { return proto1.CompactTextString(m) }
func (*FaultDelayParam) ProtoMessage()               {}
func (*FaultDelayParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FaultDelayParam) GetMs() int64 {
	if m != nil {
		return m.Ms
	}
	return 0
}

type TrafficBalanceParam struct {
}

func (m *TrafficBalanceParam) Reset()                    { *m = TrafficBalanceParam{} }
func (m *TrafficBalanceParam) String() string            { return proto1.CompactTextString(m) }
func (*TrafficBalanceParam) ProtoMessage()               {}
func (*TrafficBalanceParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type TrafficRoutingParam struct {
}

func (m *TrafficRoutingParam) Reset()                    { *m = TrafficRoutingParam{} }
func (m *TrafficRoutingParam) String() string            { return proto1.CompactTextString(m) }
func (*TrafficRoutingParam) ProtoMessage()               {}
func (*TrafficRoutingParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type ReactionConfigure struct {
	Type ReactionType `protobuf:"varint,1,opt,name=type,enum=context_bus.ReactionType" json:"type,omitempty"`
	// Types that are valid to be assigned to Params:
	//	*ReactionConfigure_FaultDelay
	//	*ReactionConfigure_TrafficBalance
	//	*ReactionConfigure_TrafficRouting
	Params  isReactionConfigure_Params `protobuf_oneof:"params"`
	PreTree []*PrerequisiteTree        `protobuf:"bytes,3,rep,name=pre_tree,json=preTree" json:"pre_tree,omitempty"`
}

func (m *ReactionConfigure) Reset()                    { *m = ReactionConfigure{} }
func (m *ReactionConfigure) String() string            { return proto1.CompactTextString(m) }
func (*ReactionConfigure) ProtoMessage()               {}
func (*ReactionConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type isReactionConfigure_Params interface{ isReactionConfigure_Params() }

type ReactionConfigure_FaultDelay struct {
	FaultDelay *FaultDelayParam `protobuf:"bytes,2002,opt,name=FaultDelay,oneof"`
}
type ReactionConfigure_TrafficBalance struct {
	TrafficBalance *TrafficBalanceParam `protobuf:"bytes,2101,opt,name=TrafficBalance,oneof"`
}
type ReactionConfigure_TrafficRouting struct {
	TrafficRouting *TrafficRoutingParam `protobuf:"bytes,2102,opt,name=TrafficRouting,oneof"`
}

func (*ReactionConfigure_FaultDelay) isReactionConfigure_Params()     {}
func (*ReactionConfigure_TrafficBalance) isReactionConfigure_Params() {}
func (*ReactionConfigure_TrafficRouting) isReactionConfigure_Params() {}

func (m *ReactionConfigure) GetParams() isReactionConfigure_Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *ReactionConfigure) GetType() ReactionType {
	if m != nil {
		return m.Type
	}
	return ReactionType_ReactionType_
}

func (m *ReactionConfigure) GetFaultDelay() *FaultDelayParam {
	if x, ok := m.GetParams().(*ReactionConfigure_FaultDelay); ok {
		return x.FaultDelay
	}
	return nil
}

func (m *ReactionConfigure) GetTrafficBalance() *TrafficBalanceParam {
	if x, ok := m.GetParams().(*ReactionConfigure_TrafficBalance); ok {
		return x.TrafficBalance
	}
	return nil
}

func (m *ReactionConfigure) GetTrafficRouting() *TrafficRoutingParam {
	if x, ok := m.GetParams().(*ReactionConfigure_TrafficRouting); ok {
		return x.TrafficRouting
	}
	return nil
}

func (m *ReactionConfigure) GetPreTree() []*PrerequisiteTree {
	if m != nil {
		return m.PreTree
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReactionConfigure) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _ReactionConfigure_OneofMarshaler, _ReactionConfigure_OneofUnmarshaler, _ReactionConfigure_OneofSizer, []interface{}{
		(*ReactionConfigure_FaultDelay)(nil),
		(*ReactionConfigure_TrafficBalance)(nil),
		(*ReactionConfigure_TrafficRouting)(nil),
	}
}

func _ReactionConfigure_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*ReactionConfigure)
	// params
	switch x := m.Params.(type) {
	case *ReactionConfigure_FaultDelay:
		b.EncodeVarint(2002<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.FaultDelay); err != nil {
			return err
		}
	case *ReactionConfigure_TrafficBalance:
		b.EncodeVarint(2101<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.TrafficBalance); err != nil {
			return err
		}
	case *ReactionConfigure_TrafficRouting:
		b.EncodeVarint(2102<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.TrafficRouting); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ReactionConfigure.Params has unexpected type %T", x)
	}
	return nil
}

func _ReactionConfigure_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*ReactionConfigure)
	switch tag {
	case 2002: // params.FaultDelay
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(FaultDelayParam)
		err := b.DecodeMessage(msg)
		m.Params = &ReactionConfigure_FaultDelay{msg}
		return true, err
	case 2101: // params.TrafficBalance
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(TrafficBalanceParam)
		err := b.DecodeMessage(msg)
		m.Params = &ReactionConfigure_TrafficBalance{msg}
		return true, err
	case 2102: // params.TrafficRouting
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(TrafficRoutingParam)
		err := b.DecodeMessage(msg)
		m.Params = &ReactionConfigure_TrafficRouting{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ReactionConfigure_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*ReactionConfigure)
	// params
	switch x := m.Params.(type) {
	case *ReactionConfigure_FaultDelay:
		s := proto1.Size(x.FaultDelay)
		n += proto1.SizeVarint(2002<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *ReactionConfigure_TrafficBalance:
		s := proto1.Size(x.TrafficBalance)
		n += proto1.SizeVarint(2101<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *ReactionConfigure_TrafficRouting:
		s := proto1.Size(x.TrafficRouting)
		n += proto1.SizeVarint(2102<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Path struct {
	Type PathType `protobuf:"varint,1,opt,name=type,enum=context_bus.PathType" json:"type,omitempty"`
	Path []string `protobuf:"bytes,2,rep,name=path" json:"path,omitempty"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto1.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Path) GetType() PathType {
	if m != nil {
		return m.Type
	}
	return PathType_PathType_
}

func (m *Path) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

type AttributeConfigure struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Path *Path  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
}

func (m *AttributeConfigure) Reset()                    { *m = AttributeConfigure{} }
func (m *AttributeConfigure) String() string            { return proto1.CompactTextString(m) }
func (*AttributeConfigure) ProtoMessage()               {}
func (*AttributeConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AttributeConfigure) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AttributeConfigure) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

type TimestampConfigure struct {
	Format string `protobuf:"bytes,1,opt,name=format" json:"format,omitempty"`
}

func (m *TimestampConfigure) Reset()                    { *m = TimestampConfigure{} }
func (m *TimestampConfigure) String() string            { return proto1.CompactTextString(m) }
func (*TimestampConfigure) ProtoMessage()               {}
func (*TimestampConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *TimestampConfigure) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type StackTraceConfigure struct {
}

func (m *StackTraceConfigure) Reset()                    { *m = StackTraceConfigure{} }
func (m *StackTraceConfigure) String() string            { return proto1.CompactTextString(m) }
func (*StackTraceConfigure) ProtoMessage()               {}
func (*StackTraceConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type LoggingConfigure struct {
	Timestamp  *TimestampConfigure   `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Stacktrace *StackTraceConfigure  `protobuf:"bytes,2,opt,name=stacktrace" json:"stacktrace,omitempty"`
	Attrs      []*AttributeConfigure `protobuf:"bytes,3,rep,name=attrs" json:"attrs,omitempty"`
}

func (m *LoggingConfigure) Reset()                    { *m = LoggingConfigure{} }
func (m *LoggingConfigure) String() string            { return proto1.CompactTextString(m) }
func (*LoggingConfigure) ProtoMessage()               {}
func (*LoggingConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *LoggingConfigure) GetTimestamp() *TimestampConfigure {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *LoggingConfigure) GetStacktrace() *StackTraceConfigure {
	if m != nil {
		return m.Stacktrace
	}
	return nil
}

func (m *LoggingConfigure) GetAttrs() []*AttributeConfigure {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type TracingConfigure struct {
	Attrs []*AttributeConfigure `protobuf:"bytes,1,rep,name=attrs" json:"attrs,omitempty"`
}

func (m *TracingConfigure) Reset()                    { *m = TracingConfigure{} }
func (m *TracingConfigure) String() string            { return proto1.CompactTextString(m) }
func (*TracingConfigure) ProtoMessage()               {}
func (*TracingConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *TracingConfigure) GetAttrs() []*AttributeConfigure {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type MetricsConfigure struct {
	Type MetricType `protobuf:"varint,1,opt,name=type,enum=context_bus.MetricType" json:"type,omitempty"`
	Name string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Tags []*Path    `protobuf:"bytes,3,rep,name=tags" json:"tags,omitempty"`
}

func (m *MetricsConfigure) Reset()                    { *m = MetricsConfigure{} }
func (m *MetricsConfigure) String() string            { return proto1.CompactTextString(m) }
func (*MetricsConfigure) ProtoMessage()               {}
func (*MetricsConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *MetricsConfigure) GetType() MetricType {
	if m != nil {
		return m.Type
	}
	return MetricType_MetricType_
}

func (m *MetricsConfigure) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetricsConfigure) GetTags() []*Path {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ObservationConfigure struct {
	Logging *LoggingConfigure   `protobuf:"bytes,1,opt,name=logging" json:"logging,omitempty"`
	Tracing *TracingConfigure   `protobuf:"bytes,2,opt,name=tracing" json:"tracing,omitempty"`
	Metrics []*MetricsConfigure `protobuf:"bytes,3,rep,name=metrics" json:"metrics,omitempty"`
}

func (m *ObservationConfigure) Reset()                    { *m = ObservationConfigure{} }
func (m *ObservationConfigure) String() string            { return proto1.CompactTextString(m) }
func (*ObservationConfigure) ProtoMessage()               {}
func (*ObservationConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ObservationConfigure) GetLogging() *LoggingConfigure {
	if m != nil {
		return m.Logging
	}
	return nil
}

func (m *ObservationConfigure) GetTracing() *TracingConfigure {
	if m != nil {
		return m.Tracing
	}
	return nil
}

func (m *ObservationConfigure) GetMetrics() []*MetricsConfigure {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type Configure struct {
	Reactions    map[string]*ReactionConfigure    `protobuf:"bytes,1,rep,name=reactions" json:"reactions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Observations map[string]*ObservationConfigure `protobuf:"bytes,2,rep,name=observations" json:"observations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Configure) Reset()                    { *m = Configure{} }
func (m *Configure) String() string            { return proto1.CompactTextString(m) }
func (*Configure) ProtoMessage()               {}
func (*Configure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *Configure) GetReactions() map[string]*ReactionConfigure {
	if m != nil {
		return m.Reactions
	}
	return nil
}

func (m *Configure) GetObservations() map[string]*ObservationConfigure {
	if m != nil {
		return m.Observations
	}
	return nil
}

// ******************* Environmental Profile *******************
type CPUProfile struct {
	Percent float64 `protobuf:"fixed64,1,opt,name=percent" json:"percent,omitempty"`
}

func (m *CPUProfile) Reset()                    { *m = CPUProfile{} }
func (m *CPUProfile) String() string            { return proto1.CompactTextString(m) }
func (*CPUProfile) ProtoMessage()               {}
func (*CPUProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *CPUProfile) GetPercent() float64 {
	if m != nil {
		return m.Percent
	}
	return 0
}

type MemProfile struct {
	Total       uint64  `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Available   uint64  `protobuf:"varint,2,opt,name=available" json:"available,omitempty"`
	Used        uint64  `protobuf:"varint,3,opt,name=used" json:"used,omitempty"`
	UsedPercent float64 `protobuf:"fixed64,4,opt,name=usedPercent" json:"usedPercent,omitempty"`
	Free        uint64  `protobuf:"varint,5,opt,name=free" json:"free,omitempty"`
}

func (m *MemProfile) Reset()                    { *m = MemProfile{} }
func (m *MemProfile) String() string            { return proto1.CompactTextString(m) }
func (*MemProfile) ProtoMessage()               {}
func (*MemProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *MemProfile) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *MemProfile) GetAvailable() uint64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *MemProfile) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *MemProfile) GetUsedPercent() float64 {
	if m != nil {
		return m.UsedPercent
	}
	return 0
}

func (m *MemProfile) GetFree() uint64 {
	if m != nil {
		return m.Free
	}
	return 0
}

type NetProfile struct {
	BytesSent   uint64 `protobuf:"varint,1,opt,name=bytesSent" json:"bytesSent,omitempty"`
	BytesRecv   uint64 `protobuf:"varint,2,opt,name=bytesRecv" json:"bytesRecv,omitempty"`
	PacketsSent uint64 `protobuf:"varint,3,opt,name=packetsSent" json:"packetsSent,omitempty"`
	PacketsRecv uint64 `protobuf:"varint,4,opt,name=packetsRecv" json:"packetsRecv,omitempty"`
	Errin       uint64 `protobuf:"varint,5,opt,name=errin" json:"errin,omitempty"`
	Errout      uint64 `protobuf:"varint,6,opt,name=errout" json:"errout,omitempty"`
	Dropin      uint64 `protobuf:"varint,7,opt,name=dropin" json:"dropin,omitempty"`
	Dropout     uint64 `protobuf:"varint,8,opt,name=dropout" json:"dropout,omitempty"`
}

func (m *NetProfile) Reset()                    { *m = NetProfile{} }
func (m *NetProfile) String() string            { return proto1.CompactTextString(m) }
func (*NetProfile) ProtoMessage()               {}
func (*NetProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *NetProfile) GetBytesSent() uint64 {
	if m != nil {
		return m.BytesSent
	}
	return 0
}

func (m *NetProfile) GetBytesRecv() uint64 {
	if m != nil {
		return m.BytesRecv
	}
	return 0
}

func (m *NetProfile) GetPacketsSent() uint64 {
	if m != nil {
		return m.PacketsSent
	}
	return 0
}

func (m *NetProfile) GetPacketsRecv() uint64 {
	if m != nil {
		return m.PacketsRecv
	}
	return 0
}

func (m *NetProfile) GetErrin() uint64 {
	if m != nil {
		return m.Errin
	}
	return 0
}

func (m *NetProfile) GetErrout() uint64 {
	if m != nil {
		return m.Errout
	}
	return 0
}

func (m *NetProfile) GetDropin() uint64 {
	if m != nil {
		return m.Dropin
	}
	return 0
}

func (m *NetProfile) GetDropout() uint64 {
	if m != nil {
		return m.Dropout
	}
	return 0
}

type HardwareProfile struct {
	Cpu *CPUProfile `protobuf:"bytes,1,opt,name=cpu" json:"cpu,omitempty"`
	Mem *MemProfile `protobuf:"bytes,2,opt,name=mem" json:"mem,omitempty"`
	Net *NetProfile `protobuf:"bytes,3,opt,name=net" json:"net,omitempty"`
}

func (m *HardwareProfile) Reset()                    { *m = HardwareProfile{} }
func (m *HardwareProfile) String() string            { return proto1.CompactTextString(m) }
func (*HardwareProfile) ProtoMessage()               {}
func (*HardwareProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *HardwareProfile) GetCpu() *CPUProfile {
	if m != nil {
		return m.Cpu
	}
	return nil
}

func (m *HardwareProfile) GetMem() *MemProfile {
	if m != nil {
		return m.Mem
	}
	return nil
}

func (m *HardwareProfile) GetNet() *NetProfile {
	if m != nil {
		return m.Net
	}
	return nil
}

type LanguageGo struct {
	HeapSys       uint64  `protobuf:"varint,1,opt,name=HeapSys" json:"HeapSys,omitempty"`
	HeapAlloc     uint64  `protobuf:"varint,2,opt,name=HeapAlloc" json:"HeapAlloc,omitempty"`
	HeapInuse     uint64  `protobuf:"varint,3,opt,name=HeapInuse" json:"HeapInuse,omitempty"`
	StackSys      uint64  `protobuf:"varint,4,opt,name=StackSys" json:"StackSys,omitempty"`
	StackInuse    uint64  `protobuf:"varint,5,opt,name=StackInuse" json:"StackInuse,omitempty"`
	MSpanInuse    uint64  `protobuf:"varint,6,opt,name=MSpanInuse" json:"MSpanInuse,omitempty"`
	MSpanSys      uint64  `protobuf:"varint,7,opt,name=MSpanSys" json:"MSpanSys,omitempty"`
	MCacheInuse   uint64  `protobuf:"varint,8,opt,name=MCacheInuse" json:"MCacheInuse,omitempty"`
	MCacheSys     uint64  `protobuf:"varint,9,opt,name=MCacheSys" json:"MCacheSys,omitempty"`
	LastGC        uint64  `protobuf:"varint,101,opt,name=LastGC" json:"LastGC,omitempty"`
	NextGC        uint64  `protobuf:"varint,102,opt,name=NextGC" json:"NextGC,omitempty"`
	GCCPUFraction float64 `protobuf:"fixed64,103,opt,name=GCCPUFraction" json:"GCCPUFraction,omitempty"`
}

func (m *LanguageGo) Reset()                    { *m = LanguageGo{} }
func (m *LanguageGo) String() string            { return proto1.CompactTextString(m) }
func (*LanguageGo) ProtoMessage()               {}
func (*LanguageGo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *LanguageGo) GetHeapSys() uint64 {
	if m != nil {
		return m.HeapSys
	}
	return 0
}

func (m *LanguageGo) GetHeapAlloc() uint64 {
	if m != nil {
		return m.HeapAlloc
	}
	return 0
}

func (m *LanguageGo) GetHeapInuse() uint64 {
	if m != nil {
		return m.HeapInuse
	}
	return 0
}

func (m *LanguageGo) GetStackSys() uint64 {
	if m != nil {
		return m.StackSys
	}
	return 0
}

func (m *LanguageGo) GetStackInuse() uint64 {
	if m != nil {
		return m.StackInuse
	}
	return 0
}

func (m *LanguageGo) GetMSpanInuse() uint64 {
	if m != nil {
		return m.MSpanInuse
	}
	return 0
}

func (m *LanguageGo) GetMSpanSys() uint64 {
	if m != nil {
		return m.MSpanSys
	}
	return 0
}

func (m *LanguageGo) GetMCacheInuse() uint64 {
	if m != nil {
		return m.MCacheInuse
	}
	return 0
}

func (m *LanguageGo) GetMCacheSys() uint64 {
	if m != nil {
		return m.MCacheSys
	}
	return 0
}

func (m *LanguageGo) GetLastGC() uint64 {
	if m != nil {
		return m.LastGC
	}
	return 0
}

func (m *LanguageGo) GetNextGC() uint64 {
	if m != nil {
		return m.NextGC
	}
	return 0
}

func (m *LanguageGo) GetGCCPUFraction() float64 {
	if m != nil {
		return m.GCCPUFraction
	}
	return 0
}

type LanguageJava struct {
}

func (m *LanguageJava) Reset()                    { *m = LanguageJava{} }
func (m *LanguageJava) String() string            { return proto1.CompactTextString(m) }
func (*LanguageJava) ProtoMessage()               {}
func (*LanguageJava) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type LanguageProfile struct {
	Type LanguageType `protobuf:"varint,1,opt,name=type,enum=context_bus.LanguageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Profile:
	//	*LanguageProfile_Go
	//	*LanguageProfile_Java
	Profile isLanguageProfile_Profile `protobuf_oneof:"Profile"`
}

func (m *LanguageProfile) Reset()                    { *m = LanguageProfile{} }
func (m *LanguageProfile) String() string            { return proto1.CompactTextString(m) }
func (*LanguageProfile) ProtoMessage()               {}
func (*LanguageProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type isLanguageProfile_Profile interface{ isLanguageProfile_Profile() }

type LanguageProfile_Go struct {
	Go *LanguageGo `protobuf:"bytes,2002,opt,name=go,oneof"`
}
type LanguageProfile_Java struct {
	Java *LanguageJava `protobuf:"bytes,2003,opt,name=java,oneof"`
}

func (*LanguageProfile_Go) isLanguageProfile_Profile()   {}
func (*LanguageProfile_Java) isLanguageProfile_Profile() {}

func (m *LanguageProfile) GetProfile() isLanguageProfile_Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *LanguageProfile) GetType() LanguageType {
	if m != nil {
		return m.Type
	}
	return LanguageType_LanguageType_
}

func (m *LanguageProfile) GetGo() *LanguageGo {
	if x, ok := m.GetProfile().(*LanguageProfile_Go); ok {
		return x.Go
	}
	return nil
}

func (m *LanguageProfile) GetJava() *LanguageJava {
	if x, ok := m.GetProfile().(*LanguageProfile_Java); ok {
		return x.Java
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*LanguageProfile) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _LanguageProfile_OneofMarshaler, _LanguageProfile_OneofUnmarshaler, _LanguageProfile_OneofSizer, []interface{}{
		(*LanguageProfile_Go)(nil),
		(*LanguageProfile_Java)(nil),
	}
}

func _LanguageProfile_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*LanguageProfile)
	// Profile
	switch x := m.Profile.(type) {
	case *LanguageProfile_Go:
		b.EncodeVarint(2002<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Go); err != nil {
			return err
		}
	case *LanguageProfile_Java:
		b.EncodeVarint(2003<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Java); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("LanguageProfile.Profile has unexpected type %T", x)
	}
	return nil
}

func _LanguageProfile_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*LanguageProfile)
	switch tag {
	case 2002: // Profile.go
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(LanguageGo)
		err := b.DecodeMessage(msg)
		m.Profile = &LanguageProfile_Go{msg}
		return true, err
	case 2003: // Profile.java
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(LanguageJava)
		err := b.DecodeMessage(msg)
		m.Profile = &LanguageProfile_Java{msg}
		return true, err
	default:
		return false, nil
	}
}

func _LanguageProfile_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*LanguageProfile)
	// Profile
	switch x := m.Profile.(type) {
	case *LanguageProfile_Go:
		s := proto1.Size(x.Go)
		n += proto1.SizeVarint(2002<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *LanguageProfile_Java:
		s := proto1.Size(x.Java)
		n += proto1.SizeVarint(2003<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EnvironmentalProfile struct {
	Timestamp int64            `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Hardware  *HardwareProfile `protobuf:"bytes,2,opt,name=hardware" json:"hardware,omitempty"`
	Language  *LanguageProfile `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"`
	Prev      int64            `protobuf:"varint,101,opt,name=prev" json:"prev,omitempty"`
	Next      int64            `protobuf:"varint,102,opt,name=next" json:"next,omitempty"`
}

func (m *EnvironmentalProfile) Reset()                    { *m = EnvironmentalProfile{} }
func (m *EnvironmentalProfile) String() string            { return proto1.CompactTextString(m) }
func (*EnvironmentalProfile) ProtoMessage()               {}
func (*EnvironmentalProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *EnvironmentalProfile) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *EnvironmentalProfile) GetHardware() *HardwareProfile {
	if m != nil {
		return m.Hardware
	}
	return nil
}

func (m *EnvironmentalProfile) GetLanguage() *LanguageProfile {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *EnvironmentalProfile) GetPrev() int64 {
	if m != nil {
		return m.Prev
	}
	return 0
}

func (m *EnvironmentalProfile) GetNext() int64 {
	if m != nil {
		return m.Next
	}
	return 0
}

// ******************* Event Representation
type EventWhen struct {
	Time int64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
}

func (m *EventWhen) Reset()                    { *m = EventWhen{} }
func (m *EventWhen) String() string            { return proto1.CompactTextString(m) }
func (*EventWhen) ProtoMessage()               {}
func (*EventWhen) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *EventWhen) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type AttributeValue struct {
	Type   AttributeValueType `protobuf:"varint,1,opt,name=type,enum=context_bus.AttributeValueType" json:"type,omitempty"`
	Str    string             `protobuf:"bytes,2,opt,name=str" json:"str,omitempty"`
	Struct *Attributes        `protobuf:"bytes,3,opt,name=struct" json:"struct,omitempty"`
}

func (m *AttributeValue) Reset()                    { *m = AttributeValue{} }
func (m *AttributeValue) String() string            { return proto1.CompactTextString(m) }
func (*AttributeValue) ProtoMessage()               {}
func (*AttributeValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *AttributeValue) GetType() AttributeValueType {
	if m != nil {
		return m.Type
	}
	return AttributeValueType_AttributeValueType_
}

func (m *AttributeValue) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func (m *AttributeValue) GetStruct() *Attributes {
	if m != nil {
		return m.Struct
	}
	return nil
}

type Attributes struct {
	Attrs map[string]*AttributeValue `protobuf:"bytes,1,rep,name=attrs" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Attributes) Reset()                    { *m = Attributes{} }
func (m *Attributes) String() string            { return proto1.CompactTextString(m) }
func (*Attributes) ProtoMessage()               {}
func (*Attributes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *Attributes) GetAttrs() map[string]*AttributeValue {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type EventWhere struct {
	Attrs      *Attributes `protobuf:"bytes,1,opt,name=attrs" json:"attrs,omitempty"`
	Stacktrace string      `protobuf:"bytes,2,opt,name=stacktrace" json:"stacktrace,omitempty"`
}

func (m *EventWhere) Reset()                    { *m = EventWhere{} }
func (m *EventWhere) String() string            { return proto1.CompactTextString(m) }
func (*EventWhere) ProtoMessage()               {}
func (*EventWhere) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *EventWhere) GetAttrs() *Attributes {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *EventWhere) GetStacktrace() string {
	if m != nil {
		return m.Stacktrace
	}
	return ""
}

type EventRecorder struct {
	Type EventRecorderType `protobuf:"varint,1,opt,name=type,enum=context_bus.EventRecorderType" json:"type,omitempty"`
	Name string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *EventRecorder) Reset()                    { *m = EventRecorder{} }
func (m *EventRecorder) String() string            { return proto1.CompactTextString(m) }
func (*EventRecorder) ProtoMessage()               {}
func (*EventRecorder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *EventRecorder) GetType() EventRecorderType {
	if m != nil {
		return m.Type
	}
	return EventRecorderType_EventRecorderType_
}

func (m *EventRecorder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EventMessage struct {
	Attrs   *Attributes `protobuf:"bytes,1,opt,name=attrs" json:"attrs,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *EventMessage) Reset()                    { *m = EventMessage{} }
func (m *EventMessage) String() string            { return proto1.CompactTextString(m) }
func (*EventMessage) ProtoMessage()               {}
func (*EventMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *EventMessage) GetAttrs() *Attributes {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *EventMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LibrariesMessage struct {
	Libraries map[string]*EventMessage `protobuf:"bytes,1,rep,name=libraries" json:"libraries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *LibrariesMessage) Reset()                    { *m = LibrariesMessage{} }
func (m *LibrariesMessage) String() string            { return proto1.CompactTextString(m) }
func (*LibrariesMessage) ProtoMessage()               {}
func (*LibrariesMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *LibrariesMessage) GetLibraries() map[string]*EventMessage {
	if m != nil {
		return m.Libraries
	}
	return nil
}

type EventWhat struct {
	Application *EventMessage     `protobuf:"bytes,1,opt,name=application" json:"application,omitempty"`
	Libraries   *LibrariesMessage `protobuf:"bytes,2,opt,name=libraries" json:"libraries,omitempty"`
}

func (m *EventWhat) Reset()                    { *m = EventWhat{} }
func (m *EventWhat) String() string            { return proto1.CompactTextString(m) }
func (*EventWhat) ProtoMessage()               {}
func (*EventWhat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *EventWhat) GetApplication() *EventMessage {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *EventWhat) GetLibraries() *LibrariesMessage {
	if m != nil {
		return m.Libraries
	}
	return nil
}

type EventRepresentation struct {
	When     *EventWhen     `protobuf:"bytes,1,opt,name=when" json:"when,omitempty"`
	Where    *EventWhere    `protobuf:"bytes,2,opt,name=where" json:"where,omitempty"`
	Recorder *EventRecorder `protobuf:"bytes,3,opt,name=recorder" json:"recorder,omitempty"`
	What     *EventWhat     `protobuf:"bytes,4,opt,name=what" json:"what,omitempty"`
}

func (m *EventRepresentation) Reset()                    { *m = EventRepresentation{} }
func (m *EventRepresentation) String() string            { return proto1.CompactTextString(m) }
func (*EventRepresentation) ProtoMessage()               {}
func (*EventRepresentation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *EventRepresentation) GetWhen() *EventWhen {
	if m != nil {
		return m.When
	}
	return nil
}

func (m *EventRepresentation) GetWhere() *EventWhere {
	if m != nil {
		return m.Where
	}
	return nil
}

func (m *EventRepresentation) GetRecorder() *EventRecorder {
	if m != nil {
		return m.Recorder
	}
	return nil
}

func (m *EventRepresentation) GetWhat() *EventWhat {
	if m != nil {
		return m.What
	}
	return nil
}

// ******************* Event Metadata
type ParentChildPointers struct {
	Parent   int64   `protobuf:"varint,1,opt,name=parent" json:"parent,omitempty"`
	Children []int64 `protobuf:"varint,2,rep,packed,name=children" json:"children,omitempty"`
}

func (m *ParentChildPointers) Reset()                    { *m = ParentChildPointers{} }
func (m *ParentChildPointers) String() string            { return proto1.CompactTextString(m) }
func (*ParentChildPointers) ProtoMessage()               {}
func (*ParentChildPointers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *ParentChildPointers) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *ParentChildPointers) GetChildren() []int64 {
	if m != nil {
		return m.Children
	}
	return nil
}

type EventMetadata struct {
	Id  int64                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Pcp *ParentChildPointers `protobuf:"bytes,2,opt,name=pcp" json:"pcp,omitempty"`
	Esp int64                `protobuf:"varint,3,opt,name=esp" json:"esp,omitempty"`
}

func (m *EventMetadata) Reset()                    { *m = EventMetadata{} }
func (m *EventMetadata) String() string            { return proto1.CompactTextString(m) }
func (*EventMetadata) ProtoMessage()               {}
func (*EventMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *EventMetadata) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EventMetadata) GetPcp() *ParentChildPointers {
	if m != nil {
		return m.Pcp
	}
	return nil
}

func (m *EventMetadata) GetEsp() int64 {
	if m != nil {
		return m.Esp
	}
	return 0
}

// ******************* Event Data
type EventData struct {
	Event    *EventRepresentation `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	Metadata *EventMetadata       `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
}

func (m *EventData) Reset()                    { *m = EventData{} }
func (m *EventData) String() string            { return proto1.CompactTextString(m) }
func (*EventData) ProtoMessage()               {}
func (*EventData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *EventData) GetEvent() *EventRepresentation {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *EventData) GetMetadata() *EventMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Record struct {
	Type        RecordType `protobuf:"varint,1,opt,name=type,enum=context_bus.RecordType" json:"type,omitempty"`
	Timestamp   int64      `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	MessageName string     `protobuf:"bytes,3,opt,name=message_name,json=messageName" json:"message_name,omitempty"`
	Uuid        string     `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
	Service     string     `protobuf:"bytes,5,opt,name=service" json:"service,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto1.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *Record) GetType() RecordType {
	if m != nil {
		return m.Type
	}
	return RecordType_RecordType_
}

func (m *Record) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Record) GetMessageName() string {
	if m != nil {
		return m.MessageName
	}
	return ""
}

func (m *Record) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Record) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

// ******************* Integration *******************
type LineageSnapshot struct {
	NumOfInvok map[string]int64 `protobuf:"bytes,1,rep,name=NumOfInvok" json:"NumOfInvok,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Latency    map[string]int64 `protobuf:"bytes,2,rep,name=Latency" json:"Latency,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *LineageSnapshot) Reset()                    { *m = LineageSnapshot{} }
func (m *LineageSnapshot) String() string            { return proto1.CompactTextString(m) }
func (*LineageSnapshot) ProtoMessage()               {}
func (*LineageSnapshot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *LineageSnapshot) GetNumOfInvok() map[string]int64 {
	if m != nil {
		return m.NumOfInvok
	}
	return nil
}

func (m *LineageSnapshot) GetLatency() map[string]int64 {
	if m != nil {
		return m.Latency
	}
	return nil
}

type Payload struct {
	RequestId int64            `protobuf:"varint,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	ConfigId  int64            `protobuf:"varint,2,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Snapshot  *LineageSnapshot `protobuf:"bytes,3,opt,name=snapshot" json:"snapshot,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto1.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *Payload) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Payload) GetConfigId() int64 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *Payload) GetSnapshot() *LineageSnapshot {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

func init() {
	proto1.RegisterType((*Condition)(nil), "context_bus.Condition")
	proto1.RegisterType((*PrerequisiteMessage)(nil), "context_bus.PrerequisiteMessage")
	proto1.RegisterType((*PrerequisiteLogic)(nil), "context_bus.PrerequisiteLogic")
	proto1.RegisterType((*PrerequisiteNode)(nil), "context_bus.PrerequisiteNode")
	proto1.RegisterType((*PrerequisiteTree)(nil), "context_bus.PrerequisiteTree")
	proto1.RegisterType((*PrerequisiteSnapshot)(nil), "context_bus.PrerequisiteSnapshot")
	proto1.RegisterType((*FaultDelayParam)(nil), "context_bus.FaultDelayParam")
	proto1.RegisterType((*TrafficBalanceParam)(nil), "context_bus.TrafficBalanceParam")
	proto1.RegisterType((*TrafficRoutingParam)(nil), "context_bus.TrafficRoutingParam")
	proto1.RegisterType((*ReactionConfigure)(nil), "context_bus.ReactionConfigure")
	proto1.RegisterType((*Path)(nil), "context_bus.Path")
	proto1.RegisterType((*AttributeConfigure)(nil), "context_bus.AttributeConfigure")
	proto1.RegisterType((*TimestampConfigure)(nil), "context_bus.TimestampConfigure")
	proto1.RegisterType((*StackTraceConfigure)(nil), "context_bus.StackTraceConfigure")
	proto1.RegisterType((*LoggingConfigure)(nil), "context_bus.LoggingConfigure")
	proto1.RegisterType((*TracingConfigure)(nil), "context_bus.TracingConfigure")
	proto1.RegisterType((*MetricsConfigure)(nil), "context_bus.MetricsConfigure")
	proto1.RegisterType((*ObservationConfigure)(nil), "context_bus.ObservationConfigure")
	proto1.RegisterType((*Configure)(nil), "context_bus.Configure")
	proto1.RegisterType((*CPUProfile)(nil), "context_bus.CPUProfile")
	proto1.RegisterType((*MemProfile)(nil), "context_bus.MemProfile")
	proto1.RegisterType((*NetProfile)(nil), "context_bus.NetProfile")
	proto1.RegisterType((*HardwareProfile)(nil), "context_bus.HardwareProfile")
	proto1.RegisterType((*LanguageGo)(nil), "context_bus.LanguageGo")
	proto1.RegisterType((*LanguageJava)(nil), "context_bus.LanguageJava")
	proto1.RegisterType((*LanguageProfile)(nil), "context_bus.LanguageProfile")
	proto1.RegisterType((*EnvironmentalProfile)(nil), "context_bus.EnvironmentalProfile")
	proto1.RegisterType((*EventWhen)(nil), "context_bus.EventWhen")
	proto1.RegisterType((*AttributeValue)(nil), "context_bus.AttributeValue")
	proto1.RegisterType((*Attributes)(nil), "context_bus.Attributes")
	proto1.RegisterType((*EventWhere)(nil), "context_bus.EventWhere")
	proto1.RegisterType((*EventRecorder)(nil), "context_bus.EventRecorder")
	proto1.RegisterType((*EventMessage)(nil), "context_bus.EventMessage")
	proto1.RegisterType((*LibrariesMessage)(nil), "context_bus.LibrariesMessage")
	proto1.RegisterType((*EventWhat)(nil), "context_bus.EventWhat")
	proto1.RegisterType((*EventRepresentation)(nil), "context_bus.EventRepresentation")
	proto1.RegisterType((*ParentChildPointers)(nil), "context_bus.ParentChildPointers")
	proto1.RegisterType((*EventMetadata)(nil), "context_bus.EventMetadata")
	proto1.RegisterType((*EventData)(nil), "context_bus.EventData")
	proto1.RegisterType((*Record)(nil), "context_bus.Record")
	proto1.RegisterType((*LineageSnapshot)(nil), "context_bus.LineageSnapshot")
	proto1.RegisterType((*Payload)(nil), "context_bus.Payload")
	proto1.RegisterEnum("context_bus.ConditionOperator", ConditionOperator_name, ConditionOperator_value)
	proto1.RegisterEnum("context_bus.ConditionType", ConditionType_name, ConditionType_value)
	proto1.RegisterEnum("context_bus.PrerequisiteNodeType", PrerequisiteNodeType_name, PrerequisiteNodeType_value)
	proto1.RegisterEnum("context_bus.PrerequisiteLogicType", PrerequisiteLogicType_name, PrerequisiteLogicType_value)
	proto1.RegisterEnum("context_bus.ReactionType", ReactionType_name, ReactionType_value)
	proto1.RegisterEnum("context_bus.PathType", PathType_name, PathType_value)
	proto1.RegisterEnum("context_bus.MetricType", MetricType_name, MetricType_value)
	proto1.RegisterEnum("context_bus.LanguageType", LanguageType_name, LanguageType_value)
	proto1.RegisterEnum("context_bus.AttributeValueType", AttributeValueType_name, AttributeValueType_value)
	proto1.RegisterEnum("context_bus.EventRecorderType", EventRecorderType_name, EventRecorderType_value)
	proto1.RegisterEnum("context_bus.MessageType", MessageType_name, MessageType_value)
	proto1.RegisterEnum("context_bus.RecordType", RecordType_name, RecordType_value)
}

func init() { proto1.RegisterFile("context_bus.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x59, 0xcd, 0x6e, 0x1c, 0xc7,
	0xf1, 0xd7, 0xcc, 0x2e, 0x3f, 0xb6, 0x28, 0x91, 0xc3, 0x16, 0x45, 0xad, 0x28, 0xd9, 0x96, 0x07,
	0x7f, 0xff, 0x21, 0x6f, 0x1c, 0x31, 0xa6, 0x63, 0x5b, 0xb0, 0xe1, 0xc4, 0xd2, 0x8a, 0x26, 0xe9,
	0x50, 0x24, 0xdd, 0xa4, 0x22, 0x20, 0x36, 0x40, 0x34, 0x67, 0x9b, 0xbb, 0x13, 0xed, 0x7c, 0xb8,
	0xa7, 0x77, 0xa5, 0x4d, 0x0e, 0x41, 0x80, 0x04, 0x08, 0x72, 0xcc, 0x3d, 0xc8, 0x25, 0x97, 0x3c,
	0x40, 0x92, 0x73, 0x8e, 0x49, 0x2e, 0x41, 0x92, 0x07, 0x48, 0xee, 0x39, 0xe4, 0x11, 0x82, 0xea,
	0xee, 0xf9, 0xe8, 0xdd, 0x21, 0x01, 0x9d, 0xb6, 0xab, 0xe6, 0x57, 0xd5, 0xd5, 0x55, 0xd5, 0xdd,
	0xd5, 0xb5, 0xb0, 0x1a, 0x24, 0xb1, 0xe4, 0x2f, 0xe5, 0xe9, 0xd9, 0x28, 0xbb, 0x9f, 0x8a, 0x44,
	0x26, 0x64, 0xa9, 0xc2, 0xf2, 0x7f, 0xea, 0x40, 0xab, 0x9b, 0xc4, 0xbd, 0x50, 0x86, 0x49, 0x4c,
	0xee, 0x43, 0x53, 0x4e, 0x52, 0xde, 0x76, 0xee, 0x3a, 0xf7, 0x96, 0xb7, 0x36, 0xee, 0x57, 0x85,
	0x0b, 0xd4, 0xc9, 0x24, 0xe5, 0x54, 0xe1, 0xc8, 0x7d, 0x70, 0x93, 0xb4, 0xed, 0x2a, 0xf4, 0xeb,
	0xf5, 0xe8, 0xc3, 0x94, 0x0b, 0x26, 0x13, 0x41, 0xdd, 0x24, 0x25, 0x6b, 0x30, 0x37, 0x66, 0xc3,
	0x11, 0x6f, 0x37, 0xee, 0x3a, 0xf7, 0x1a, 0x54, 0x13, 0xfe, 0x9f, 0x1d, 0xb8, 0x7e, 0x24, 0xb8,
	0xe0, 0x5f, 0x8f, 0xc2, 0x2c, 0x94, 0xfc, 0x09, 0xcf, 0x32, 0xd6, 0xe7, 0xe4, 0x7d, 0xcb, 0x9a,
	0x37, 0x2d, 0xfd, 0x55, 0xfc, 0x41, 0xd2, 0xe3, 0x15, 0xa3, 0xde, 0x84, 0xab, 0x91, 0xd6, 0x70,
	0x1a, 0xb3, 0x88, 0x2b, 0xf3, 0x5a, 0x74, 0xc9, 0xf0, 0x0e, 0x58, 0xc4, 0xc9, 0x3b, 0x30, 0x17,
	0x24, 0x71, 0x2f, 0x6b, 0x37, 0xee, 0x36, 0xee, 0x2d, 0x6d, 0xad, 0xd7, 0x9b, 0x4e, 0x35, 0x88,
	0xac, 0xc3, 0x7c, 0xca, 0x04, 0x8f, 0x65, 0xbb, 0xa7, 0xcc, 0x36, 0x14, 0x21, 0xd0, 0x1c, 0x86,
	0x99, 0x6c, 0xf3, 0xbb, 0x8d, 0x7b, 0x0d, 0xaa, 0xc6, 0xfe, 0x0b, 0x58, 0xad, 0x9a, 0xb6, 0x9f,
	0xf4, 0xc3, 0x80, 0x7c, 0x60, 0x2d, 0xc4, 0xbf, 0x70, 0x21, 0x0a, 0x5d, 0x59, 0xc9, 0xab, 0x4c,
	0xfc, 0x57, 0x07, 0xbc, 0x69, 0xa7, 0x90, 0x65, 0x70, 0xc3, 0x9e, 0x9a, 0xb6, 0x41, 0xdd, 0xb0,
	0x57, 0x78, 0xd4, 0x7d, 0x35, 0x8f, 0x7e, 0x04, 0x0b, 0xc6, 0x7b, 0x2a, 0x70, 0x4b, 0x5b, 0x77,
	0x2f, 0x94, 0x34, 0xb1, 0xa3, 0xb9, 0x00, 0xf9, 0x36, 0xcc, 0x0d, 0x71, 0x59, 0xed, 0xa6, 0x92,
	0x7c, 0xfd, 0xf2, 0xc5, 0x53, 0x0d, 0xf6, 0x4f, 0xed, 0xc5, 0x9c, 0x08, 0xce, 0xc9, 0xbb, 0xd0,
	0x4c, 0x05, 0xcf, 0xda, 0x8e, 0x8a, 0xd9, 0x6b, 0x97, 0x1a, 0x4f, 0x15, 0x94, 0xb4, 0x61, 0x61,
	0xc8, 0xd9, 0xf9, 0xde, 0xe3, 0xac, 0xed, 0x2a, 0x5f, 0xe5, 0xa4, 0xff, 0x1d, 0x58, 0xab, 0xca,
	0x1c, 0xc7, 0x2c, 0xcd, 0x06, 0x89, 0x2c, 0x33, 0xd4, 0x51, 0x78, 0x4d, 0x10, 0x0f, 0x1a, 0x2c,
	0x08, 0x94, 0xdb, 0x16, 0x29, 0x0e, 0xfd, 0x37, 0x61, 0xe5, 0x33, 0x36, 0x1a, 0xca, 0xc7, 0x7c,
	0xc8, 0x26, 0x47, 0x4c, 0xb0, 0x08, 0x9d, 0x1d, 0x65, 0xb9, 0xb3, 0xa3, 0xcc, 0xbf, 0x01, 0xd7,
	0x4f, 0x04, 0x3b, 0x3f, 0x0f, 0x83, 0x47, 0x6c, 0xc8, 0xe2, 0x80, 0x2b, 0x58, 0x85, 0x4d, 0x93,
	0x91, 0x0c, 0xe3, 0xbe, 0x66, 0xff, 0xdb, 0x85, 0x55, 0xca, 0x59, 0x80, 0x89, 0xd7, 0x4d, 0xe2,
	0xf3, 0xb0, 0x3f, 0x12, 0x9c, 0x7c, 0xd3, 0xca, 0x9c, 0x5b, 0xd6, 0x9a, 0x73, 0x74, 0x25, 0x50,
	0xdf, 0x05, 0x28, 0xad, 0x6a, 0xff, 0x7d, 0x45, 0xb9, 0xfc, 0x8e, 0x25, 0x35, 0x65, 0xf5, 0xee,
	0x15, 0x5a, 0x11, 0x21, 0xdf, 0x83, 0x65, 0xdb, 0xe6, 0xf6, 0xef, 0xbd, 0x9a, 0x88, 0xd7, 0xac,
	0x6b, 0xf7, 0x0a, 0x9d, 0x12, 0xad, 0x28, 0x33, 0x2b, 0x6d, 0xff, 0xe1, 0x12, 0x65, 0x55, 0x6f,
	0x54, 0x94, 0x19, 0x36, 0x79, 0x00, 0x8b, 0xa9, 0xe0, 0xa7, 0x52, 0x70, 0x6e, 0x76, 0xed, 0xc5,
	0x19, 0x80, 0xe9, 0x42, 0x17, 0x52, 0xa1, 0x06, 0x8f, 0x16, 0xd5, 0x2e, 0x62, 0x51, 0xe6, 0x6f,
	0x43, 0xf3, 0x88, 0xc9, 0x01, 0x79, 0xdb, 0xf2, 0xea, 0x0d, 0x5b, 0x0f, 0x93, 0x83, 0x8a, 0x47,
	0x09, 0x34, 0x53, 0x26, 0x07, 0x2a, 0x7d, 0x5a, 0x54, 0x8d, 0xfd, 0x43, 0x20, 0x0f, 0xa5, 0x14,
	0xe1, 0xd9, 0x48, 0xf2, 0x32, 0x54, 0x04, 0x9a, 0xea, 0xb8, 0x71, 0xd4, 0x71, 0xa3, 0xc6, 0xe4,
	0xad, 0x42, 0x1a, 0x97, 0xbd, 0x3a, 0x33, 0x91, 0x51, 0xf8, 0x0e, 0x90, 0x93, 0x30, 0xe2, 0x99,
	0x64, 0x51, 0x5a, 0x2a, 0x5c, 0x87, 0xf9, 0xf3, 0x44, 0x44, 0x4c, 0x1a, 0x95, 0x86, 0xc2, 0x04,
	0x3a, 0x96, 0x2c, 0x78, 0x7e, 0x22, 0x58, 0x50, 0xce, 0xef, 0xff, 0xc5, 0x01, 0x6f, 0x3f, 0xe9,
	0xf7, 0xc3, 0xb8, 0x5f, 0xea, 0xf8, 0x04, 0x5a, 0x32, 0xd7, 0xac, 0xd4, 0x2c, 0x6d, 0xbd, 0x61,
	0x3b, 0x7f, 0x66, 0x5e, 0x5a, 0x4a, 0x90, 0x4f, 0x01, 0x32, 0x9c, 0x4a, 0xe2, 0x54, 0x66, 0x15,
	0x76, 0xf0, 0x6a, 0x2c, 0xa1, 0x15, 0x19, 0xf2, 0x3e, 0xcc, 0x31, 0x29, 0x45, 0x7e, 0xd2, 0xda,
	0x93, 0xcf, 0x7a, 0x91, 0x6a, 0xb4, 0xbf, 0x07, 0x1e, 0x2a, 0xb5, 0xd6, 0x52, 0xa8, 0x72, 0x5e,
	0x49, 0xd5, 0x8f, 0xc0, 0x7b, 0xc2, 0xa5, 0x08, 0x83, 0xac, 0x54, 0xf5, 0x0d, 0x2b, 0x01, 0x6e,
	0x5a, 0x9a, 0x34, 0xd8, 0x4e, 0x81, 0xca, 0x3d, 0x52, 0x04, 0x56, 0xb2, 0x7e, 0xbe, 0xaa, 0xba,
	0xc0, 0xe2, 0x67, 0xff, 0x4f, 0x0e, 0xac, 0x1d, 0x9e, 0x65, 0x5c, 0x8c, 0x99, 0xbd, 0xaf, 0x3f,
	0x84, 0x85, 0xa1, 0x8e, 0x95, 0x89, 0x8a, 0x9d, 0xcc, 0xd3, 0x71, 0xa4, 0x39, 0x1a, 0x05, 0xa5,
	0x76, 0x8c, 0x09, 0xc7, 0x6b, 0xd3, 0x7b, 0x29, 0xb0, 0x05, 0x0d, 0x1a, 0x05, 0x23, 0xed, 0x86,
	0xda, 0xed, 0x33, 0xed, 0x22, 0x9a, 0xa3, 0xfd, 0x7f, 0xb9, 0xaa, 0x42, 0x30, 0x86, 0x77, 0xa1,
	0x25, 0xcc, 0xb9, 0x93, 0x07, 0xe2, 0xad, 0xe9, 0xdb, 0x53, 0x43, 0x8b, 0xf3, 0x29, 0xdb, 0x8e,
	0xa5, 0x98, 0xd0, 0x52, 0x8e, 0xec, 0xc3, 0xd5, 0xa4, 0xf4, 0x8a, 0x3e, 0x9b, 0x97, 0xb6, 0xee,
	0x5d, 0xa0, 0xa7, 0xe2, 0x40, 0xa3, 0xca, 0x92, 0xde, 0xf8, 0x0a, 0x96, 0xed, 0xa9, 0xf0, 0xb8,
	0x7e, 0xce, 0x27, 0x66, 0xdb, 0xe0, 0x10, 0x6f, 0x21, 0x7d, 0xac, 0xbb, 0x35, 0xb7, 0xd0, 0xcc,
	0xb1, 0x6b, 0x8e, 0xfd, 0x8f, 0xdc, 0x07, 0xce, 0xc6, 0x19, 0xac, 0xce, 0x18, 0x50, 0x33, 0xc1,
	0x87, 0xf6, 0x04, 0xf6, 0xd5, 0x5a, 0x97, 0x02, 0x95, 0x39, 0xfc, 0xff, 0x07, 0xe8, 0x1e, 0x3d,
	0x3d, 0x12, 0xc9, 0x79, 0x38, 0xe4, 0x78, 0x69, 0xa5, 0x5c, 0x04, 0x78, 0xed, 0xe3, 0x04, 0x0e,
	0xcd, 0x49, 0xff, 0x97, 0x0e, 0xc0, 0x13, 0x1e, 0xe5, 0xc0, 0x35, 0x98, 0x93, 0x89, 0x64, 0x43,
	0x05, 0x6b, 0x52, 0x4d, 0x90, 0x3b, 0xd0, 0x62, 0x63, 0x16, 0x0e, 0xd9, 0xd9, 0x50, 0x5b, 0xd3,
	0xa4, 0x25, 0x03, 0x93, 0x79, 0x94, 0xf1, 0x9e, 0xba, 0xc7, 0x9b, 0x54, 0x8d, 0xc9, 0x5d, 0x58,
	0xc2, 0xdf, 0x23, 0x33, 0x69, 0x53, 0x4d, 0x5a, 0x65, 0xa1, 0xd4, 0x39, 0x1e, 0xbc, 0x73, 0x5a,
	0x0a, 0xc7, 0xfe, 0x7f, 0x1c, 0x80, 0x03, 0x2e, 0x73, 0x63, 0xee, 0x40, 0xeb, 0x6c, 0x22, 0x79,
	0x76, 0x9c, 0xdb, 0xdd, 0xa4, 0x25, 0xa3, 0xf8, 0x4a, 0x79, 0x30, 0xce, 0x8d, 0x2a, 0x18, 0x68,
	0x40, 0xca, 0x82, 0xe7, 0x5c, 0x6a, 0x69, 0x6d, 0x5b, 0x95, 0x55, 0x41, 0x28, 0x0d, 0x4d, 0x0b,
	0xa1, 0x74, 0xac, 0xc1, 0x1c, 0x17, 0x22, 0x8c, 0x8d, 0x8d, 0x9a, 0xc0, 0x33, 0x94, 0x0b, 0x91,
	0x8c, 0x64, 0x7b, 0x5e, 0xb1, 0x0d, 0x85, 0xfc, 0x9e, 0x48, 0xd2, 0x30, 0x6e, 0x2f, 0x68, 0xbe,
	0xa6, 0xd0, 0xf7, 0x38, 0x42, 0x81, 0x45, 0xf5, 0x21, 0x27, 0xfd, 0x5f, 0x39, 0xb0, 0xb2, 0xcb,
	0x44, 0xef, 0x05, 0x13, 0x3c, 0x5f, 0xf3, 0xdb, 0xd0, 0x08, 0xd2, 0x91, 0xd9, 0xc1, 0xf6, 0x29,
	0x52, 0xc6, 0x93, 0x22, 0x06, 0xa1, 0x11, 0x8f, 0x4c, 0x76, 0x4c, 0x1f, 0x38, 0x51, 0x01, 0x8d,
	0x78, 0x84, 0xd0, 0x98, 0x4b, 0x53, 0x69, 0xd9, 0xd0, 0xd2, 0xdf, 0x14, 0x31, 0xfe, 0x7f, 0x5d,
	0x80, 0x7d, 0x16, 0xf7, 0x47, 0xac, 0xcf, 0x77, 0x12, 0xb4, 0x7e, 0x97, 0xb3, 0xf4, 0x78, 0x92,
	0x99, 0x08, 0xe4, 0x24, 0xfa, 0x1f, 0x87, 0x0f, 0x87, 0xc3, 0x24, 0xc8, 0xfd, 0x5f, 0x30, 0xf2,
	0xaf, 0x7b, 0xf1, 0x28, 0xe3, 0xc6, 0xfb, 0x25, 0x83, 0x6c, 0xc0, 0xa2, 0x3a, 0xe5, 0x51, 0xad,
	0x76, 0x7c, 0x41, 0x93, 0xd7, 0x01, 0xd4, 0x58, 0x8b, 0x6a, 0xd7, 0x57, 0x38, 0xf8, 0xfd, 0xc9,
	0x71, 0xca, 0x62, 0xfd, 0x5d, 0xc7, 0xa0, 0xc2, 0x41, 0xdd, 0x8a, 0x42, 0xdd, 0x3a, 0x12, 0x05,
	0x8d, 0x31, 0x7f, 0xd2, 0x65, 0xc1, 0x80, 0x6b, 0x61, 0x1d, 0x8f, 0x2a, 0x0b, 0xed, 0xd6, 0x24,
	0x8a, 0xb7, 0xb4, 0xdd, 0x05, 0x03, 0x63, 0xbc, 0xcf, 0x32, 0xb9, 0xd3, 0x6d, 0x73, 0x1d, 0x63,
	0x4d, 0x21, 0xff, 0x80, 0xbf, 0x44, 0xfe, 0xb9, 0xe6, 0x6b, 0x8a, 0xfc, 0x1f, 0x5c, 0xdb, 0xe9,
	0x76, 0x8f, 0x9e, 0x7e, 0x26, 0xf4, 0x71, 0xd0, 0xee, 0xab, 0x8d, 0x60, 0x33, 0xfd, 0x65, 0xb8,
	0x9a, 0x7b, 0xfc, 0x73, 0x36, 0x66, 0xfe, 0xef, 0x1c, 0x58, 0xc9, 0x19, 0x79, 0x5e, 0x5c, 0x56,
	0xb5, 0xe5, 0xd8, 0xca, 0x05, 0xd3, 0x01, 0xb7, 0x9f, 0xe4, 0xd5, 0xda, 0xcd, 0x5a, 0xf4, 0x4e,
	0xb2, 0x7b, 0x85, 0xba, 0xfd, 0x84, 0x7c, 0x0b, 0x9a, 0x3f, 0x64, 0x63, 0xd6, 0xfe, 0x87, 0x46,
	0xd7, 0xeb, 0x46, 0xc3, 0x76, 0xaf, 0x50, 0x85, 0x7c, 0xd4, 0x82, 0x05, 0x63, 0x97, 0xff, 0x37,
	0x07, 0xd6, 0xb6, 0xe3, 0x71, 0x28, 0x92, 0x38, 0xe2, 0xb1, 0x64, 0xc3, 0xca, 0xe6, 0xb5, 0xcb,
	0x84, 0x46, 0xb5, 0x0a, 0x78, 0x00, 0x8b, 0x03, 0x93, 0xf9, 0x26, 0x81, 0xed, 0x92, 0x72, 0x6a,
	0x5b, 0xd0, 0x02, 0x8d, 0x92, 0x43, 0x63, 0x93, 0xc9, 0xe7, 0x3b, 0xb5, 0x06, 0x17, 0x92, 0x39,
	0x5a, 0xd5, 0x5d, 0x82, 0x8f, 0x55, 0xe8, 0x1a, 0xaa, 0x9a, 0x1f, 0xab, 0x8b, 0x98, 0xbf, 0x94,
	0x2a, 0x6c, 0x0d, 0xaa, 0xc6, 0xfe, 0x1b, 0xd0, 0xda, 0x1e, 0xf3, 0x58, 0x3e, 0x1b, 0xf0, 0x18,
	0x01, 0x68, 0xb5, 0x59, 0x81, 0x1a, 0xfb, 0xbf, 0x70, 0x60, 0xb9, 0x28, 0x0e, 0xbe, 0xaf, 0xaa,
	0xf9, 0xf7, 0xac, 0xf0, 0x5c, 0x50, 0x47, 0x28, 0x68, 0x25, 0x48, 0x1e, 0x34, 0x32, 0x29, 0x4c,
	0x11, 0x80, 0x43, 0xb2, 0x09, 0xf3, 0x99, 0x14, 0xa3, 0xa0, 0x7e, 0xab, 0x16, 0x8a, 0x32, 0x6a,
	0x60, 0xfe, 0xaf, 0x1d, 0x80, 0x92, 0x4d, 0x1e, 0xd8, 0xf5, 0x8c, 0x7f, 0x81, 0xb8, 0x1a, 0x9a,
	0x8b, 0x4f, 0x0b, 0x6c, 0x3c, 0xd5, 0x7a, 0x2e, 0xbc, 0x8c, 0xde, 0xb5, 0x2f, 0xa3, 0xdb, 0x97,
	0xac, 0xb0, 0x7a, 0x0d, 0x7d, 0x09, 0x90, 0xfb, 0x52, 0x3d, 0x3d, 0x0a, 0xf3, 0x2e, 0x5d, 0x9d,
	0x46, 0xe1, 0x4e, 0x9f, 0x2a, 0x15, 0x5b, 0xd5, 0x42, 0xd0, 0x7f, 0x06, 0xd7, 0x94, 0x72, 0xca,
	0x83, 0x44, 0xf4, 0xb8, 0x20, 0x5b, 0x56, 0x14, 0xec, 0x1b, 0xd9, 0x42, 0x5e, 0x5e, 0x8a, 0xf9,
	0xcf, 0xe0, 0xaa, 0x82, 0xe7, 0x5d, 0x83, 0x57, 0xb4, 0xbb, 0x5d, 0xbe, 0x6d, 0xb5, 0xd6, 0x9c,
	0xf4, 0xff, 0x88, 0x05, 0x75, 0x78, 0x26, 0x98, 0x08, 0x79, 0x96, 0x6b, 0xff, 0x1c, 0x5a, 0xc3,
	0x9c, 0x67, 0x02, 0xf7, 0x8e, 0x9d, 0xd2, 0x53, 0x12, 0x25, 0xc3, 0x94, 0x41, 0x85, 0xf8, 0xc6,
	0x33, 0x58, 0xb6, 0x3f, 0xd6, 0x84, 0x72, 0xd3, 0x0e, 0xe5, 0xad, 0x59, 0x37, 0xe5, 0x2f, 0xee,
	0x4a, 0x20, 0x7f, 0xee, 0x14, 0xbb, 0x82, 0x49, 0xf2, 0x31, 0x2c, 0xb1, 0x34, 0x1d, 0x86, 0x81,
	0x2a, 0x40, 0x8c, 0x5b, 0x2e, 0x51, 0x54, 0x45, 0x93, 0x8f, 0xab, 0xeb, 0xad, 0xab, 0x38, 0xa7,
	0xd7, 0x5b, 0x59, 0xa0, 0xff, 0x4f, 0x07, 0xae, 0x9b, 0x50, 0xe2, 0x73, 0x1c, 0x8f, 0x1c, 0xa5,
	0xb4, 0x03, 0xcd, 0x17, 0x03, 0x9e, 0x9b, 0xb2, 0x3e, 0x6b, 0x0a, 0xee, 0x66, 0xaa, 0x30, 0x18,
	0xce, 0x17, 0x98, 0x8f, 0xb5, 0x57, 0x67, 0x99, 0xae, 0x54, 0xa3, 0xc8, 0x07, 0xb0, 0x28, 0x4c,
	0xde, 0x98, 0x6d, 0xb9, 0x71, 0x71, 0x66, 0xd1, 0x02, 0xab, 0x4d, 0x62, 0xd2, 0x74, 0x29, 0x6a,
	0x4d, 0x62, 0x92, 0x2a, 0x8c, 0xbf, 0x07, 0xd7, 0x8f, 0x54, 0x23, 0xa6, 0x3b, 0x08, 0x87, 0xbd,
	0xa3, 0x24, 0x8c, 0x25, 0x17, 0xd5, 0x36, 0x91, 0x63, 0x75, 0x6b, 0x36, 0x60, 0x31, 0x40, 0xa0,
	0xe0, 0xb1, 0xe9, 0x42, 0x14, 0xb4, 0xcf, 0xcd, 0xae, 0x78, 0xc2, 0x25, 0xeb, 0x31, 0xc9, 0x66,
	0x3a, 0x36, 0x5b, 0xd0, 0x48, 0x83, 0xb4, 0xf6, 0xe9, 0x55, 0x63, 0x03, 0x45, 0x30, 0x66, 0x11,
	0xcf, 0x52, 0xd3, 0x63, 0xc3, 0xa1, 0xff, 0x63, 0x93, 0x0f, 0x8f, 0x71, 0x8a, 0x0f, 0x60, 0x8e,
	0x8f, 0x73, 0x33, 0xa7, 0x95, 0xd6, 0x84, 0x8b, 0x6a, 0x38, 0xba, 0x36, 0x32, 0x66, 0x1a, 0x7b,
	0x36, 0xea, 0x92, 0x48, 0x23, 0x68, 0x81, 0xf5, 0x7f, 0xeb, 0xc0, 0xbc, 0xf6, 0xf8, 0xa5, 0xef,
	0x2e, 0x0d, 0xa9, 0x6c, 0x76, 0xeb, 0x52, 0x72, 0xa7, 0x2f, 0xa5, 0xe9, 0x2e, 0x5f, 0x63, 0xb6,
	0xcb, 0x87, 0xb5, 0xee, 0x28, 0xec, 0xa9, 0x98, 0xb6, 0xa8, 0x1a, 0xe3, 0x76, 0xc7, 0x5a, 0x3c,
	0x0c, 0x74, 0xb5, 0xd2, 0xa2, 0x39, 0xe9, 0xff, 0xc6, 0x85, 0x95, 0xfd, 0x30, 0xe6, 0xac, 0x5f,
	0x76, 0x83, 0xf6, 0x01, 0x0e, 0x46, 0xd1, 0xe1, 0xf9, 0x5e, 0x3c, 0x4e, 0x9e, 0x5f, 0xb0, 0xdd,
	0x2d, 0x89, 0xfb, 0x25, 0x5c, 0x6f, 0xf7, 0x8a, 0x3c, 0xe9, 0xc2, 0xc2, 0x3e, 0x93, 0x3c, 0x0e,
	0x26, 0xe6, 0xc5, 0xf3, 0xf6, 0xa5, 0xaa, 0x0c, 0x56, 0xeb, 0xc9, 0x25, 0x37, 0x3e, 0x81, 0x95,
	0xa9, 0x39, 0x6a, 0x4e, 0x8d, 0xb5, 0xea, 0xa9, 0xd1, 0xa8, 0x3e, 0x67, 0x3e, 0xc2, 0xf2, 0xa5,
	0xd4, 0xfb, 0x2a, 0xb2, 0xfe, 0x4f, 0x60, 0xe1, 0x88, 0x4d, 0x86, 0x09, 0xeb, 0x91, 0xd7, 0x00,
	0x04, 0xff, 0x7a, 0xc4, 0x33, 0x79, 0x5a, 0xa4, 0x6b, 0xcb, 0x70, 0xf6, 0x7a, 0xe4, 0x36, 0xb4,
	0x02, 0xf5, 0xd0, 0xc1, 0xaf, 0x5a, 0xcf, 0xa2, 0x66, 0xec, 0xf5, 0xb0, 0x28, 0xc8, 0xcc, 0x1a,
	0xeb, 0x8b, 0x02, 0xdb, 0x0f, 0xb4, 0x40, 0x77, 0xbe, 0x84, 0xd5, 0x99, 0xbe, 0x32, 0x59, 0x07,
	0x32, 0xc3, 0x3c, 0xf5, 0xae, 0x90, 0x79, 0x70, 0xf7, 0x4f, 0x3c, 0x07, 0x7f, 0x77, 0x4e, 0x3c,
	0x57, 0xd1, 0xdb, 0x5e, 0x43, 0xd1, 0xdb, 0x5e, 0x13, 0x7f, 0xb7, 0xbf, 0xf0, 0xe6, 0xf0, 0xf7,
	0x60, 0xdb, 0x9b, 0xef, 0x7c, 0x0a, 0xd7, 0xac, 0x16, 0x37, 0x21, 0xb0, 0x6c, 0x31, 0x50, 0xe9,
	0x72, 0x35, 0x21, 0x3c, 0x87, 0x2c, 0x15, 0x21, 0xf5, 0xdc, 0xce, 0x9e, 0xdd, 0x53, 0xcc, 0x9b,
	0xa8, 0xe4, 0x16, 0xdc, 0xa8, 0xe3, 0xa3, 0xbe, 0x25, 0x58, 0x30, 0xe7, 0xa6, 0xe7, 0x90, 0x16,
	0xcc, 0xa9, 0x26, 0xa8, 0xe7, 0x76, 0x1e, 0xdb, 0x22, 0x45, 0x63, 0x98, 0x6c, 0xc0, 0x7a, 0xed,
	0x07, 0x54, 0xb6, 0x00, 0x8d, 0x87, 0x71, 0x4f, 0x2f, 0xf9, 0x50, 0x78, 0x6e, 0xe7, 0x25, 0x5c,
	0xad, 0x36, 0x09, 0xc9, 0x2a, 0x5c, 0xab, 0xd2, 0x66, 0x41, 0xaa, 0xfd, 0xd7, 0x15, 0x2c, 0x1b,
	0x78, 0x4e, 0x41, 0xab, 0x76, 0xa0, 0xe7, 0x92, 0x6b, 0xd0, 0xd2, 0xb4, 0x48, 0x52, 0xaf, 0x81,
	0x3e, 0xb1, 0x9b, 0x7c, 0x1e, 0xaf, 0xf0, 0x4c, 0xaf, 0xce, 0x3b, 0xef, 0x7c, 0x08, 0x8b, 0x79,
	0x23, 0x0d, 0x55, 0xe4, 0x63, 0x9c, 0x71, 0x05, 0x96, 0x1e, 0x96, 0x17, 0x8c, 0xf1, 0xa1, 0xba,
	0x32, 0xd0, 0x87, 0x5f, 0xe0, 0x0b, 0x37, 0x6f, 0xc0, 0x20, 0xb6, 0xa4, 0x8c, 0xbf, 0xba, 0xc9,
	0x08, 0xcf, 0x3a, 0xed, 0xaf, 0x1d, 0x36, 0xea, 0x73, 0x6d, 0xe6, 0x6e, 0x98, 0xc9, 0xa4, 0x2f,
	0x58, 0xe4, 0x35, 0x10, 0x76, 0x3c, 0x8a, 0x22, 0x2e, 0x26, 0x5e, 0xb3, 0xf3, 0xa8, 0xac, 0xd8,
	0x73, 0x2f, 0x54, 0x69, 0x54, 0xdb, 0x82, 0xb9, 0x43, 0x39, 0x50, 0x4a, 0x01, 0xe6, 0x77, 0x12,
	0x2c, 0x43, 0x3d, 0x97, 0x2c, 0x42, 0x13, 0x4b, 0x69, 0xaf, 0xd1, 0xf9, 0xaa, 0xd2, 0xf2, 0x2b,
	0x2a, 0x43, 0x72, 0x13, 0xae, 0xcf, 0x72, 0x51, 0xdf, 0x0d, 0x58, 0xb5, 0x3f, 0x1c, 0x4b, 0xd4,
	0xbd, 0x3e, 0xad, 0x05, 0x29, 0xcf, 0xed, 0xfc, 0xcc, 0x81, 0xd5, 0x99, 0x92, 0x07, 0xd1, 0x33,
	0x4c, 0x54, 0xfe, 0x06, 0xdc, 0xb6, 0xf8, 0xc7, 0xfa, 0x00, 0xdb, 0x65, 0x71, 0x6f, 0xa8, 0x96,
	0x70, 0x0b, 0x6e, 0x58, 0x80, 0xcf, 0x46, 0xb1, 0x8a, 0xb9, 0xe7, 0x92, 0xdb, 0x70, 0xd3, 0xd6,
	0x39, 0x08, 0x45, 0xef, 0x88, 0x09, 0x39, 0xf1, 0x1a, 0x9d, 0xcf, 0xd1, 0xdb, 0x2a, 0x19, 0x4f,
	0x74, 0xc5, 0x7b, 0xb5, 0x42, 0xe2, 0xcc, 0xd7, 0x61, 0xc5, 0x70, 0x4e, 0xa9, 0xde, 0xeb, 0x9e,
	0x43, 0xd6, 0xc0, 0x2b, 0x99, 0x59, 0x9a, 0xc4, 0x19, 0xf7, 0xdc, 0xce, 0xa7, 0x00, 0xe5, 0x81,
	0x8e, 0x71, 0x2c, 0x29, 0x93, 0x76, 0x9a, 0x71, 0xcc, 0x55, 0xc6, 0xaa, 0xcc, 0x44, 0x9a, 0xf2,
	0x80, 0x87, 0x63, 0xee, 0xb9, 0x8f, 0xde, 0xff, 0xc1, 0x7b, 0xfd, 0x50, 0x0e, 0x46, 0x67, 0xf7,
	0x83, 0x24, 0xda, 0x7c, 0x38, 0xe4, 0xc1, 0xf3, 0xc7, 0x4c, 0x04, 0x93, 0x4d, 0xc1, 0xf1, 0x08,
	0xda, 0x0c, 0x12, 0xc1, 0x37, 0x2b, 0xe7, 0xc6, 0xa6, 0xfa, 0x77, 0xeb, 0x6c, 0x5e, 0xfd, 0xbc,
	0xf7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x11, 0x47, 0x05, 0x3a, 0xf9, 0x1a, 0x00, 0x00,
}
