// Code generated by protoc-gen-go. DO NOT EDIT.
// source: context_bus.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	context_bus.proto

It has these top-level messages:
	ConditionMessage
	ConditionLogic
	ConditionNode
	ConditionTree
	PrerequisiteMessage
	PrerequisiteLogic
	PrerequisiteNode
	PrerequisiteTree
	PrerequisiteSnapshot
	PrerequisiteSnapshots
	FaultDelayParam
	TrafficBalanceParam
	TrafficRoutingParam
	ReactionConfigure
	Path
	AttributeConfigure
	TimestampConfigure
	StackTraceConfigure
	LoggingConfigure
	TracingConfigure
	MetricsConfigure
	ObservationConfigure
	Configure
	CPUProfile
	MemProfile
	NetProfile
	HardwareProfile
	LanguageGo
	LanguageJava
	LanguageProfile
	EnvironmentalProfile
	EventWhen
	AttributeValue
	Attributes
	CodeBaseInfo
	EventWhere
	EventRecorder
	EventMessage
	LibrariesMessage
	EventWhat
	EventRepresentation
	ParentChildPointers
	EventMetadata
	EventData
	Record
	PrometheusOpts
	PrometheusHistogramOpts
	PrometheusSummaryObjective
	PrometheusSummaryOpts
	PrometheusConfiguration
	Payload
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ConditionOperator int32

const (
	ConditionOperator_ConditionOperator_ ConditionOperator = 0
	ConditionOperator_LT                 ConditionOperator = 1
	ConditionOperator_GT                 ConditionOperator = 2
	ConditionOperator_LE                 ConditionOperator = 3
	ConditionOperator_GE                 ConditionOperator = 4
	ConditionOperator_EQ                 ConditionOperator = 5
	ConditionOperator_NE                 ConditionOperator = 6
)

var ConditionOperator_name = map[int32]string{
	0: "ConditionOperator_",
	1: "LT",
	2: "GT",
	3: "LE",
	4: "GE",
	5: "EQ",
	6: "NE",
}
var ConditionOperator_value = map[string]int32{
	"ConditionOperator_": 0,
	"LT":                 1,
	"GT":                 2,
	"LE":                 3,
	"GE":                 4,
	"EQ":                 5,
	"NE":                 6,
}

func (x ConditionOperator) String() string {
	return proto1.EnumName(ConditionOperator_name, int32(x))
}
func (ConditionOperator) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ConditionType int32

const (
	ConditionType_ConditionType_ ConditionType = 0
	ConditionType_NumOfInvok     ConditionType = 1
	ConditionType_Latency        ConditionType = 2
)

var ConditionType_name = map[int32]string{
	0: "ConditionType_",
	1: "NumOfInvok",
	2: "Latency",
}
var ConditionType_value = map[string]int32{
	"ConditionType_": 0,
	"NumOfInvok":     1,
	"Latency":        2,
}

func (x ConditionType) String() string {
	return proto1.EnumName(ConditionType_name, int32(x))
}
func (ConditionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ConditionNodeType int32

const (
	ConditionNodeType_ConditionNodeType_ ConditionNodeType = 0
	ConditionNodeType_ConditionMessage_  ConditionNodeType = 1
	ConditionNodeType_ConditionLogic_    ConditionNodeType = 2
)

var ConditionNodeType_name = map[int32]string{
	0: "ConditionNodeType_",
	1: "ConditionMessage_",
	2: "ConditionLogic_",
}
var ConditionNodeType_value = map[string]int32{
	"ConditionNodeType_": 0,
	"ConditionMessage_":  1,
	"ConditionLogic_":    2,
}

func (x ConditionNodeType) String() string {
	return proto1.EnumName(ConditionNodeType_name, int32(x))
}
func (ConditionNodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type LogicType int32

const (
	LogicType_LogicType_ LogicType = 0
	LogicType_And_       LogicType = 1
	LogicType_Or_        LogicType = 2
)

var LogicType_name = map[int32]string{
	0: "LogicType_",
	1: "And_",
	2: "Or_",
}
var LogicType_value = map[string]int32{
	"LogicType_": 0,
	"And_":       1,
	"Or_":        2,
}

func (x LogicType) String() string {
	return proto1.EnumName(LogicType_name, int32(x))
}
func (LogicType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type PrerequisiteNodeType int32

const (
	PrerequisiteNodeType_PrerequisiteNodeType_ PrerequisiteNodeType = 0
	PrerequisiteNodeType_PrerequisiteMessage_  PrerequisiteNodeType = 1
	PrerequisiteNodeType_PrerequisiteLogic_    PrerequisiteNodeType = 2
)

var PrerequisiteNodeType_name = map[int32]string{
	0: "PrerequisiteNodeType_",
	1: "PrerequisiteMessage_",
	2: "PrerequisiteLogic_",
}
var PrerequisiteNodeType_value = map[string]int32{
	"PrerequisiteNodeType_": 0,
	"PrerequisiteMessage_":  1,
	"PrerequisiteLogic_":    2,
}

func (x PrerequisiteNodeType) String() string {
	return proto1.EnumName(PrerequisiteNodeType_name, int32(x))
}
func (PrerequisiteNodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ReactionType int32

const (
	ReactionType_ReactionType_ ReactionType = 0
	// fault injection
	ReactionType_FaultCrash ReactionType = 1
	ReactionType_FaultDelay ReactionType = 2
	ReactionType_FaultDrop  ReactionType = 3
	// traffic (e.g., load-balancing, traffic shaping)
	ReactionType_TrafficBalance ReactionType = 101
	ReactionType_TrafficRouting ReactionType = 102
)

var ReactionType_name = map[int32]string{
	0:   "ReactionType_",
	1:   "FaultCrash",
	2:   "FaultDelay",
	3:   "FaultDrop",
	101: "TrafficBalance",
	102: "TrafficRouting",
}
var ReactionType_value = map[string]int32{
	"ReactionType_":  0,
	"FaultCrash":     1,
	"FaultDelay":     2,
	"FaultDrop":      3,
	"TrafficBalance": 101,
	"TrafficRouting": 102,
}

func (x ReactionType) String() string {
	return proto1.EnumName(ReactionType_name, int32(x))
}
func (ReactionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type PathType int32

const (
	PathType_PathType_   PathType = 0
	PathType_Application PathType = 1
	PathType_Library     PathType = 2
)

var PathType_name = map[int32]string{
	0: "PathType_",
	1: "Application",
	2: "Library",
}
var PathType_value = map[string]int32{
	"PathType_":   0,
	"Application": 1,
	"Library":     2,
}

func (x PathType) String() string {
	return proto1.EnumName(PathType_name, int32(x))
}
func (PathType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type LogOutType int32

const (
	LogOutType_LogOutType_ LogOutType = 0
	LogOutType_Stdout      LogOutType = 1
	LogOutType_Stderr      LogOutType = 2
	LogOutType_File        LogOutType = 3
)

var LogOutType_name = map[int32]string{
	0: "LogOutType_",
	1: "Stdout",
	2: "Stderr",
	3: "File",
}
var LogOutType_value = map[string]int32{
	"LogOutType_": 0,
	"Stdout":      1,
	"Stderr":      2,
	"File":        3,
}

func (x LogOutType) String() string {
	return proto1.EnumName(LogOutType_name, int32(x))
}
func (LogOutType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type MetricType int32

const (
	MetricType_MetricType_ MetricType = 0
	MetricType_Counter     MetricType = 1
	MetricType_Gauge       MetricType = 2
	MetricType_Histogram   MetricType = 3
	MetricType_Summary     MetricType = 4
)

var MetricType_name = map[int32]string{
	0: "MetricType_",
	1: "Counter",
	2: "Gauge",
	3: "Histogram",
	4: "Summary",
}
var MetricType_value = map[string]int32{
	"MetricType_": 0,
	"Counter":     1,
	"Gauge":       2,
	"Histogram":   3,
	"Summary":     4,
}

func (x MetricType) String() string {
	return proto1.EnumName(MetricType_name, int32(x))
}
func (MetricType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type ObservationType int32

const (
	ObservationType_ObservationType_  ObservationType = 0
	ObservationType_ObservationSingle ObservationType = 1
	ObservationType_ObservationStart  ObservationType = 2
	ObservationType_ObservationInter  ObservationType = 3
	ObservationType_ObservationEnd    ObservationType = 4
)

var ObservationType_name = map[int32]string{
	0: "ObservationType_",
	1: "ObservationSingle",
	2: "ObservationStart",
	3: "ObservationInter",
	4: "ObservationEnd",
}
var ObservationType_value = map[string]int32{
	"ObservationType_":  0,
	"ObservationSingle": 1,
	"ObservationStart":  2,
	"ObservationInter":  3,
	"ObservationEnd":    4,
}

func (x ObservationType) String() string {
	return proto1.EnumName(ObservationType_name, int32(x))
}
func (ObservationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type LanguageType int32

const (
	LanguageType_LanguageType_ LanguageType = 0
	LanguageType_Other         LanguageType = 1
	LanguageType_Golang        LanguageType = 2
	LanguageType_Java          LanguageType = 3
)

var LanguageType_name = map[int32]string{
	0: "LanguageType_",
	1: "Other",
	2: "Golang",
	3: "Java",
}
var LanguageType_value = map[string]int32{
	"LanguageType_": 0,
	"Other":         1,
	"Golang":        2,
	"Java":          3,
}

func (x LanguageType) String() string {
	return proto1.EnumName(LanguageType_name, int32(x))
}
func (LanguageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type AttributeValueType int32

const (
	AttributeValueType_AttributeValueType_ AttributeValueType = 0
	AttributeValueType_AttributeValueStr   AttributeValueType = 1
	AttributeValueType_AttributeValueAttr  AttributeValueType = 2
)

var AttributeValueType_name = map[int32]string{
	0: "AttributeValueType_",
	1: "AttributeValueStr",
	2: "AttributeValueAttr",
}
var AttributeValueType_value = map[string]int32{
	"AttributeValueType_": 0,
	"AttributeValueStr":   1,
	"AttributeValueAttr":  2,
}

func (x AttributeValueType) String() string {
	return proto1.EnumName(AttributeValueType_name, int32(x))
}
func (AttributeValueType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type EventRecorderType int32

const (
	EventRecorderType_EventRecorderType_          EventRecorderType = 0
	EventRecorderType_EventRecorderServiceHandler EventRecorderType = 1
	EventRecorderType_EventRecorderFunction       EventRecorderType = 2
	EventRecorderType_EventRecorderThirdParty     EventRecorderType = 3
)

var EventRecorderType_name = map[int32]string{
	0: "EventRecorderType_",
	1: "EventRecorderServiceHandler",
	2: "EventRecorderFunction",
	3: "EventRecorderThirdParty",
}
var EventRecorderType_value = map[string]int32{
	"EventRecorderType_":          0,
	"EventRecorderServiceHandler": 1,
	"EventRecorderFunction":       2,
	"EventRecorderThirdParty":     3,
}

func (x EventRecorderType) String() string {
	return proto1.EnumName(EventRecorderType_name, int32(x))
}
func (EventRecorderType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

// ******************* from 3mb WIP
type MessageType int32

const (
	MessageType_MessageType_     MessageType = 0
	MessageType_Message_Request  MessageType = 1
	MessageType_Message_Response MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "MessageType_",
	1: "Message_Request",
	2: "Message_Response",
}
var MessageType_value = map[string]int32{
	"MessageType_":     0,
	"Message_Request":  1,
	"Message_Response": 2,
}

func (x MessageType) String() string {
	return proto1.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type ActionType int32

const (
	ActionType_ActionType_   ActionType = 0
	ActionType_ActionSend    ActionType = 1
	ActionType_ActionReceive ActionType = 2
)

var ActionType_name = map[int32]string{
	0: "ActionType_",
	1: "ActionSend",
	2: "ActionReceive",
}
var ActionType_value = map[string]int32{
	"ActionType_":   0,
	"ActionSend":    1,
	"ActionReceive": 2,
}

func (x ActionType) String() string {
	return proto1.EnumName(ActionType_name, int32(x))
}
func (ActionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type ConditionMessage struct {
	Type  ConditionType     `protobuf:"varint,1,opt,name=type,enum=context_bus.ConditionType" json:"type,omitempty"`
	Op    ConditionOperator `protobuf:"varint,2,opt,name=op,enum=context_bus.ConditionOperator" json:"op,omitempty"`
	Value int64             `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
}

func (m *ConditionMessage) Reset()                    { *m = ConditionMessage{} }
func (m *ConditionMessage) String() string            { return proto1.CompactTextString(m) }
func (*ConditionMessage) ProtoMessage()               {}
func (*ConditionMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ConditionMessage) GetType() ConditionType {
	if m != nil {
		return m.Type
	}
	return ConditionType_ConditionType_
}

func (m *ConditionMessage) GetOp() ConditionOperator {
	if m != nil {
		return m.Op
	}
	return ConditionOperator_ConditionOperator_
}

func (m *ConditionMessage) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type ConditionLogic struct {
	Type   LogicType `protobuf:"varint,1,opt,name=type,enum=context_bus.LogicType" json:"type,omitempty"`
	Parent int64     `protobuf:"varint,100,opt,name=parent" json:"parent,omitempty"`
	List   []int64   `protobuf:"varint,101,rep,packed,name=list" json:"list,omitempty"`
}

func (m *ConditionLogic) Reset()                    { *m = ConditionLogic{} }
func (m *ConditionLogic) String() string            { return proto1.CompactTextString(m) }
func (*ConditionLogic) ProtoMessage()               {}
func (*ConditionLogic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ConditionLogic) GetType() LogicType {
	if m != nil {
		return m.Type
	}
	return LogicType_LogicType_
}

func (m *ConditionLogic) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *ConditionLogic) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

type ConditionNode struct {
	Type    ConditionNodeType `protobuf:"varint,2,opt,name=type,enum=context_bus.ConditionNodeType" json:"type,omitempty"`
	Message *ConditionMessage `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Logic   *ConditionLogic   `protobuf:"bytes,4,opt,name=logic" json:"logic,omitempty"`
}

func (m *ConditionNode) Reset()                    { *m = ConditionNode{} }
func (m *ConditionNode) String() string            { return proto1.CompactTextString(m) }
func (*ConditionNode) ProtoMessage()               {}
func (*ConditionNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ConditionNode) GetType() ConditionNodeType {
	if m != nil {
		return m.Type
	}
	return ConditionNodeType_ConditionNodeType_
}

func (m *ConditionNode) GetMessage() *ConditionMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ConditionNode) GetLogic() *ConditionLogic {
	if m != nil {
		return m.Logic
	}
	return nil
}

type ConditionTree struct {
	Nodes   []*ConditionNode `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	LeafIDs []int64          `protobuf:"varint,2,rep,packed,name=leafIDs" json:"leafIDs,omitempty"`
}

func (m *ConditionTree) Reset()                    { *m = ConditionTree{} }
func (m *ConditionTree) String() string            { return proto1.CompactTextString(m) }
func (*ConditionTree) ProtoMessage()               {}
func (*ConditionTree) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ConditionTree) GetNodes() []*ConditionNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *ConditionTree) GetLeafIDs() []int64 {
	if m != nil {
		return m.LeafIDs
	}
	return nil
}

type PrerequisiteMessage struct {
	Name     string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	CondTree *ConditionTree `protobuf:"bytes,2,opt,name=cond_tree,json=condTree" json:"cond_tree,omitempty"`
	Parent   int64          `protobuf:"varint,100,opt,name=parent" json:"parent,omitempty"`
}

func (m *PrerequisiteMessage) Reset()                    { *m = PrerequisiteMessage{} }
func (m *PrerequisiteMessage) String() string            { return proto1.CompactTextString(m) }
func (*PrerequisiteMessage) ProtoMessage()               {}
func (*PrerequisiteMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PrerequisiteMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PrerequisiteMessage) GetCondTree() *ConditionTree {
	if m != nil {
		return m.CondTree
	}
	return nil
}

func (m *PrerequisiteMessage) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

type PrerequisiteLogic struct {
	Type   LogicType `protobuf:"varint,1,opt,name=type,enum=context_bus.LogicType" json:"type,omitempty"`
	Parent int64     `protobuf:"varint,100,opt,name=parent" json:"parent,omitempty"`
	List   []int64   `protobuf:"varint,101,rep,packed,name=list" json:"list,omitempty"`
}

func (m *PrerequisiteLogic) Reset()                    { *m = PrerequisiteLogic{} }
func (m *PrerequisiteLogic) String() string            { return proto1.CompactTextString(m) }
func (*PrerequisiteLogic) ProtoMessage()               {}
func (*PrerequisiteLogic) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PrerequisiteLogic) GetType() LogicType {
	if m != nil {
		return m.Type
	}
	return LogicType_LogicType_
}

func (m *PrerequisiteLogic) GetParent() int64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *PrerequisiteLogic) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

type PrerequisiteNode struct {
	Id      int64                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type    PrerequisiteNodeType `protobuf:"varint,2,opt,name=type,enum=context_bus.PrerequisiteNodeType" json:"type,omitempty"`
	Message *PrerequisiteMessage `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Logic   *PrerequisiteLogic   `protobuf:"bytes,4,opt,name=logic" json:"logic,omitempty"`
}

func (m *PrerequisiteNode) Reset()                    { *m = PrerequisiteNode{} }
func (m *PrerequisiteNode) String() string            { return proto1.CompactTextString(m) }
func (*PrerequisiteNode) ProtoMessage()               {}
func (*PrerequisiteNode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PrerequisiteNode) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PrerequisiteNode) GetType() PrerequisiteNodeType {
	if m != nil {
		return m.Type
	}
	return PrerequisiteNodeType_PrerequisiteNodeType_
}

func (m *PrerequisiteNode) GetMessage() *PrerequisiteMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *PrerequisiteNode) GetLogic() *PrerequisiteLogic {
	if m != nil {
		return m.Logic
	}
	return nil
}

// prerequisite tree
type PrerequisiteTree struct {
	Nodes   []*PrerequisiteNode `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	LeafIDs []int64             `protobuf:"varint,2,rep,packed,name=leafIDs" json:"leafIDs,omitempty"`
}

func (m *PrerequisiteTree) Reset()                    { *m = PrerequisiteTree{} }
func (m *PrerequisiteTree) String() string            { return proto1.CompactTextString(m) }
func (*PrerequisiteTree) ProtoMessage()               {}
func (*PrerequisiteTree) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PrerequisiteTree) GetNodes() []*PrerequisiteNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *PrerequisiteTree) GetLeafIDs() []int64 {
	if m != nil {
		return m.LeafIDs
	}
	return nil
}

type PrerequisiteSnapshot struct {
	Value []int64 `protobuf:"varint,1,rep,packed,name=value" json:"value,omitempty"`
	Acc   bool    `protobuf:"varint,2,opt,name=acc" json:"acc,omitempty"`
}

func (m *PrerequisiteSnapshot) Reset()                    { *m = PrerequisiteSnapshot{} }
func (m *PrerequisiteSnapshot) String() string            { return proto1.CompactTextString(m) }
func (*PrerequisiteSnapshot) ProtoMessage()               {}
func (*PrerequisiteSnapshot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PrerequisiteSnapshot) GetValue() []int64 {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PrerequisiteSnapshot) GetAcc() bool {
	if m != nil {
		return m.Acc
	}
	return false
}

type PrerequisiteSnapshots struct {
	Snapshots map[string]*PrerequisiteSnapshot `protobuf:"bytes,1,rep,name=snapshots" json:"snapshots,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *PrerequisiteSnapshots) Reset()                    { *m = PrerequisiteSnapshots{} }
func (m *PrerequisiteSnapshots) String() string            { return proto1.CompactTextString(m) }
func (*PrerequisiteSnapshots) ProtoMessage()               {}
func (*PrerequisiteSnapshots) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PrerequisiteSnapshots) GetSnapshots() map[string]*PrerequisiteSnapshot {
	if m != nil {
		return m.Snapshots
	}
	return nil
}

type FaultDelayParam struct {
	Ms int64 `protobuf:"varint,1,opt,name=ms" json:"ms,omitempty"`
}

func (m *FaultDelayParam) Reset()                    { *m = FaultDelayParam{} }
func (m *FaultDelayParam) String() string            { return proto1.CompactTextString(m) }
func (*FaultDelayParam) ProtoMessage()               {}
func (*FaultDelayParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *FaultDelayParam) GetMs() int64 {
	if m != nil {
		return m.Ms
	}
	return 0
}

type TrafficBalanceParam struct {
}

func (m *TrafficBalanceParam) Reset()                    { *m = TrafficBalanceParam{} }
func (m *TrafficBalanceParam) String() string            { return proto1.CompactTextString(m) }
func (*TrafficBalanceParam) ProtoMessage()               {}
func (*TrafficBalanceParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type TrafficRoutingParam struct {
}

func (m *TrafficRoutingParam) Reset()                    { *m = TrafficRoutingParam{} }
func (m *TrafficRoutingParam) String() string            { return proto1.CompactTextString(m) }
func (*TrafficRoutingParam) ProtoMessage()               {}
func (*TrafficRoutingParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type ReactionConfigure struct {
	Type ReactionType `protobuf:"varint,1,opt,name=type,enum=context_bus.ReactionType" json:"type,omitempty"`
	// Types that are valid to be assigned to Params:
	//	*ReactionConfigure_FaultDelay
	//	*ReactionConfigure_TrafficBalance
	//	*ReactionConfigure_TrafficRouting
	Params  isReactionConfigure_Params `protobuf_oneof:"params"`
	PreTree *PrerequisiteTree          `protobuf:"bytes,3,opt,name=pre_tree,json=preTree" json:"pre_tree,omitempty"`
}

func (m *ReactionConfigure) Reset()                    { *m = ReactionConfigure{} }
func (m *ReactionConfigure) String() string            { return proto1.CompactTextString(m) }
func (*ReactionConfigure) ProtoMessage()               {}
func (*ReactionConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type isReactionConfigure_Params interface{ isReactionConfigure_Params() }

type ReactionConfigure_FaultDelay struct {
	FaultDelay *FaultDelayParam `protobuf:"bytes,2002,opt,name=FaultDelay,oneof"`
}
type ReactionConfigure_TrafficBalance struct {
	TrafficBalance *TrafficBalanceParam `protobuf:"bytes,2101,opt,name=TrafficBalance,oneof"`
}
type ReactionConfigure_TrafficRouting struct {
	TrafficRouting *TrafficRoutingParam `protobuf:"bytes,2102,opt,name=TrafficRouting,oneof"`
}

func (*ReactionConfigure_FaultDelay) isReactionConfigure_Params()     {}
func (*ReactionConfigure_TrafficBalance) isReactionConfigure_Params() {}
func (*ReactionConfigure_TrafficRouting) isReactionConfigure_Params() {}

func (m *ReactionConfigure) GetParams() isReactionConfigure_Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *ReactionConfigure) GetType() ReactionType {
	if m != nil {
		return m.Type
	}
	return ReactionType_ReactionType_
}

func (m *ReactionConfigure) GetFaultDelay() *FaultDelayParam {
	if x, ok := m.GetParams().(*ReactionConfigure_FaultDelay); ok {
		return x.FaultDelay
	}
	return nil
}

func (m *ReactionConfigure) GetTrafficBalance() *TrafficBalanceParam {
	if x, ok := m.GetParams().(*ReactionConfigure_TrafficBalance); ok {
		return x.TrafficBalance
	}
	return nil
}

func (m *ReactionConfigure) GetTrafficRouting() *TrafficRoutingParam {
	if x, ok := m.GetParams().(*ReactionConfigure_TrafficRouting); ok {
		return x.TrafficRouting
	}
	return nil
}

func (m *ReactionConfigure) GetPreTree() *PrerequisiteTree {
	if m != nil {
		return m.PreTree
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReactionConfigure) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _ReactionConfigure_OneofMarshaler, _ReactionConfigure_OneofUnmarshaler, _ReactionConfigure_OneofSizer, []interface{}{
		(*ReactionConfigure_FaultDelay)(nil),
		(*ReactionConfigure_TrafficBalance)(nil),
		(*ReactionConfigure_TrafficRouting)(nil),
	}
}

func _ReactionConfigure_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*ReactionConfigure)
	// params
	switch x := m.Params.(type) {
	case *ReactionConfigure_FaultDelay:
		b.EncodeVarint(2002<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.FaultDelay); err != nil {
			return err
		}
	case *ReactionConfigure_TrafficBalance:
		b.EncodeVarint(2101<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.TrafficBalance); err != nil {
			return err
		}
	case *ReactionConfigure_TrafficRouting:
		b.EncodeVarint(2102<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.TrafficRouting); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ReactionConfigure.Params has unexpected type %T", x)
	}
	return nil
}

func _ReactionConfigure_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*ReactionConfigure)
	switch tag {
	case 2002: // params.FaultDelay
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(FaultDelayParam)
		err := b.DecodeMessage(msg)
		m.Params = &ReactionConfigure_FaultDelay{msg}
		return true, err
	case 2101: // params.TrafficBalance
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(TrafficBalanceParam)
		err := b.DecodeMessage(msg)
		m.Params = &ReactionConfigure_TrafficBalance{msg}
		return true, err
	case 2102: // params.TrafficRouting
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(TrafficRoutingParam)
		err := b.DecodeMessage(msg)
		m.Params = &ReactionConfigure_TrafficRouting{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ReactionConfigure_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*ReactionConfigure)
	// params
	switch x := m.Params.(type) {
	case *ReactionConfigure_FaultDelay:
		s := proto1.Size(x.FaultDelay)
		n += proto1.SizeVarint(2002<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *ReactionConfigure_TrafficBalance:
		s := proto1.Size(x.TrafficBalance)
		n += proto1.SizeVarint(2101<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *ReactionConfigure_TrafficRouting:
		s := proto1.Size(x.TrafficRouting)
		n += proto1.SizeVarint(2102<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Path struct {
	Type PathType `protobuf:"varint,1,opt,name=type,enum=context_bus.PathType" json:"type,omitempty"`
	Path []string `protobuf:"bytes,2,rep,name=path" json:"path,omitempty"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto1.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Path) GetType() PathType {
	if m != nil {
		return m.Type
	}
	return PathType_PathType_
}

func (m *Path) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

type AttributeConfigure struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Path *Path  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
}

func (m *AttributeConfigure) Reset()                    { *m = AttributeConfigure{} }
func (m *AttributeConfigure) String() string            { return proto1.CompactTextString(m) }
func (*AttributeConfigure) ProtoMessage()               {}
func (*AttributeConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *AttributeConfigure) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AttributeConfigure) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

type TimestampConfigure struct {
	Format string `protobuf:"bytes,1,opt,name=format" json:"format,omitempty"`
}

func (m *TimestampConfigure) Reset()                    { *m = TimestampConfigure{} }
func (m *TimestampConfigure) String() string            { return proto1.CompactTextString(m) }
func (*TimestampConfigure) ProtoMessage()               {}
func (*TimestampConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *TimestampConfigure) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type StackTraceConfigure struct {
}

func (m *StackTraceConfigure) Reset()                    { *m = StackTraceConfigure{} }
func (m *StackTraceConfigure) String() string            { return proto1.CompactTextString(m) }
func (*StackTraceConfigure) ProtoMessage()               {}
func (*StackTraceConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type LoggingConfigure struct {
	Timestamp  *TimestampConfigure   `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Stacktrace *StackTraceConfigure  `protobuf:"bytes,2,opt,name=stacktrace" json:"stacktrace,omitempty"`
	Attrs      []*AttributeConfigure `protobuf:"bytes,3,rep,name=attrs" json:"attrs,omitempty"`
	Out        LogOutType            `protobuf:"varint,4,opt,name=out,enum=context_bus.LogOutType" json:"out,omitempty"`
}

func (m *LoggingConfigure) Reset()                    { *m = LoggingConfigure{} }
func (m *LoggingConfigure) String() string            { return proto1.CompactTextString(m) }
func (*LoggingConfigure) ProtoMessage()               {}
func (*LoggingConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *LoggingConfigure) GetTimestamp() *TimestampConfigure {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *LoggingConfigure) GetStacktrace() *StackTraceConfigure {
	if m != nil {
		return m.Stacktrace
	}
	return nil
}

func (m *LoggingConfigure) GetAttrs() []*AttributeConfigure {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *LoggingConfigure) GetOut() LogOutType {
	if m != nil {
		return m.Out
	}
	return LogOutType_LogOutType_
}

type TracingConfigure struct {
	Name     string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	PrevName string                `protobuf:"bytes,2,opt,name=prev_name,json=prevName" json:"prev_name,omitempty"`
	Attrs    []*AttributeConfigure `protobuf:"bytes,3,rep,name=attrs" json:"attrs,omitempty"`
}

func (m *TracingConfigure) Reset()                    { *m = TracingConfigure{} }
func (m *TracingConfigure) String() string            { return proto1.CompactTextString(m) }
func (*TracingConfigure) ProtoMessage()               {}
func (*TracingConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *TracingConfigure) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TracingConfigure) GetPrevName() string {
	if m != nil {
		return m.PrevName
	}
	return ""
}

func (m *TracingConfigure) GetAttrs() []*AttributeConfigure {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type MetricsConfigure struct {
	Type     MetricType            `protobuf:"varint,1,opt,name=type,enum=context_bus.MetricType" json:"type,omitempty"`
	OptsId   int64                 `protobuf:"varint,2,opt,name=opts_id,json=optsId" json:"opts_id,omitempty"`
	Name     string                `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	PrevName string                `protobuf:"bytes,4,opt,name=prev_name,json=prevName" json:"prev_name,omitempty"`
	Attrs    []*AttributeConfigure `protobuf:"bytes,5,rep,name=attrs" json:"attrs,omitempty"`
}

func (m *MetricsConfigure) Reset()                    { *m = MetricsConfigure{} }
func (m *MetricsConfigure) String() string            { return proto1.CompactTextString(m) }
func (*MetricsConfigure) ProtoMessage()               {}
func (*MetricsConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *MetricsConfigure) GetType() MetricType {
	if m != nil {
		return m.Type
	}
	return MetricType_MetricType_
}

func (m *MetricsConfigure) GetOptsId() int64 {
	if m != nil {
		return m.OptsId
	}
	return 0
}

func (m *MetricsConfigure) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetricsConfigure) GetPrevName() string {
	if m != nil {
		return m.PrevName
	}
	return ""
}

func (m *MetricsConfigure) GetAttrs() []*AttributeConfigure {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type ObservationConfigure struct {
	Type    ObservationType     `protobuf:"varint,1,opt,name=type,enum=context_bus.ObservationType" json:"type,omitempty"`
	Logging *LoggingConfigure   `protobuf:"bytes,2,opt,name=logging" json:"logging,omitempty"`
	Tracing *TracingConfigure   `protobuf:"bytes,3,opt,name=tracing" json:"tracing,omitempty"`
	Metrics []*MetricsConfigure `protobuf:"bytes,4,rep,name=metrics" json:"metrics,omitempty"`
}

func (m *ObservationConfigure) Reset()                    { *m = ObservationConfigure{} }
func (m *ObservationConfigure) String() string            { return proto1.CompactTextString(m) }
func (*ObservationConfigure) ProtoMessage()               {}
func (*ObservationConfigure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ObservationConfigure) GetType() ObservationType {
	if m != nil {
		return m.Type
	}
	return ObservationType_ObservationType_
}

func (m *ObservationConfigure) GetLogging() *LoggingConfigure {
	if m != nil {
		return m.Logging
	}
	return nil
}

func (m *ObservationConfigure) GetTracing() *TracingConfigure {
	if m != nil {
		return m.Tracing
	}
	return nil
}

func (m *ObservationConfigure) GetMetrics() []*MetricsConfigure {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type Configure struct {
	Reactions    map[string]*ReactionConfigure    `protobuf:"bytes,1,rep,name=reactions" json:"reactions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Observations map[string]*ObservationConfigure `protobuf:"bytes,2,rep,name=observations" json:"observations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Configure) Reset()                    { *m = Configure{} }
func (m *Configure) String() string            { return proto1.CompactTextString(m) }
func (*Configure) ProtoMessage()               {}
func (*Configure) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *Configure) GetReactions() map[string]*ReactionConfigure {
	if m != nil {
		return m.Reactions
	}
	return nil
}

func (m *Configure) GetObservations() map[string]*ObservationConfigure {
	if m != nil {
		return m.Observations
	}
	return nil
}

// ******************* Environmental Profile *******************
type CPUProfile struct {
	Percent float64 `protobuf:"fixed64,1,opt,name=percent" json:"percent,omitempty"`
}

func (m *CPUProfile) Reset()                    { *m = CPUProfile{} }
func (m *CPUProfile) String() string            { return proto1.CompactTextString(m) }
func (*CPUProfile) ProtoMessage()               {}
func (*CPUProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *CPUProfile) GetPercent() float64 {
	if m != nil {
		return m.Percent
	}
	return 0
}

type MemProfile struct {
	Total       uint64  `protobuf:"varint,1,opt,name=total" json:"total,omitempty"`
	Available   uint64  `protobuf:"varint,2,opt,name=available" json:"available,omitempty"`
	Used        uint64  `protobuf:"varint,3,opt,name=used" json:"used,omitempty"`
	UsedPercent float64 `protobuf:"fixed64,4,opt,name=usedPercent" json:"usedPercent,omitempty"`
	Free        uint64  `protobuf:"varint,5,opt,name=free" json:"free,omitempty"`
}

func (m *MemProfile) Reset()                    { *m = MemProfile{} }
func (m *MemProfile) String() string            { return proto1.CompactTextString(m) }
func (*MemProfile) ProtoMessage()               {}
func (*MemProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *MemProfile) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *MemProfile) GetAvailable() uint64 {
	if m != nil {
		return m.Available
	}
	return 0
}

func (m *MemProfile) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *MemProfile) GetUsedPercent() float64 {
	if m != nil {
		return m.UsedPercent
	}
	return 0
}

func (m *MemProfile) GetFree() uint64 {
	if m != nil {
		return m.Free
	}
	return 0
}

type NetProfile struct {
	BytesSent   uint64 `protobuf:"varint,1,opt,name=bytesSent" json:"bytesSent,omitempty"`
	BytesRecv   uint64 `protobuf:"varint,2,opt,name=bytesRecv" json:"bytesRecv,omitempty"`
	PacketsSent uint64 `protobuf:"varint,3,opt,name=packetsSent" json:"packetsSent,omitempty"`
	PacketsRecv uint64 `protobuf:"varint,4,opt,name=packetsRecv" json:"packetsRecv,omitempty"`
	Errin       uint64 `protobuf:"varint,5,opt,name=errin" json:"errin,omitempty"`
	Errout      uint64 `protobuf:"varint,6,opt,name=errout" json:"errout,omitempty"`
	Dropin      uint64 `protobuf:"varint,7,opt,name=dropin" json:"dropin,omitempty"`
	Dropout     uint64 `protobuf:"varint,8,opt,name=dropout" json:"dropout,omitempty"`
}

func (m *NetProfile) Reset()                    { *m = NetProfile{} }
func (m *NetProfile) String() string            { return proto1.CompactTextString(m) }
func (*NetProfile) ProtoMessage()               {}
func (*NetProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *NetProfile) GetBytesSent() uint64 {
	if m != nil {
		return m.BytesSent
	}
	return 0
}

func (m *NetProfile) GetBytesRecv() uint64 {
	if m != nil {
		return m.BytesRecv
	}
	return 0
}

func (m *NetProfile) GetPacketsSent() uint64 {
	if m != nil {
		return m.PacketsSent
	}
	return 0
}

func (m *NetProfile) GetPacketsRecv() uint64 {
	if m != nil {
		return m.PacketsRecv
	}
	return 0
}

func (m *NetProfile) GetErrin() uint64 {
	if m != nil {
		return m.Errin
	}
	return 0
}

func (m *NetProfile) GetErrout() uint64 {
	if m != nil {
		return m.Errout
	}
	return 0
}

func (m *NetProfile) GetDropin() uint64 {
	if m != nil {
		return m.Dropin
	}
	return 0
}

func (m *NetProfile) GetDropout() uint64 {
	if m != nil {
		return m.Dropout
	}
	return 0
}

type HardwareProfile struct {
	Cpu *CPUProfile `protobuf:"bytes,1,opt,name=cpu" json:"cpu,omitempty"`
	Mem *MemProfile `protobuf:"bytes,2,opt,name=mem" json:"mem,omitempty"`
	Net *NetProfile `protobuf:"bytes,3,opt,name=net" json:"net,omitempty"`
}

func (m *HardwareProfile) Reset()                    { *m = HardwareProfile{} }
func (m *HardwareProfile) String() string            { return proto1.CompactTextString(m) }
func (*HardwareProfile) ProtoMessage()               {}
func (*HardwareProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *HardwareProfile) GetCpu() *CPUProfile {
	if m != nil {
		return m.Cpu
	}
	return nil
}

func (m *HardwareProfile) GetMem() *MemProfile {
	if m != nil {
		return m.Mem
	}
	return nil
}

func (m *HardwareProfile) GetNet() *NetProfile {
	if m != nil {
		return m.Net
	}
	return nil
}

type LanguageGo struct {
	HeapSys       uint64  `protobuf:"varint,1,opt,name=HeapSys" json:"HeapSys,omitempty"`
	HeapAlloc     uint64  `protobuf:"varint,2,opt,name=HeapAlloc" json:"HeapAlloc,omitempty"`
	HeapInuse     uint64  `protobuf:"varint,3,opt,name=HeapInuse" json:"HeapInuse,omitempty"`
	StackSys      uint64  `protobuf:"varint,4,opt,name=StackSys" json:"StackSys,omitempty"`
	StackInuse    uint64  `protobuf:"varint,5,opt,name=StackInuse" json:"StackInuse,omitempty"`
	MSpanInuse    uint64  `protobuf:"varint,6,opt,name=MSpanInuse" json:"MSpanInuse,omitempty"`
	MSpanSys      uint64  `protobuf:"varint,7,opt,name=MSpanSys" json:"MSpanSys,omitempty"`
	MCacheInuse   uint64  `protobuf:"varint,8,opt,name=MCacheInuse" json:"MCacheInuse,omitempty"`
	MCacheSys     uint64  `protobuf:"varint,9,opt,name=MCacheSys" json:"MCacheSys,omitempty"`
	LastGC        uint64  `protobuf:"varint,101,opt,name=LastGC" json:"LastGC,omitempty"`
	NextGC        uint64  `protobuf:"varint,102,opt,name=NextGC" json:"NextGC,omitempty"`
	GCCPUFraction float64 `protobuf:"fixed64,103,opt,name=GCCPUFraction" json:"GCCPUFraction,omitempty"`
}

func (m *LanguageGo) Reset()                    { *m = LanguageGo{} }
func (m *LanguageGo) String() string            { return proto1.CompactTextString(m) }
func (*LanguageGo) ProtoMessage()               {}
func (*LanguageGo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *LanguageGo) GetHeapSys() uint64 {
	if m != nil {
		return m.HeapSys
	}
	return 0
}

func (m *LanguageGo) GetHeapAlloc() uint64 {
	if m != nil {
		return m.HeapAlloc
	}
	return 0
}

func (m *LanguageGo) GetHeapInuse() uint64 {
	if m != nil {
		return m.HeapInuse
	}
	return 0
}

func (m *LanguageGo) GetStackSys() uint64 {
	if m != nil {
		return m.StackSys
	}
	return 0
}

func (m *LanguageGo) GetStackInuse() uint64 {
	if m != nil {
		return m.StackInuse
	}
	return 0
}

func (m *LanguageGo) GetMSpanInuse() uint64 {
	if m != nil {
		return m.MSpanInuse
	}
	return 0
}

func (m *LanguageGo) GetMSpanSys() uint64 {
	if m != nil {
		return m.MSpanSys
	}
	return 0
}

func (m *LanguageGo) GetMCacheInuse() uint64 {
	if m != nil {
		return m.MCacheInuse
	}
	return 0
}

func (m *LanguageGo) GetMCacheSys() uint64 {
	if m != nil {
		return m.MCacheSys
	}
	return 0
}

func (m *LanguageGo) GetLastGC() uint64 {
	if m != nil {
		return m.LastGC
	}
	return 0
}

func (m *LanguageGo) GetNextGC() uint64 {
	if m != nil {
		return m.NextGC
	}
	return 0
}

func (m *LanguageGo) GetGCCPUFraction() float64 {
	if m != nil {
		return m.GCCPUFraction
	}
	return 0
}

type LanguageJava struct {
}

func (m *LanguageJava) Reset()                    { *m = LanguageJava{} }
func (m *LanguageJava) String() string            { return proto1.CompactTextString(m) }
func (*LanguageJava) ProtoMessage()               {}
func (*LanguageJava) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type LanguageProfile struct {
	Type LanguageType `protobuf:"varint,1,opt,name=type,enum=context_bus.LanguageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Profile:
	//	*LanguageProfile_Go
	//	*LanguageProfile_Java
	Profile isLanguageProfile_Profile `protobuf_oneof:"Profile"`
}

func (m *LanguageProfile) Reset()                    { *m = LanguageProfile{} }
func (m *LanguageProfile) String() string            { return proto1.CompactTextString(m) }
func (*LanguageProfile) ProtoMessage()               {}
func (*LanguageProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

type isLanguageProfile_Profile interface{ isLanguageProfile_Profile() }

type LanguageProfile_Go struct {
	Go *LanguageGo `protobuf:"bytes,2002,opt,name=go,oneof"`
}
type LanguageProfile_Java struct {
	Java *LanguageJava `protobuf:"bytes,2003,opt,name=java,oneof"`
}

func (*LanguageProfile_Go) isLanguageProfile_Profile()   {}
func (*LanguageProfile_Java) isLanguageProfile_Profile() {}

func (m *LanguageProfile) GetProfile() isLanguageProfile_Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *LanguageProfile) GetType() LanguageType {
	if m != nil {
		return m.Type
	}
	return LanguageType_LanguageType_
}

func (m *LanguageProfile) GetGo() *LanguageGo {
	if x, ok := m.GetProfile().(*LanguageProfile_Go); ok {
		return x.Go
	}
	return nil
}

func (m *LanguageProfile) GetJava() *LanguageJava {
	if x, ok := m.GetProfile().(*LanguageProfile_Java); ok {
		return x.Java
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*LanguageProfile) XXX_OneofFuncs() (func(msg proto1.Message, b *proto1.Buffer) error, func(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error), func(msg proto1.Message) (n int), []interface{}) {
	return _LanguageProfile_OneofMarshaler, _LanguageProfile_OneofUnmarshaler, _LanguageProfile_OneofSizer, []interface{}{
		(*LanguageProfile_Go)(nil),
		(*LanguageProfile_Java)(nil),
	}
}

func _LanguageProfile_OneofMarshaler(msg proto1.Message, b *proto1.Buffer) error {
	m := msg.(*LanguageProfile)
	// Profile
	switch x := m.Profile.(type) {
	case *LanguageProfile_Go:
		b.EncodeVarint(2002<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Go); err != nil {
			return err
		}
	case *LanguageProfile_Java:
		b.EncodeVarint(2003<<3 | proto1.WireBytes)
		if err := b.EncodeMessage(x.Java); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("LanguageProfile.Profile has unexpected type %T", x)
	}
	return nil
}

func _LanguageProfile_OneofUnmarshaler(msg proto1.Message, tag, wire int, b *proto1.Buffer) (bool, error) {
	m := msg.(*LanguageProfile)
	switch tag {
	case 2002: // Profile.go
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(LanguageGo)
		err := b.DecodeMessage(msg)
		m.Profile = &LanguageProfile_Go{msg}
		return true, err
	case 2003: // Profile.java
		if wire != proto1.WireBytes {
			return true, proto1.ErrInternalBadWireType
		}
		msg := new(LanguageJava)
		err := b.DecodeMessage(msg)
		m.Profile = &LanguageProfile_Java{msg}
		return true, err
	default:
		return false, nil
	}
}

func _LanguageProfile_OneofSizer(msg proto1.Message) (n int) {
	m := msg.(*LanguageProfile)
	// Profile
	switch x := m.Profile.(type) {
	case *LanguageProfile_Go:
		s := proto1.Size(x.Go)
		n += proto1.SizeVarint(2002<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case *LanguageProfile_Java:
		s := proto1.Size(x.Java)
		n += proto1.SizeVarint(2003<<3 | proto1.WireBytes)
		n += proto1.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type EnvironmentalProfile struct {
	Timestamp int64            `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Hardware  *HardwareProfile `protobuf:"bytes,2,opt,name=hardware" json:"hardware,omitempty"`
	Language  *LanguageProfile `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"`
	Prev      int64            `protobuf:"varint,101,opt,name=prev" json:"prev,omitempty"`
	Next      int64            `protobuf:"varint,102,opt,name=next" json:"next,omitempty"`
}

func (m *EnvironmentalProfile) Reset()                    { *m = EnvironmentalProfile{} }
func (m *EnvironmentalProfile) String() string            { return proto1.CompactTextString(m) }
func (*EnvironmentalProfile) ProtoMessage()               {}
func (*EnvironmentalProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *EnvironmentalProfile) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *EnvironmentalProfile) GetHardware() *HardwareProfile {
	if m != nil {
		return m.Hardware
	}
	return nil
}

func (m *EnvironmentalProfile) GetLanguage() *LanguageProfile {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *EnvironmentalProfile) GetPrev() int64 {
	if m != nil {
		return m.Prev
	}
	return 0
}

func (m *EnvironmentalProfile) GetNext() int64 {
	if m != nil {
		return m.Next
	}
	return 0
}

// ******************* Event Representation
type EventWhen struct {
	Time int64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
}

func (m *EventWhen) Reset()                    { *m = EventWhen{} }
func (m *EventWhen) String() string            { return proto1.CompactTextString(m) }
func (*EventWhen) ProtoMessage()               {}
func (*EventWhen) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *EventWhen) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type AttributeValue struct {
	Type   AttributeValueType `protobuf:"varint,1,opt,name=type,enum=context_bus.AttributeValueType" json:"type,omitempty"`
	Str    string             `protobuf:"bytes,2,opt,name=str" json:"str,omitempty"`
	Struct *Attributes        `protobuf:"bytes,3,opt,name=struct" json:"struct,omitempty"`
}

func (m *AttributeValue) Reset()                    { *m = AttributeValue{} }
func (m *AttributeValue) String() string            { return proto1.CompactTextString(m) }
func (*AttributeValue) ProtoMessage()               {}
func (*AttributeValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *AttributeValue) GetType() AttributeValueType {
	if m != nil {
		return m.Type
	}
	return AttributeValueType_AttributeValueType_
}

func (m *AttributeValue) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func (m *AttributeValue) GetStruct() *Attributes {
	if m != nil {
		return m.Struct
	}
	return nil
}

type Attributes struct {
	Attrs map[string]*AttributeValue `protobuf:"bytes,1,rep,name=attrs" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Attributes) Reset()                    { *m = Attributes{} }
func (m *Attributes) String() string            { return proto1.CompactTextString(m) }
func (*Attributes) ProtoMessage()               {}
func (*Attributes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *Attributes) GetAttrs() map[string]*AttributeValue {
	if m != nil {
		return m.Attrs
	}
	return nil
}

type CodeBaseInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	File string `protobuf:"bytes,2,opt,name=file" json:"file,omitempty"`
	Line int64  `protobuf:"varint,3,opt,name=line" json:"line,omitempty"`
}

func (m *CodeBaseInfo) Reset()                    { *m = CodeBaseInfo{} }
func (m *CodeBaseInfo) String() string            { return proto1.CompactTextString(m) }
func (*CodeBaseInfo) ProtoMessage()               {}
func (*CodeBaseInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *CodeBaseInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CodeBaseInfo) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *CodeBaseInfo) GetLine() int64 {
	if m != nil {
		return m.Line
	}
	return 0
}

type EventWhere struct {
	Attrs      *Attributes `protobuf:"bytes,1,opt,name=attrs" json:"attrs,omitempty"`
	Stacktrace string      `protobuf:"bytes,2,opt,name=stacktrace" json:"stacktrace,omitempty"`
}

func (m *EventWhere) Reset()                    { *m = EventWhere{} }
func (m *EventWhere) String() string            { return proto1.CompactTextString(m) }
func (*EventWhere) ProtoMessage()               {}
func (*EventWhere) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *EventWhere) GetAttrs() *Attributes {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *EventWhere) GetStacktrace() string {
	if m != nil {
		return m.Stacktrace
	}
	return ""
}

type EventRecorder struct {
	Type EventRecorderType `protobuf:"varint,1,opt,name=type,enum=context_bus.EventRecorderType" json:"type,omitempty"`
	Name string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *EventRecorder) Reset()                    { *m = EventRecorder{} }
func (m *EventRecorder) String() string            { return proto1.CompactTextString(m) }
func (*EventRecorder) ProtoMessage()               {}
func (*EventRecorder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *EventRecorder) GetType() EventRecorderType {
	if m != nil {
		return m.Type
	}
	return EventRecorderType_EventRecorderType_
}

func (m *EventRecorder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EventMessage struct {
	Attrs   *Attributes `protobuf:"bytes,1,opt,name=attrs" json:"attrs,omitempty"`
	Message string      `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Paths   []*Path     `protobuf:"bytes,3,rep,name=paths" json:"paths,omitempty"`
}

func (m *EventMessage) Reset()                    { *m = EventMessage{} }
func (m *EventMessage) String() string            { return proto1.CompactTextString(m) }
func (*EventMessage) ProtoMessage()               {}
func (*EventMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *EventMessage) GetAttrs() *Attributes {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *EventMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *EventMessage) GetPaths() []*Path {
	if m != nil {
		return m.Paths
	}
	return nil
}

type LibrariesMessage struct {
	Libraries map[string]*EventMessage `protobuf:"bytes,1,rep,name=libraries" json:"libraries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *LibrariesMessage) Reset()                    { *m = LibrariesMessage{} }
func (m *LibrariesMessage) String() string            { return proto1.CompactTextString(m) }
func (*LibrariesMessage) ProtoMessage()               {}
func (*LibrariesMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *LibrariesMessage) GetLibraries() map[string]*EventMessage {
	if m != nil {
		return m.Libraries
	}
	return nil
}

type EventWhat struct {
	Application *EventMessage     `protobuf:"bytes,1,opt,name=application" json:"application,omitempty"`
	Libraries   *LibrariesMessage `protobuf:"bytes,2,opt,name=libraries" json:"libraries,omitempty"`
}

func (m *EventWhat) Reset()                    { *m = EventWhat{} }
func (m *EventWhat) String() string            { return proto1.CompactTextString(m) }
func (*EventWhat) ProtoMessage()               {}
func (*EventWhat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *EventWhat) GetApplication() *EventMessage {
	if m != nil {
		return m.Application
	}
	return nil
}

func (m *EventWhat) GetLibraries() *LibrariesMessage {
	if m != nil {
		return m.Libraries
	}
	return nil
}

type EventRepresentation struct {
	When     *EventWhen     `protobuf:"bytes,1,opt,name=when" json:"when,omitempty"`
	Where    *EventWhere    `protobuf:"bytes,2,opt,name=where" json:"where,omitempty"`
	Recorder *EventRecorder `protobuf:"bytes,3,opt,name=recorder" json:"recorder,omitempty"`
	What     *EventWhat     `protobuf:"bytes,4,opt,name=what" json:"what,omitempty"`
}

func (m *EventRepresentation) Reset()                    { *m = EventRepresentation{} }
func (m *EventRepresentation) String() string            { return proto1.CompactTextString(m) }
func (*EventRepresentation) ProtoMessage()               {}
func (*EventRepresentation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *EventRepresentation) GetWhen() *EventWhen {
	if m != nil {
		return m.When
	}
	return nil
}

func (m *EventRepresentation) GetWhere() *EventWhere {
	if m != nil {
		return m.Where
	}
	return nil
}

func (m *EventRepresentation) GetRecorder() *EventRecorder {
	if m != nil {
		return m.Recorder
	}
	return nil
}

func (m *EventRepresentation) GetWhat() *EventWhat {
	if m != nil {
		return m.What
	}
	return nil
}

// ******************* Event Metadata
type ParentChildPointers struct {
	Parent   uint64   `protobuf:"varint,1,opt,name=parent" json:"parent,omitempty"`
	Children []uint64 `protobuf:"varint,2,rep,packed,name=children" json:"children,omitempty"`
}

func (m *ParentChildPointers) Reset()                    { *m = ParentChildPointers{} }
func (m *ParentChildPointers) String() string            { return proto1.CompactTextString(m) }
func (*ParentChildPointers) ProtoMessage()               {}
func (*ParentChildPointers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *ParentChildPointers) GetParent() uint64 {
	if m != nil {
		return m.Parent
	}
	return 0
}

func (m *ParentChildPointers) GetChildren() []uint64 {
	if m != nil {
		return m.Children
	}
	return nil
}

type EventMetadata struct {
	Id  uint64               `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Pcp *ParentChildPointers `protobuf:"bytes,2,opt,name=pcp" json:"pcp,omitempty"`
	Esp int64                `protobuf:"varint,3,opt,name=esp" json:"esp,omitempty"`
}

func (m *EventMetadata) Reset()                    { *m = EventMetadata{} }
func (m *EventMetadata) String() string            { return proto1.CompactTextString(m) }
func (*EventMetadata) ProtoMessage()               {}
func (*EventMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *EventMetadata) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EventMetadata) GetPcp() *ParentChildPointers {
	if m != nil {
		return m.Pcp
	}
	return nil
}

func (m *EventMetadata) GetEsp() int64 {
	if m != nil {
		return m.Esp
	}
	return 0
}

// ******************* Event Data
type EventData struct {
	Event         *EventRepresentation `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	Metadata      *EventMetadata       `protobuf:"bytes,2,opt,name=metadata" json:"metadata,omitempty"`
	PrevEventData *EventData           `protobuf:"bytes,3,opt,name=prevEventData" json:"prevEventData,omitempty"`
}

func (m *EventData) Reset()                    { *m = EventData{} }
func (m *EventData) String() string            { return proto1.CompactTextString(m) }
func (*EventData) ProtoMessage()               {}
func (*EventData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *EventData) GetEvent() *EventRepresentation {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *EventData) GetMetadata() *EventMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *EventData) GetPrevEventData() *EventData {
	if m != nil {
		return m.PrevEventData
	}
	return nil
}

// Trace span, deprecated
type Record struct {
	Type        ActionType `protobuf:"varint,1,opt,name=type,enum=context_bus.ActionType" json:"type,omitempty"`
	Timestamp   int64      `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	MessageName string     `protobuf:"bytes,3,opt,name=message_name,json=messageName" json:"message_name,omitempty"`
	Uuid        string     `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
	Service     string     `protobuf:"bytes,5,opt,name=service" json:"service,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto1.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *Record) GetType() ActionType {
	if m != nil {
		return m.Type
	}
	return ActionType_ActionType_
}

func (m *Record) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Record) GetMessageName() string {
	if m != nil {
		return m.MessageName
	}
	return ""
}

func (m *Record) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Record) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

// ******************* Prometheus *******************
type PrometheusOpts struct {
	Id          int64             `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Namespace   string            `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	Subsystem   string            `protobuf:"bytes,3,opt,name=subsystem" json:"subsystem,omitempty"`
	Name        string            `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Help        string            `protobuf:"bytes,5,opt,name=help" json:"help,omitempty"`
	ConstLabels map[string]string `protobuf:"bytes,6,rep,name=const_labels,json=constLabels" json:"const_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LabelNames  []string          `protobuf:"bytes,7,rep,name=label_names,json=labelNames" json:"label_names,omitempty"`
}

func (m *PrometheusOpts) Reset()                    { *m = PrometheusOpts{} }
func (m *PrometheusOpts) String() string            { return proto1.CompactTextString(m) }
func (*PrometheusOpts) ProtoMessage()               {}
func (*PrometheusOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *PrometheusOpts) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PrometheusOpts) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PrometheusOpts) GetSubsystem() string {
	if m != nil {
		return m.Subsystem
	}
	return ""
}

func (m *PrometheusOpts) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PrometheusOpts) GetHelp() string {
	if m != nil {
		return m.Help
	}
	return ""
}

func (m *PrometheusOpts) GetConstLabels() map[string]string {
	if m != nil {
		return m.ConstLabels
	}
	return nil
}

func (m *PrometheusOpts) GetLabelNames() []string {
	if m != nil {
		return m.LabelNames
	}
	return nil
}

type PrometheusHistogramOpts struct {
	Id          int64             `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Namespace   string            `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	Subsystem   string            `protobuf:"bytes,3,opt,name=subsystem" json:"subsystem,omitempty"`
	Name        string            `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Help        string            `protobuf:"bytes,5,opt,name=help" json:"help,omitempty"`
	ConstLabels map[string]string `protobuf:"bytes,6,rep,name=const_labels,json=constLabels" json:"const_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Buckets     []float64         `protobuf:"fixed64,7,rep,packed,name=buckets" json:"buckets,omitempty"`
	LabelNames  []string          `protobuf:"bytes,8,rep,name=label_names,json=labelNames" json:"label_names,omitempty"`
}

func (m *PrometheusHistogramOpts) Reset()                    { *m = PrometheusHistogramOpts{} }
func (m *PrometheusHistogramOpts) String() string            { return proto1.CompactTextString(m) }
func (*PrometheusHistogramOpts) ProtoMessage()               {}
func (*PrometheusHistogramOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *PrometheusHistogramOpts) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PrometheusHistogramOpts) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PrometheusHistogramOpts) GetSubsystem() string {
	if m != nil {
		return m.Subsystem
	}
	return ""
}

func (m *PrometheusHistogramOpts) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PrometheusHistogramOpts) GetHelp() string {
	if m != nil {
		return m.Help
	}
	return ""
}

func (m *PrometheusHistogramOpts) GetConstLabels() map[string]string {
	if m != nil {
		return m.ConstLabels
	}
	return nil
}

func (m *PrometheusHistogramOpts) GetBuckets() []float64 {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *PrometheusHistogramOpts) GetLabelNames() []string {
	if m != nil {
		return m.LabelNames
	}
	return nil
}

type PrometheusSummaryObjective struct {
	Id    int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Key   float64 `protobuf:"fixed64,2,opt,name=key" json:"key,omitempty"`
	Value float64 `protobuf:"fixed64,3,opt,name=value" json:"value,omitempty"`
}

func (m *PrometheusSummaryObjective) Reset()                    { *m = PrometheusSummaryObjective{} }
func (m *PrometheusSummaryObjective) String() string            { return proto1.CompactTextString(m) }
func (*PrometheusSummaryObjective) ProtoMessage()               {}
func (*PrometheusSummaryObjective) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *PrometheusSummaryObjective) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PrometheusSummaryObjective) GetKey() float64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *PrometheusSummaryObjective) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PrometheusSummaryOpts struct {
	Id          int64                         `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Namespace   string                        `protobuf:"bytes,2,opt,name=namespace" json:"namespace,omitempty"`
	Subsystem   string                        `protobuf:"bytes,3,opt,name=subsystem" json:"subsystem,omitempty"`
	Name        string                        `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Help        string                        `protobuf:"bytes,5,opt,name=help" json:"help,omitempty"`
	ConstLabels map[string]string             `protobuf:"bytes,6,rep,name=const_labels,json=constLabels" json:"const_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Objectives  []*PrometheusSummaryObjective `protobuf:"bytes,7,rep,name=objectives" json:"objectives,omitempty"`
	MaxAge      int64                         `protobuf:"varint,8,opt,name=max_age,json=maxAge" json:"max_age,omitempty"`
	AgeBuckets  uint32                        `protobuf:"varint,9,opt,name=age_buckets,json=ageBuckets" json:"age_buckets,omitempty"`
	BufCap      uint32                        `protobuf:"varint,10,opt,name=buf_cap,json=bufCap" json:"buf_cap,omitempty"`
	LabelNames  []string                      `protobuf:"bytes,11,rep,name=label_names,json=labelNames" json:"label_names,omitempty"`
}

func (m *PrometheusSummaryOpts) Reset()                    { *m = PrometheusSummaryOpts{} }
func (m *PrometheusSummaryOpts) String() string            { return proto1.CompactTextString(m) }
func (*PrometheusSummaryOpts) ProtoMessage()               {}
func (*PrometheusSummaryOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

func (m *PrometheusSummaryOpts) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PrometheusSummaryOpts) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *PrometheusSummaryOpts) GetSubsystem() string {
	if m != nil {
		return m.Subsystem
	}
	return ""
}

func (m *PrometheusSummaryOpts) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PrometheusSummaryOpts) GetHelp() string {
	if m != nil {
		return m.Help
	}
	return ""
}

func (m *PrometheusSummaryOpts) GetConstLabels() map[string]string {
	if m != nil {
		return m.ConstLabels
	}
	return nil
}

func (m *PrometheusSummaryOpts) GetObjectives() []*PrometheusSummaryObjective {
	if m != nil {
		return m.Objectives
	}
	return nil
}

func (m *PrometheusSummaryOpts) GetMaxAge() int64 {
	if m != nil {
		return m.MaxAge
	}
	return 0
}

func (m *PrometheusSummaryOpts) GetAgeBuckets() uint32 {
	if m != nil {
		return m.AgeBuckets
	}
	return 0
}

func (m *PrometheusSummaryOpts) GetBufCap() uint32 {
	if m != nil {
		return m.BufCap
	}
	return 0
}

func (m *PrometheusSummaryOpts) GetLabelNames() []string {
	if m != nil {
		return m.LabelNames
	}
	return nil
}

type PrometheusConfiguration struct {
	Counters   []*PrometheusOpts          `protobuf:"bytes,1,rep,name=counters" json:"counters,omitempty"`
	Gauges     []*PrometheusOpts          `protobuf:"bytes,2,rep,name=gauges" json:"gauges,omitempty"`
	Histograms []*PrometheusHistogramOpts `protobuf:"bytes,3,rep,name=histograms" json:"histograms,omitempty"`
	Summaries  []*PrometheusSummaryOpts   `protobuf:"bytes,4,rep,name=summaries" json:"summaries,omitempty"`
}

func (m *PrometheusConfiguration) Reset()                    { *m = PrometheusConfiguration{} }
func (m *PrometheusConfiguration) String() string            { return proto1.CompactTextString(m) }
func (*PrometheusConfiguration) ProtoMessage()               {}
func (*PrometheusConfiguration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

func (m *PrometheusConfiguration) GetCounters() []*PrometheusOpts {
	if m != nil {
		return m.Counters
	}
	return nil
}

func (m *PrometheusConfiguration) GetGauges() []*PrometheusOpts {
	if m != nil {
		return m.Gauges
	}
	return nil
}

func (m *PrometheusConfiguration) GetHistograms() []*PrometheusHistogramOpts {
	if m != nil {
		return m.Histograms
	}
	return nil
}

func (m *PrometheusConfiguration) GetSummaries() []*PrometheusSummaryOpts {
	if m != nil {
		return m.Summaries
	}
	return nil
}

// ******************* Integration *******************
type Payload struct {
	// workflow-level
	RequestId int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	ConfigId  int64                  `protobuf:"varint,2,opt,name=config_id,json=configId" json:"config_id,omitempty"`
	Snapshots *PrerequisiteSnapshots `protobuf:"bytes,3,opt,name=snapshots" json:"snapshots,omitempty"`
	Addition  *PrerequisiteSnapshots `protobuf:"bytes,4,opt,name=addition" json:"addition,omitempty"`
	// message-level
	MType MessageType `protobuf:"varint,11,opt,name=m_type,json=mType,enum=context_bus.MessageType" json:"m_type,omitempty"`
	Uuid  string      `protobuf:"bytes,12,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto1.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

func (m *Payload) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Payload) GetConfigId() int64 {
	if m != nil {
		return m.ConfigId
	}
	return 0
}

func (m *Payload) GetSnapshots() *PrerequisiteSnapshots {
	if m != nil {
		return m.Snapshots
	}
	return nil
}

func (m *Payload) GetAddition() *PrerequisiteSnapshots {
	if m != nil {
		return m.Addition
	}
	return nil
}

func (m *Payload) GetMType() MessageType {
	if m != nil {
		return m.MType
	}
	return MessageType_MessageType_
}

func (m *Payload) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto1.RegisterType((*ConditionMessage)(nil), "context_bus.ConditionMessage")
	proto1.RegisterType((*ConditionLogic)(nil), "context_bus.ConditionLogic")
	proto1.RegisterType((*ConditionNode)(nil), "context_bus.ConditionNode")
	proto1.RegisterType((*ConditionTree)(nil), "context_bus.ConditionTree")
	proto1.RegisterType((*PrerequisiteMessage)(nil), "context_bus.PrerequisiteMessage")
	proto1.RegisterType((*PrerequisiteLogic)(nil), "context_bus.PrerequisiteLogic")
	proto1.RegisterType((*PrerequisiteNode)(nil), "context_bus.PrerequisiteNode")
	proto1.RegisterType((*PrerequisiteTree)(nil), "context_bus.PrerequisiteTree")
	proto1.RegisterType((*PrerequisiteSnapshot)(nil), "context_bus.PrerequisiteSnapshot")
	proto1.RegisterType((*PrerequisiteSnapshots)(nil), "context_bus.PrerequisiteSnapshots")
	proto1.RegisterType((*FaultDelayParam)(nil), "context_bus.FaultDelayParam")
	proto1.RegisterType((*TrafficBalanceParam)(nil), "context_bus.TrafficBalanceParam")
	proto1.RegisterType((*TrafficRoutingParam)(nil), "context_bus.TrafficRoutingParam")
	proto1.RegisterType((*ReactionConfigure)(nil), "context_bus.ReactionConfigure")
	proto1.RegisterType((*Path)(nil), "context_bus.Path")
	proto1.RegisterType((*AttributeConfigure)(nil), "context_bus.AttributeConfigure")
	proto1.RegisterType((*TimestampConfigure)(nil), "context_bus.TimestampConfigure")
	proto1.RegisterType((*StackTraceConfigure)(nil), "context_bus.StackTraceConfigure")
	proto1.RegisterType((*LoggingConfigure)(nil), "context_bus.LoggingConfigure")
	proto1.RegisterType((*TracingConfigure)(nil), "context_bus.TracingConfigure")
	proto1.RegisterType((*MetricsConfigure)(nil), "context_bus.MetricsConfigure")
	proto1.RegisterType((*ObservationConfigure)(nil), "context_bus.ObservationConfigure")
	proto1.RegisterType((*Configure)(nil), "context_bus.Configure")
	proto1.RegisterType((*CPUProfile)(nil), "context_bus.CPUProfile")
	proto1.RegisterType((*MemProfile)(nil), "context_bus.MemProfile")
	proto1.RegisterType((*NetProfile)(nil), "context_bus.NetProfile")
	proto1.RegisterType((*HardwareProfile)(nil), "context_bus.HardwareProfile")
	proto1.RegisterType((*LanguageGo)(nil), "context_bus.LanguageGo")
	proto1.RegisterType((*LanguageJava)(nil), "context_bus.LanguageJava")
	proto1.RegisterType((*LanguageProfile)(nil), "context_bus.LanguageProfile")
	proto1.RegisterType((*EnvironmentalProfile)(nil), "context_bus.EnvironmentalProfile")
	proto1.RegisterType((*EventWhen)(nil), "context_bus.EventWhen")
	proto1.RegisterType((*AttributeValue)(nil), "context_bus.AttributeValue")
	proto1.RegisterType((*Attributes)(nil), "context_bus.Attributes")
	proto1.RegisterType((*CodeBaseInfo)(nil), "context_bus.CodeBaseInfo")
	proto1.RegisterType((*EventWhere)(nil), "context_bus.EventWhere")
	proto1.RegisterType((*EventRecorder)(nil), "context_bus.EventRecorder")
	proto1.RegisterType((*EventMessage)(nil), "context_bus.EventMessage")
	proto1.RegisterType((*LibrariesMessage)(nil), "context_bus.LibrariesMessage")
	proto1.RegisterType((*EventWhat)(nil), "context_bus.EventWhat")
	proto1.RegisterType((*EventRepresentation)(nil), "context_bus.EventRepresentation")
	proto1.RegisterType((*ParentChildPointers)(nil), "context_bus.ParentChildPointers")
	proto1.RegisterType((*EventMetadata)(nil), "context_bus.EventMetadata")
	proto1.RegisterType((*EventData)(nil), "context_bus.EventData")
	proto1.RegisterType((*Record)(nil), "context_bus.Record")
	proto1.RegisterType((*PrometheusOpts)(nil), "context_bus.PrometheusOpts")
	proto1.RegisterType((*PrometheusHistogramOpts)(nil), "context_bus.PrometheusHistogramOpts")
	proto1.RegisterType((*PrometheusSummaryObjective)(nil), "context_bus.PrometheusSummaryObjective")
	proto1.RegisterType((*PrometheusSummaryOpts)(nil), "context_bus.PrometheusSummaryOpts")
	proto1.RegisterType((*PrometheusConfiguration)(nil), "context_bus.PrometheusConfiguration")
	proto1.RegisterType((*Payload)(nil), "context_bus.Payload")
	proto1.RegisterEnum("context_bus.ConditionOperator", ConditionOperator_name, ConditionOperator_value)
	proto1.RegisterEnum("context_bus.ConditionType", ConditionType_name, ConditionType_value)
	proto1.RegisterEnum("context_bus.ConditionNodeType", ConditionNodeType_name, ConditionNodeType_value)
	proto1.RegisterEnum("context_bus.LogicType", LogicType_name, LogicType_value)
	proto1.RegisterEnum("context_bus.PrerequisiteNodeType", PrerequisiteNodeType_name, PrerequisiteNodeType_value)
	proto1.RegisterEnum("context_bus.ReactionType", ReactionType_name, ReactionType_value)
	proto1.RegisterEnum("context_bus.PathType", PathType_name, PathType_value)
	proto1.RegisterEnum("context_bus.LogOutType", LogOutType_name, LogOutType_value)
	proto1.RegisterEnum("context_bus.MetricType", MetricType_name, MetricType_value)
	proto1.RegisterEnum("context_bus.ObservationType", ObservationType_name, ObservationType_value)
	proto1.RegisterEnum("context_bus.LanguageType", LanguageType_name, LanguageType_value)
	proto1.RegisterEnum("context_bus.AttributeValueType", AttributeValueType_name, AttributeValueType_value)
	proto1.RegisterEnum("context_bus.EventRecorderType", EventRecorderType_name, EventRecorderType_value)
	proto1.RegisterEnum("context_bus.MessageType", MessageType_name, MessageType_value)
	proto1.RegisterEnum("context_bus.ActionType", ActionType_name, ActionType_value)
}

func init() { proto1.RegisterFile("context_bus.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 3134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x3a, 0xcf, 0x6f, 0x1b, 0xc7,
	0xd5, 0x5e, 0x92, 0x92, 0xc8, 0x47, 0x59, 0x5a, 0x8d, 0x65, 0x8b, 0x96, 0x7f, 0x2f, 0x92, 0x2f,
	0x8e, 0xbe, 0xd4, 0x4e, 0xe4, 0x38, 0x36, 0x92, 0x36, 0xb1, 0x2d, 0xcb, 0x92, 0x5c, 0xd9, 0x52,
	0x56, 0x4a, 0x5c, 0x34, 0x01, 0x84, 0xd1, 0x72, 0x44, 0x6e, 0x4c, 0xee, 0x6e, 0x66, 0x87, 0x8c,
	0x95, 0x43, 0xd1, 0x43, 0x0b, 0x04, 0x45, 0x81, 0x02, 0xbd, 0xf7, 0xd6, 0x4b, 0x4f, 0x3d, 0x35,
	0x45, 0x6f, 0xbd, 0x16, 0xbd, 0x14, 0x6d, 0xff, 0x80, 0xb4, 0xe7, 0x1e, 0x0a, 0x14, 0xbd, 0x17,
	0x6f, 0x66, 0x76, 0x77, 0x86, 0x5c, 0xc9, 0x49, 0x91, 0x22, 0x27, 0xce, 0x7b, 0xfb, 0xde, 0x9b,
	0x37, 0xef, 0xbd, 0x79, 0xef, 0xcd, 0x0c, 0x61, 0x2e, 0x88, 0x23, 0xc1, 0x9e, 0x89, 0xbd, 0xfd,
	0x41, 0x7a, 0x2d, 0xe1, 0xb1, 0x88, 0x49, 0xd3, 0x40, 0x79, 0x9f, 0x39, 0xe0, 0xae, 0xc4, 0x51,
	0x3b, 0x14, 0x61, 0x1c, 0x3d, 0x62, 0x69, 0x4a, 0x3b, 0x8c, 0x5c, 0x83, 0x9a, 0x38, 0x4c, 0x58,
	0xcb, 0xb9, 0xec, 0x5c, 0x9d, 0x59, 0x5e, 0xbc, 0x66, 0xca, 0xc8, 0x89, 0x77, 0x0f, 0x13, 0xe6,
	0x4b, 0x3a, 0x72, 0x0d, 0x2a, 0x71, 0xd2, 0xaa, 0x48, 0xea, 0x8b, 0xe5, 0xd4, 0x5b, 0x09, 0xe3,
	0x54, 0xc4, 0xdc, 0xaf, 0xc4, 0x09, 0x99, 0x87, 0x89, 0x21, 0xed, 0x0d, 0x58, 0xab, 0x7a, 0xd9,
	0xb9, 0x5a, 0xf5, 0x15, 0xe0, 0x75, 0x61, 0x26, 0x27, 0xdf, 0x8c, 0x3b, 0x61, 0x40, 0x96, 0x2c,
	0x3d, 0xce, 0x58, 0x92, 0x25, 0x85, 0xa1, 0xc3, 0x19, 0x98, 0x4c, 0x28, 0x67, 0x91, 0x68, 0xb5,
	0xa5, 0x50, 0x0d, 0x11, 0x02, 0xb5, 0x5e, 0x98, 0x8a, 0x16, 0xbb, 0x5c, 0xbd, 0x5a, 0xf5, 0xe5,
	0xd8, 0xfb, 0xb5, 0x03, 0x27, 0xf3, 0xa9, 0x1e, 0xc7, 0x6d, 0x46, 0x96, 0xf5, 0x4c, 0xc7, 0xae,
	0x01, 0x29, 0x8d, 0x19, 0x6f, 0xc1, 0x54, 0x5f, 0x19, 0x4c, 0xae, 0xa3, 0xb9, 0x7c, 0xa1, 0x9c,
	0x4d, 0x5b, 0xd5, 0xcf, 0xa8, 0xc9, 0x6b, 0x30, 0xd1, 0x43, 0xed, 0x5b, 0x35, 0xc9, 0x76, 0xae,
	0x9c, 0x4d, 0x2e, 0xd0, 0x57, 0x94, 0xde, 0x07, 0x86, 0xc2, 0xbb, 0x9c, 0x31, 0xf2, 0x2a, 0x4c,
	0x44, 0x71, 0x9b, 0xa5, 0x2d, 0xe7, 0x72, 0xf5, 0x6a, 0xf3, 0x28, 0x1f, 0xa1, 0xc6, 0xbe, 0x22,
	0x24, 0x2d, 0x98, 0xea, 0x31, 0x7a, 0xb0, 0x71, 0x3f, 0x6d, 0x55, 0xa4, 0x2d, 0x32, 0xd0, 0xfb,
	0x14, 0x4e, 0x6d, 0x73, 0xc6, 0xd9, 0xc7, 0x83, 0x30, 0x0d, 0x05, 0xcb, 0xa2, 0x80, 0x40, 0x2d,
	0xa2, 0x7d, 0x65, 0xfd, 0x86, 0x2f, 0xc7, 0xe4, 0x16, 0x34, 0x82, 0x38, 0x6a, 0xef, 0x09, 0xce,
	0x94, 0xb1, 0x8e, 0x9c, 0x1a, 0xb5, 0xf4, 0xeb, 0x48, 0x2c, 0xf5, 0x3d, 0xc2, 0x3d, 0xde, 0x53,
	0x98, 0x33, 0xe7, 0xfe, 0xdf, 0xfa, 0xfd, 0x8f, 0x0e, 0xb8, 0xe6, 0x6c, 0xd2, 0xf5, 0x33, 0x50,
	0x09, 0xdb, 0x72, 0xaa, 0xaa, 0x5f, 0x09, 0xdb, 0xe4, 0xa6, 0x15, 0x0a, 0x57, 0xac, 0xc9, 0x47,
	0x99, 0x0d, 0x3d, 0xde, 0x1c, 0x8d, 0x86, 0xcb, 0x47, 0x72, 0x8e, 0x05, 0xc4, 0xeb, 0x76, 0x40,
	0x5c, 0x3c, 0x92, 0xd3, 0x8a, 0x09, 0x6a, 0x2f, 0x46, 0x9a, 0xf9, 0x86, 0x1d, 0x16, 0x17, 0x8e,
	0xd5, 0xfe, 0xf9, 0x91, 0xf1, 0x36, 0xcc, 0x9b, 0x4c, 0x3b, 0x11, 0x4d, 0xd2, 0x6e, 0x2c, 0x8a,
	0x0d, 0xec, 0x48, 0x7a, 0x05, 0x10, 0x17, 0xaa, 0x34, 0x08, 0xa4, 0xe1, 0xea, 0x3e, 0x0e, 0xbd,
	0x3f, 0x38, 0x70, 0xba, 0x4c, 0x40, 0x4a, 0xb6, 0xa0, 0x91, 0x66, 0x80, 0x56, 0xf6, 0xb5, 0x23,
	0x95, 0xcd, 0xd9, 0xae, 0xe5, 0xa3, 0xd5, 0x48, 0xf0, 0x43, 0xbf, 0x90, 0xb1, 0xb8, 0x07, 0x33,
	0xf6, 0x47, 0x54, 0xe7, 0x29, 0x3b, 0xd4, 0xe1, 0x8b, 0x43, 0x72, 0x2b, 0x53, 0x5b, 0x45, 0xee,
	0x95, 0xe7, 0x4e, 0xa8, 0x57, 0xf6, 0x66, 0xe5, 0xb6, 0xe3, 0x5d, 0x81, 0xd9, 0x07, 0x74, 0xd0,
	0x13, 0xf7, 0x59, 0x8f, 0x1e, 0x6e, 0x53, 0x4e, 0xfb, 0x18, 0x3a, 0xfd, 0x34, 0x0b, 0x9d, 0x7e,
	0xea, 0x9d, 0x86, 0x53, 0xbb, 0x9c, 0x1e, 0x1c, 0x84, 0xc1, 0x3d, 0xda, 0xa3, 0x51, 0xc0, 0x24,
	0x99, 0x81, 0xf6, 0xe3, 0x81, 0x08, 0xa3, 0x8e, 0x42, 0xff, 0xad, 0x02, 0x73, 0x3e, 0xa3, 0x01,
	0xee, 0x96, 0x95, 0x38, 0x3a, 0x08, 0x3b, 0x03, 0xce, 0xc8, 0xb7, 0xac, 0xd8, 0x3f, 0x6b, 0xa9,
	0x98, 0x51, 0x1b, 0x61, 0xf7, 0x0e, 0x40, 0xa1, 0x55, 0xeb, 0xcf, 0xb3, 0x72, 0x61, 0xe7, 0x2d,
	0xae, 0x11, 0xad, 0xd7, 0x4f, 0xf8, 0x06, 0x0b, 0xf9, 0x2e, 0xcc, 0xd8, 0x3a, 0xb7, 0x7e, 0xe3,
	0x96, 0xc4, 0x6f, 0xc9, 0xba, 0xd6, 0x4f, 0xf8, 0x23, 0xac, 0x86, 0x30, 0xbd, 0xd2, 0xd6, 0xe7,
	0xc7, 0x08, 0x33, 0xad, 0x61, 0x08, 0xd3, 0x68, 0x72, 0x1b, 0xea, 0x09, 0x67, 0x2a, 0xd5, 0x94,
	0x25, 0xd8, 0xd1, 0xe0, 0xf7, 0xa7, 0x12, 0x2e, 0x07, 0xf7, 0xea, 0x32, 0x27, 0xd0, 0x7e, 0xea,
	0xad, 0x42, 0x6d, 0x9b, 0x8a, 0x2e, 0x79, 0xd9, 0xb2, 0xea, 0x69, 0x5b, 0x0e, 0x15, 0x5d, 0xc3,
	0xa2, 0x04, 0x6a, 0x09, 0x15, 0x5d, 0xb9, 0x15, 0x1a, 0xbe, 0x1c, 0x7b, 0x5b, 0x40, 0xee, 0x0a,
	0xc1, 0xc3, 0xfd, 0x81, 0x60, 0x85, 0xab, 0xca, 0x12, 0xe4, 0x8b, 0x39, 0x37, 0x2a, 0x3c, 0x37,
	0x36, 0x91, 0x16, 0xf8, 0x0a, 0x90, 0xdd, 0xb0, 0xcf, 0x52, 0x41, 0xfb, 0x49, 0x21, 0xf0, 0x0c,
	0x4c, 0x1e, 0xc4, 0xbc, 0x4f, 0x85, 0x16, 0xa9, 0x21, 0x0c, 0xa0, 0x1d, 0x41, 0x83, 0xa7, 0xbb,
	0x9c, 0x06, 0xc5, 0xfc, 0xde, 0xbf, 0x1d, 0x70, 0x37, 0xe3, 0x4e, 0x27, 0x8c, 0x3a, 0x85, 0x8c,
	0xef, 0x40, 0x43, 0x64, 0x92, 0xa5, 0x98, 0xe6, 0xf2, 0x25, 0xdb, 0xf8, 0x63, 0xf3, 0xfa, 0x05,
	0x07, 0xb9, 0x03, 0x90, 0xe2, 0x54, 0x02, 0xa7, 0xd2, 0xab, 0xb0, 0x9d, 0x57, 0xa2, 0x89, 0x6f,
	0xf0, 0x90, 0x9b, 0x30, 0x41, 0x85, 0xe0, 0x69, 0xab, 0x2a, 0x77, 0xb5, 0x3d, 0xf9, 0xb8, 0x15,
	0x7d, 0x45, 0x4d, 0x5e, 0x86, 0x6a, 0x3c, 0x10, 0x32, 0x03, 0xce, 0x2c, 0x2f, 0x8c, 0xa6, 0xfc,
	0xad, 0x81, 0x90, 0x2e, 0x42, 0x1a, 0xef, 0x53, 0x70, 0x71, 0x7e, 0x6b, 0xd9, 0x65, 0xbe, 0x38,
	0x07, 0x8d, 0x84, 0xb3, 0xe1, 0x9e, 0xfc, 0x50, 0x91, 0x1f, 0x30, 0xa2, 0x86, 0x8f, 0xf1, 0xe3,
	0x7f, 0xa7, 0xa6, 0xf7, 0x7b, 0x07, 0xdc, 0x47, 0x4c, 0xf0, 0x30, 0x48, 0x8b, 0xc9, 0xff, 0xdf,
	0x8a, 0x2e, 0x5b, 0x79, 0x45, 0x6c, 0xc4, 0xd7, 0x02, 0x4c, 0xc5, 0x89, 0x48, 0xf7, 0xc2, 0xb6,
	0xd4, 0xa9, 0xea, 0x4f, 0x22, 0xb8, 0xd1, 0xce, 0x97, 0x50, 0x3d, 0x6a, 0x09, 0xb5, 0xa3, 0x96,
	0x30, 0xf1, 0x95, 0x96, 0xf0, 0x2f, 0x07, 0xe6, 0xb7, 0xf6, 0x53, 0xc6, 0x87, 0xd4, 0x4e, 0x3d,
	0xaf, 0x5a, 0xcb, 0xb0, 0x93, 0x88, 0xc1, 0x60, 0xb7, 0x40, 0x3d, 0x15, 0x80, 0x3a, 0x54, 0x2e,
	0x8c, 0x3a, 0xce, 0x0a, 0x4e, 0x3f, 0xa3, 0x46, 0x46, 0xa1, 0x5c, 0x58, 0xba, 0xb5, 0x47, 0xdd,
	0xeb, 0x67, 0xd4, 0xaa, 0xe9, 0x92, 0xe6, 0x6f, 0xd5, 0x4a, 0x4a, 0xdc, 0xa8, 0x6b, 0xfc, 0x8c,
	0xda, 0xfb, 0xa2, 0x02, 0x8d, 0x62, 0xa9, 0x2b, 0xd0, 0xe0, 0x3a, 0x99, 0x66, 0xe5, 0xe7, 0xc5,
	0xd1, 0x3e, 0x46, 0x91, 0xe6, 0x49, 0x37, 0x2b, 0x39, 0x39, 0x1f, 0xd9, 0x84, 0xe9, 0xb8, 0x30,
	0x8b, 0x2a, 0x9e, 0xcd, 0xe5, 0xab, 0x47, 0xc8, 0x31, 0x2c, 0xa8, 0x45, 0x59, 0xdc, 0x8b, 0x1f,
	0xc2, 0x8c, 0x3d, 0x55, 0x49, 0x01, 0x7b, 0xdd, 0x2e, 0x60, 0x17, 0x4b, 0xab, 0x83, 0xe1, 0xf0,
	0xbc, 0x7a, 0x2d, 0xee, 0xc3, 0xdc, 0x98, 0x02, 0x5f, 0xb5, 0x42, 0x96, 0x05, 0x8d, 0x59, 0x21,
	0xff, 0x0f, 0x60, 0x65, 0xfb, 0xbd, 0x6d, 0x1e, 0x1f, 0x84, 0x3d, 0x86, 0x5d, 0x45, 0xc2, 0x78,
	0x80, 0x9d, 0x19, 0x4e, 0xe0, 0xf8, 0x19, 0xe8, 0xfd, 0xc4, 0x01, 0x78, 0xc4, 0xfa, 0x19, 0xe1,
	0x3c, 0x4c, 0x88, 0x58, 0xd0, 0x9e, 0x24, 0xab, 0xf9, 0x0a, 0x20, 0xe7, 0xa1, 0x41, 0x87, 0x34,
	0xec, 0xd1, 0xfd, 0x9e, 0xd2, 0xa6, 0xe6, 0x17, 0x08, 0xdc, 0x2b, 0x83, 0x94, 0xb5, 0x65, 0xf0,
	0xd4, 0x7c, 0x39, 0x26, 0x97, 0xa1, 0x89, 0xbf, 0xdb, 0x7a, 0xd2, 0x9a, 0x9c, 0xd4, 0x44, 0x21,
	0xd7, 0x01, 0x56, 0x93, 0x09, 0xc5, 0x85, 0x63, 0xef, 0x1f, 0x0e, 0xc0, 0x63, 0x26, 0x32, 0x65,
	0xce, 0x43, 0x63, 0xff, 0x50, 0xb0, 0x74, 0x27, 0xd3, 0xbb, 0xe6, 0x17, 0x88, 0xfc, 0xab, 0xcf,
	0x82, 0x61, 0xa6, 0x54, 0x8e, 0x40, 0x05, 0x12, 0x1a, 0x3c, 0x65, 0x42, 0x71, 0x2b, 0xdd, 0x4c,
	0x94, 0x41, 0x21, 0x25, 0xd4, 0x2c, 0x0a, 0x29, 0x63, 0x1e, 0x26, 0x18, 0xe7, 0x61, 0xa4, 0x75,
	0x54, 0x00, 0x16, 0x06, 0xc6, 0x39, 0xe6, 0xc7, 0x49, 0x89, 0xd6, 0x10, 0xe2, 0xdb, 0x3c, 0x4e,
	0xc2, 0xa8, 0x35, 0xa5, 0xf0, 0x0a, 0x42, 0xdb, 0xe3, 0x08, 0x19, 0xea, 0xf2, 0x43, 0x06, 0x7a,
	0x3f, 0x77, 0x60, 0x76, 0x9d, 0xf2, 0xf6, 0x27, 0x94, 0xb3, 0x6c, 0xcd, 0x2f, 0x43, 0x35, 0x48,
	0x06, 0xba, 0x58, 0xd8, 0xd9, 0xab, 0xf0, 0xa7, 0x8f, 0x34, 0x48, 0xda, 0x67, 0x7d, 0x1d, 0x1d,
	0xa3, 0x89, 0xae, 0x9f, 0x93, 0xf6, 0x59, 0x1f, 0x49, 0x23, 0x26, 0xf4, 0xf6, 0xb6, 0x49, 0x0b,
	0x7b, 0xfb, 0x48, 0xe3, 0xfd, 0xb3, 0x02, 0xb0, 0x49, 0xa3, 0xce, 0x80, 0x76, 0xd8, 0x5a, 0x8c,
	0xda, 0xaf, 0x33, 0x9a, 0xec, 0x1c, 0xa6, 0xda, 0x03, 0x19, 0x88, 0xf6, 0xc7, 0xe1, 0xdd, 0x5e,
	0x2f, 0x0e, 0x32, 0xfb, 0xe7, 0x88, 0xec, 0xeb, 0x46, 0x34, 0x48, 0x99, 0xb6, 0x7e, 0x81, 0x20,
	0x8b, 0x50, 0x97, 0xa5, 0x0b, 0xc5, 0x2a, 0xc3, 0xe7, 0x30, 0xb9, 0x08, 0x20, 0xc7, 0x8a, 0x55,
	0x99, 0xde, 0xc0, 0xe0, 0xf7, 0x47, 0x3b, 0x09, 0x8d, 0xd4, 0x77, 0xe5, 0x03, 0x03, 0x83, 0xb2,
	0x25, 0x84, 0xb2, 0x95, 0x27, 0x72, 0x18, 0x7d, 0xfe, 0x68, 0x85, 0x06, 0x5d, 0xa6, 0x98, 0x95,
	0x3f, 0x4c, 0x14, 0xea, 0xad, 0x40, 0x64, 0x6f, 0x28, 0xbd, 0x73, 0x04, 0xfa, 0x78, 0x93, 0xa6,
	0x62, 0x6d, 0xa5, 0xc5, 0x94, 0x8f, 0x15, 0x84, 0xf8, 0xc7, 0xec, 0x19, 0xe2, 0x0f, 0x14, 0x5e,
	0x41, 0xe4, 0x05, 0x38, 0xb9, 0xb6, 0xb2, 0xb2, 0xfd, 0xde, 0x03, 0xae, 0xd2, 0x41, 0xab, 0x23,
	0x37, 0x82, 0x8d, 0xf4, 0x66, 0x60, 0x3a, 0xb3, 0xf8, 0x43, 0x3a, 0xa4, 0xde, 0xaf, 0x1c, 0x98,
	0xcd, 0x10, 0x59, 0x5c, 0x1c, 0xd7, 0x8a, 0x66, 0xb4, 0x46, 0x31, 0x58, 0x82, 0x4a, 0x27, 0xce,
	0x5a, 0xd0, 0x85, 0x52, 0xea, 0xb5, 0x78, 0xfd, 0x84, 0x5f, 0xe9, 0xc4, 0x58, 0x6a, 0x3e, 0xa2,
	0x43, 0xda, 0xfa, 0x8b, 0xa2, 0x2e, 0x97, 0x8d, 0x8a, 0xad, 0x9f, 0xf0, 0x25, 0xe5, 0xbd, 0x06,
	0x4c, 0x69, 0xbd, 0xbc, 0x3f, 0x39, 0x30, 0xbf, 0x1a, 0x0d, 0x43, 0x1e, 0x47, 0x7d, 0x16, 0x09,
	0xda, 0x33, 0x36, 0xaf, 0xdd, 0xfb, 0x54, 0xcd, 0xd6, 0xe6, 0x36, 0xd4, 0xbb, 0x3a, 0xf2, 0x75,
	0x00, 0xdb, 0x25, 0x6e, 0x64, 0x5b, 0xf8, 0x39, 0x35, 0x72, 0xf6, 0xb4, 0x4e, 0x3a, 0x9e, 0xcf,
	0x97, 0x2a, 0x9c, 0x73, 0x66, 0xd4, 0xb2, 0x99, 0xe4, 0x6c, 0x28, 0x5d, 0x57, 0xf5, 0xe5, 0x58,
	0xd6, 0x79, 0xf6, 0x4c, 0x48, 0xb7, 0x55, 0x7d, 0x39, 0xf6, 0x2e, 0x41, 0x63, 0x75, 0xc8, 0x22,
	0xf1, 0xa4, 0xcb, 0x22, 0x24, 0x40, 0xad, 0xf5, 0x0a, 0xe4, 0xd8, 0xfb, 0xcc, 0x81, 0x99, 0xbc,
	0xa4, 0xbf, 0x2f, 0x8f, 0x5b, 0x37, 0x2c, 0xf7, 0x1c, 0x51, 0xfd, 0x25, 0xa9, 0xe1, 0x24, 0x17,
	0xaa, 0xa9, 0xe0, 0xba, 0x1b, 0xc2, 0x21, 0xb9, 0x0e, 0x93, 0xa9, 0xe0, 0x83, 0xa0, 0x7c, 0xab,
	0xe6, 0x82, 0x52, 0x5f, 0x93, 0x79, 0xbf, 0x70, 0x00, 0x0a, 0x34, 0xb9, 0x9d, 0x75, 0x21, 0xaa,
	0x8c, 0x7a, 0x47, 0xb0, 0xcb, 0xa1, 0x2e, 0x7c, 0x8a, 0x61, 0xf1, 0x3d, 0x25, 0xe7, 0xc8, 0x62,
	0xf4, 0x9a, 0x5d, 0x8c, 0xce, 0x1d, 0xb3, 0x42, 0xb3, 0x0c, 0x3d, 0x84, 0xe9, 0x95, 0xb8, 0xcd,
	0xee, 0xd1, 0x94, 0x6d, 0x44, 0x07, 0x71, 0x69, 0x6b, 0x88, 0x95, 0x20, 0xec, 0x65, 0x5d, 0xa1,
	0x1c, 0xab, 0x1b, 0x83, 0x28, 0xbb, 0x94, 0x92, 0x63, 0xef, 0x03, 0x80, 0xcc, 0x2f, 0xf2, 0x6c,
	0x96, 0x2f, 0xf5, 0x58, 0x4b, 0xe9, 0x96, 0xf6, 0xe2, 0x58, 0x2f, 0xdd, 0x30, 0x3b, 0x65, 0xef,
	0x09, 0x9c, 0x94, 0xc2, 0x7d, 0x16, 0xc4, 0xbc, 0xcd, 0x78, 0x7e, 0x0b, 0xe5, 0x94, 0xdc, 0x42,
	0x59, 0x94, 0xf6, 0x71, 0xc5, 0xe8, 0x6f, 0xe5, 0xd8, 0xfb, 0xa1, 0x03, 0xd3, 0x92, 0x3e, 0xbb,
	0xca, 0xf9, 0x8a, 0x8a, 0xb7, 0x8a, 0xbb, 0x0c, 0x25, 0x36, 0xbf, 0xa9, 0x78, 0x09, 0x26, 0xf0,
	0xfc, 0x92, 0x75, 0xcd, 0x25, 0xe7, 0x1b, 0xf5, 0xdd, 0xfb, 0x2d, 0x9e, 0x4d, 0xc2, 0x7d, 0x4e,
	0x79, 0xc8, 0xd2, 0x4c, 0x8d, 0x87, 0xd0, 0xe8, 0x65, 0x38, 0x1d, 0x2e, 0xaf, 0xd8, 0x1b, 0x69,
	0x84, 0xa3, 0x40, 0xe8, 0xe6, 0x2b, 0x67, 0x5f, 0x7c, 0x02, 0x33, 0xf6, 0xc7, 0x92, 0x00, 0xba,
	0x6e, 0x07, 0xd0, 0xd9, 0x71, 0x83, 0x66, 0x57, 0x31, 0x46, 0xf8, 0xfc, 0xd8, 0xc9, 0xf7, 0x22,
	0x15, 0xe4, 0x2d, 0x68, 0xd2, 0x24, 0xe9, 0x85, 0x81, 0x6c, 0x7b, 0xb4, 0xfd, 0x8e, 0x11, 0x64,
	0x52, 0x93, 0xb7, 0xcc, 0xf5, 0x96, 0x36, 0xc8, 0x23, 0xeb, 0x35, 0x16, 0xe8, 0xfd, 0xd5, 0x81,
	0x53, 0xda, 0xe9, 0x09, 0x67, 0x29, 0x26, 0x3a, 0x29, 0x74, 0x09, 0x6a, 0x9f, 0x74, 0x59, 0xa6,
	0xca, 0x99, 0x71, 0x55, 0x30, 0x87, 0xf8, 0x92, 0x06, 0xfd, 0xfe, 0x09, 0x46, 0x6e, 0x69, 0xc1,
	0x2e, 0x02, 0xdb, 0x57, 0x54, 0xe4, 0x0d, 0xa8, 0x73, 0x1d, 0x61, 0x3a, 0x19, 0x2c, 0x1e, 0x1d,
	0x83, 0x7e, 0x4e, 0xab, 0x54, 0xa2, 0x42, 0x5f, 0x5f, 0x95, 0xaa, 0x44, 0x85, 0x2f, 0x69, 0xbc,
	0x0d, 0x38, 0xb5, 0x2d, 0x6f, 0xe8, 0x56, 0xba, 0x61, 0xaf, 0xbd, 0x1d, 0x87, 0x91, 0x60, 0x3c,
	0x35, 0xae, 0xf1, 0x54, 0xc9, 0xcf, 0xae, 0xf1, 0x16, 0xa1, 0x1e, 0x20, 0x21, 0x67, 0x91, 0xec,
	0xaf, 0x6b, 0x7e, 0x0e, 0x7b, 0x4c, 0xef, 0x9f, 0x47, 0x4c, 0xd0, 0x36, 0x15, 0xd4, 0xb8, 0xca,
	0xab, 0xc9, 0xab, 0xbc, 0x65, 0xa8, 0x26, 0x41, 0x52, 0x7a, 0x8a, 0x2d, 0xd1, 0xc1, 0x47, 0x62,
	0x8c, 0x22, 0x96, 0x26, 0x3a, 0x09, 0xe0, 0xd0, 0xfb, 0x5d, 0x16, 0x10, 0xf7, 0x71, 0x8e, 0x37,
	0x60, 0x82, 0x0d, 0x33, 0x3d, 0x47, 0xa5, 0x96, 0xf8, 0xcb, 0x57, 0xe4, 0x68, 0xdb, 0xbe, 0xd6,
	0xb3, 0xf4, 0xe2, 0xd4, 0x5a, 0x89, 0x9f, 0xd3, 0x92, 0x6f, 0xc3, 0x49, 0xac, 0x1a, 0xb9, 0x02,
	0xda, 0x31, 0x25, 0x46, 0xc6, 0xaf, 0xbe, 0x4d, 0xec, 0xfd, 0xd2, 0x81, 0x49, 0xe5, 0xb0, 0x63,
	0x0f, 0xa9, 0x77, 0x47, 0xaf, 0x95, 0xac, 0x4a, 0x5a, 0x19, 0xad, 0xa4, 0x57, 0x60, 0x5a, 0x27,
	0x84, 0x3d, 0xe3, 0xc4, 0xda, 0xd4, 0xb8, 0xc7, 0x3a, 0xc1, 0x0e, 0x06, 0x61, 0x5b, 0x9f, 0x59,
	0xe5, 0x18, 0xd3, 0x0a, 0x1e, 0x20, 0xc2, 0x40, 0xb5, 0x58, 0x0d, 0x3f, 0x03, 0xbd, 0xcf, 0x2b,
	0x30, 0xb3, 0xcd, 0xe3, 0x3e, 0x13, 0x5d, 0x36, 0x48, 0xb7, 0x12, 0x91, 0x8e, 0x5d, 0xcb, 0x9e,
	0x87, 0x06, 0xce, 0x95, 0x26, 0x45, 0x2e, 0x2d, 0x10, 0xf8, 0x35, 0x1d, 0xec, 0xa7, 0x87, 0xa9,
	0x60, 0x7d, 0xad, 0x4e, 0x81, 0xc8, 0x73, 0x64, 0xcd, 0xae, 0x00, 0x5d, 0xd6, 0x4b, 0xb4, 0x26,
	0x72, 0x4c, 0xb6, 0x60, 0x3a, 0x88, 0xa3, 0x54, 0xec, 0xf5, 0xe8, 0x3e, 0xeb, 0xa5, 0xad, 0xc9,
	0x92, 0x14, 0x65, 0xab, 0x89, 0xe7, 0xbb, 0x54, 0x6c, 0x4a, 0x72, 0x95, 0xa2, 0x9a, 0x41, 0x81,
	0x21, 0x97, 0xa0, 0x29, 0x45, 0x49, 0x33, 0x61, 0x6b, 0x58, 0xc5, 0x12, 0x20, 0x51, 0x68, 0xa5,
	0x74, 0xf1, 0x6d, 0xf9, 0xfa, 0x62, 0x49, 0x28, 0xc9, 0x63, 0xf3, 0x66, 0x1e, 0x6b, 0x98, 0xc9,
	0xea, 0xef, 0x15, 0x58, 0x28, 0x34, 0x5a, 0x0f, 0x53, 0x11, 0x77, 0x38, 0xed, 0x7f, 0x63, 0x16,
	0xfc, 0x5e, 0xa9, 0x05, 0x6f, 0x1e, 0x61, 0x41, 0x4b, 0xdf, 0xe7, 0x98, 0xb2, 0x05, 0x53, 0xfb,
	0x03, 0x79, 0x4e, 0x92, 0x66, 0x74, 0xfc, 0x0c, 0x1c, 0x35, 0x72, 0xfd, 0x6b, 0x37, 0xf2, 0x2e,
	0x2c, 0x16, 0x3a, 0xef, 0x0c, 0xfa, 0x7d, 0xca, 0x0f, 0xb7, 0xf6, 0x3f, 0x62, 0x81, 0x08, 0x87,
	0xe3, 0xef, 0x07, 0x5a, 0x72, 0x45, 0x76, 0xdd, 0xb6, 0xe4, 0xaa, 0xc4, 0xe9, 0xe7, 0xae, 0x2f,
	0xaa, 0x70, 0x7a, 0x5c, 0xec, 0x37, 0xe5, 0xb8, 0xf7, 0x4b, 0x1d, 0x77, 0xe3, 0x08, 0xc7, 0x19,
	0xda, 0x3e, 0xc7, 0x6d, 0x6b, 0x00, 0x71, 0x66, 0x2a, 0xe5, 0xb9, 0xe6, 0xf2, 0x4b, 0xcf, 0x91,
	0x9a, 0xd1, 0xfb, 0x06, 0x2b, 0x59, 0x80, 0xa9, 0x3e, 0x7d, 0xb6, 0x87, 0x3d, 0x49, 0x5d, 0x5d,
	0x9b, 0xf5, 0xe9, 0xb3, 0xbb, 0x1d, 0x86, 0xee, 0xc7, 0x44, 0x94, 0x05, 0x07, 0x9e, 0x9f, 0x4e,
	0xfa, 0x40, 0x3b, 0xec, 0x9e, 0x8e, 0x8f, 0x05, 0x8c, 0x9c, 0x83, 0xbd, 0x80, 0x26, 0x2d, 0x90,
	0x1f, 0x27, 0xf7, 0x07, 0x07, 0x2b, 0x34, 0x19, 0x0d, 0x9c, 0xe6, 0xd7, 0x1e, 0x38, 0x3f, 0xb3,
	0x76, 0x67, 0x76, 0x67, 0xa2, 0xca, 0xf8, 0x2d, 0xa8, 0x07, 0xf1, 0x40, 0x16, 0x1e, 0xdd, 0x0a,
	0x9d, 0x3b, 0x26, 0xcf, 0xf8, 0x39, 0x31, 0xb9, 0x01, 0x93, 0x1d, 0x3a, 0xe8, 0xb0, 0xec, 0xbe,
	0xe9, 0x58, 0x36, 0x4d, 0x4a, 0xee, 0x03, 0x74, 0xb3, 0xcd, 0x96, 0x35, 0x6f, 0x2f, 0x7c, 0x99,
	0x5d, 0xe9, 0x1b, 0x7c, 0xe4, 0x0e, 0x86, 0x1a, 0xfa, 0x08, 0xfb, 0x99, 0x5a, 0x49, 0xbb, 0x5f,
	0x1a, 0x21, 0x7e, 0xc1, 0xe4, 0xfd, 0xb4, 0x02, 0x53, 0xdb, 0xf4, 0xb0, 0x17, 0xd3, 0x36, 0xb9,
	0x00, 0xc0, 0xd9, 0xc7, 0x03, 0x96, 0x8a, 0xbd, 0x3c, 0xdc, 0x1b, 0x1a, 0xb3, 0xd1, 0x26, 0xe7,
	0xe4, 0x53, 0xe3, 0x41, 0xd8, 0x29, 0x6e, 0x4a, 0xeb, 0x0a, 0xb1, 0xd1, 0x96, 0x9a, 0xe4, 0xcf,
	0x47, 0xaa, 0x22, 0x7a, 0xcf, 0x7f, 0x3e, 0x32, 0xde, 0x8b, 0xc8, 0xdb, 0x50, 0xa7, 0x6d, 0xf5,
	0x54, 0xa9, 0xfb, 0x96, 0x2f, 0x23, 0x20, 0xe7, 0xc1, 0x63, 0x53, 0x7f, 0x4f, 0x16, 0xd4, 0xa6,
	0x2c, 0xa8, 0xad, 0x91, 0xcb, 0x10, 0x59, 0x0a, 0x65, 0x45, 0x9d, 0xe8, 0xef, 0xea, 0x46, 0x5d,
	0x56, 0xc4, 0xe9, 0xa2, 0x22, 0x2e, 0x7d, 0x00, 0x73, 0x63, 0x2f, 0xe4, 0xe4, 0x0c, 0x90, 0x31,
	0xe4, 0x9e, 0x7b, 0x82, 0x4c, 0x42, 0x65, 0x73, 0xd7, 0x75, 0xf0, 0x77, 0x6d, 0xd7, 0xad, 0x48,
	0x78, 0xd5, 0xad, 0x4a, 0x78, 0xd5, 0xad, 0xe1, 0xef, 0xea, 0xbb, 0xee, 0x04, 0xfe, 0x3e, 0x5e,
	0x75, 0x27, 0x97, 0xee, 0x98, 0x6f, 0xc6, 0x4a, 0x83, 0x19, 0x0b, 0x81, 0x42, 0x67, 0x00, 0x1e,
	0x0f, 0xfa, 0x5b, 0x07, 0x1b, 0xd1, 0x30, 0x7e, 0xea, 0x3a, 0xa4, 0x09, 0x53, 0x9b, 0x54, 0xb0,
	0x28, 0x38, 0x74, 0x2b, 0x4b, 0x4f, 0x0c, 0xf5, 0xb2, 0xe7, 0x4e, 0x4b, 0xbd, 0x0c, 0x89, 0x92,
	0x4e, 0x1b, 0xc4, 0x7a, 0xf9, 0x7b, 0xae, 0x43, 0x4e, 0xc1, 0xac, 0xfd, 0xa4, 0xbd, 0xe7, 0x56,
	0x96, 0xae, 0x41, 0x23, 0x7f, 0xc7, 0x45, 0x15, 0x72, 0x00, 0x05, 0xd5, 0xa1, 0x76, 0x37, 0x6a,
	0x23, 0xef, 0x14, 0x54, 0xb7, 0x38, 0xd2, 0x07, 0xf6, 0x3b, 0x64, 0xae, 0xcb, 0x59, 0xfb, 0x79,
	0xd1, 0x54, 0xa7, 0x65, 0xb3, 0x18, 0x1a, 0x9d, 0x01, 0x32, 0xf6, 0xa6, 0x8a, 0x93, 0x3c, 0x83,
	0x69, 0xf3, 0x81, 0x8d, 0xcc, 0xc1, 0x49, 0x13, 0xd6, 0xd6, 0x92, 0x4f, 0x67, 0x2b, 0x9c, 0xa6,
	0x5d, 0xd7, 0xc9, 0x61, 0xf9, 0x94, 0xe6, 0x56, 0xc8, 0x49, 0x68, 0x28, 0x98, 0xc7, 0x89, 0x5b,
	0x45, 0x83, 0xdb, 0x0f, 0x64, 0x2e, 0x33, 0x70, 0xfa, 0x9d, 0xcb, 0x3d, 0x58, 0xba, 0x05, 0xf5,
	0xec, 0x11, 0x0a, 0x45, 0x64, 0x63, 0x9c, 0x71, 0x16, 0x9a, 0x77, 0x8b, 0x13, 0x85, 0x76, 0x90,
	0x3c, 0x23, 0xa0, 0x83, 0xde, 0x91, 0xa6, 0xd3, 0x8f, 0x23, 0x48, 0x5b, 0x40, 0xc8, 0x0c, 0x30,
	0xb9, 0x23, 0xda, 0xf1, 0x40, 0xb8, 0x8e, 0x1e, 0x33, 0xce, 0xdd, 0x0a, 0x5a, 0xf8, 0x41, 0xd8,
	0x63, 0x6e, 0x75, 0xe9, 0x5d, 0x80, 0xe2, 0x81, 0x02, 0x05, 0x14, 0x10, 0x0a, 0x68, 0xc2, 0xd4,
	0x8a, 0xca, 0x3b, 0xae, 0x43, 0x1a, 0x30, 0xb1, 0x86, 0xd9, 0x44, 0xad, 0x33, 0xcf, 0x12, 0x6e,
	0x15, 0xc9, 0xf4, 0x7e, 0x77, 0x6b, 0x4b, 0x3f, 0x80, 0xd9, 0x91, 0xc7, 0x02, 0x32, 0x0f, 0xee,
	0x08, 0x4a, 0x07, 0x8c, 0x81, 0xdd, 0x09, 0xa3, 0x4e, 0x8f, 0xb9, 0xce, 0x08, 0xf1, 0x8e, 0xa0,
	0x5c, 0xb8, 0x95, 0x11, 0xec, 0x86, 0x54, 0x49, 0x1a, 0xd8, 0xc0, 0xae, 0x46, 0x6d, 0xb7, 0xb6,
	0x74, 0xaf, 0xb8, 0xd9, 0xca, 0xdc, 0x68, 0xc2, 0x38, 0x73, 0x03, 0x26, 0xb6, 0x44, 0x57, 0x2e,
	0x0a, 0x60, 0x72, 0x2d, 0xee, 0xd1, 0xa8, 0xa3, 0xcc, 0xf2, 0x90, 0x0e, 0xa9, 0x5b, 0x5d, 0xfa,
	0xd0, 0x78, 0xef, 0xcb, 0x6f, 0x50, 0xc8, 0x02, 0x9c, 0x1a, 0xc7, 0xea, 0x95, 0xd8, 0x1f, 0x76,
	0x04, 0x57, 0x81, 0x66, 0xa3, 0x11, 0x72, 0x2b, 0x4b, 0x3f, 0x72, 0x60, 0x6e, 0xec, 0x38, 0x8f,
	0xd4, 0x63, 0x48, 0x14, 0x7e, 0x09, 0xce, 0x59, 0xf8, 0x1d, 0xd5, 0x33, 0xaf, 0xd3, 0xa8, 0xdd,
	0x93, 0x4b, 0x38, 0x0b, 0xa7, 0x2d, 0x82, 0x07, 0x83, 0x48, 0x06, 0xad, 0x5b, 0x21, 0xe7, 0x60,
	0xc1, 0x96, 0xd9, 0x0d, 0x79, 0x7b, 0x9b, 0x72, 0x71, 0xe8, 0x56, 0x97, 0x1e, 0xa2, 0xb7, 0xf3,
	0x34, 0x45, 0x5c, 0x98, 0x36, 0x40, 0x9c, 0xf9, 0x14, 0xcc, 0x66, 0xdb, 0xc6, 0x57, 0x69, 0x59,
	0xb9, 0xa7, 0x40, 0xa6, 0x49, 0x1c, 0xa5, 0xcc, 0xad, 0x2c, 0xdd, 0x01, 0x28, 0xce, 0x10, 0x32,
	0x68, 0x47, 0xf7, 0x8d, 0x42, 0xec, 0xb0, 0xa8, 0xed, 0x3a, 0xe8, 0x13, 0x05, 0xfb, 0x2c, 0x60,
	0xe1, 0x90, 0xb9, 0x95, 0x7b, 0x37, 0xbf, 0x7f, 0xa3, 0x13, 0x8a, 0xee, 0x60, 0xff, 0x5a, 0x10,
	0xf7, 0xaf, 0xdf, 0xed, 0xb1, 0xe0, 0xe9, 0x7d, 0xca, 0x83, 0xc3, 0xeb, 0x9c, 0x61, 0xb5, 0xb8,
	0x1e, 0xc4, 0x9c, 0x5d, 0x37, 0x52, 0xec, 0x75, 0xf9, 0x67, 0xa6, 0xfd, 0x49, 0xf9, 0x73, 0xe3,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xea, 0x5b, 0xdb, 0xe8, 0x24, 0x00, 0x00,
}
