// File generated by hadoop record compiler. Do not edit.
/**
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package org.apache.zookeeper.trace;

import org.apache.jute.*;
import org.apache.jute.Record;
import org.apache.yetus.audience.InterfaceAudience;

@InterfaceAudience.Public
public class TMB_Event implements Record {
  // special events
  public static final int EVENT_NULL    = 0x00000000;
  public static final int EVENT_UNKNOWN = 0x7fffffff;
  // service-level events, captured on service boundaries
  public static final int SERVICE_OFFSET = 0x00000010;
  public static final int SERVICE_SEND   = SERVICE_OFFSET + 0x1;
  public static final int SERVICE_RECV   = SERVICE_OFFSET + 0x2;
  public static final int SERVICE_FRWD   = SERVICE_OFFSET + 0x3; // follower forward
  public static final int SERVICE_PRPS   = SERVICE_OFFSET + 0x4; // leader proposal
  // processor-level events, captured on processor boundaries
  public static final int PROCESSOR_OFFSET = 0x00000100;
  public static final int PROCESSOR_RECV   = PROCESSOR_OFFSET + 0x1; // processor received a message from other processors
  // logical events, captured when logical pre-requisites are satisfied
  public static final int LOGICAL_OFFSET     = 0x00001000;
  public static final int LOGICAL_PRPS_READY = LOGICAL_OFFSET + 0x1; // leader starts to send proposals to followers
  public static final int LOGICAL_CMMT_READY = LOGICAL_OFFSET + 0x2; // leader has received enough ACK's and starts to send commit to the followers

  private int type;
  private long timestamp;
  private String message_name;
  private String uuid;
  private String service;
  private String processor; // Zookeeper specified field
  public TMB_Event() {
  }
  public TMB_Event(
          int type,
          String message_name,
          String uuid,
          TMB_Store.ProcessorMeta procMeta) {
    this.type=type;
    this.timestamp=TMB_Helper.currentTimeNanos();
    this.message_name=message_name;
    this.uuid=uuid;
    this.service=procMeta.getQuorumName();
    this.processor=procMeta.getName();
  }
  public TMB_Event(
        int type,
        String message_name,
        String uuid,
        String service,
        Class processor) {
    this.type=type;
    this.timestamp=TMB_Helper.currentTimeNanos();
    this.message_name=message_name;
    this.uuid=uuid;
    this.service=service;
    this.processor=TMB_Helper.getClassName(processor);

    // TMB_Helper.printf(3, "[%s] a new event: %s", service, this);
  }
  // 3MileBeach starts
  public String getTypeString() {
    return getTypeString(this.type);
  }
  public static String getTypeString(int type) {
    switch (type) {
      case EVENT_NULL:
        return "EVENT_NULL";
      case EVENT_UNKNOWN:
        return "EVENT_UNKNOWN";
      case SERVICE_SEND:
        return "SERVICE_SEND";
      case SERVICE_RECV:
        return "SERVICE_RECV";
      case SERVICE_FRWD:
        return "SERVICE_FRWD";
      case SERVICE_PRPS:
        return "SERVICE_PRPS";
      case PROCESSOR_RECV:
        return "PROCESSOR_RECV";
      case LOGICAL_PRPS_READY:
        return "LOGICAL_PRPS_READY";
      case LOGICAL_CMMT_READY:
        return "LOGICAL_CMMT_READY";
      default:
        return "EVENT_UNDEFINED";
    }
  }
  public String toJSON() {
    StringBuffer buffer = new StringBuffer();
    toJSON(buffer);
    return buffer.toString();
  }
  public void toJSON(StringBuffer buffer) {
    buffer.append(String.format("{\"service\":\"%s\",\"timestamp\":%d,\"type\":\"%s\",\"message_name\":\"%s\",\"uuid\":\"%s\",\"processor\":\"%s\"}",
            this.getService(), this.getTimestamp(), this.getTypeString(), this.getMessage_name(), this.getUuid(), this.getProcessor()));
  }
  // 3MileBeach ends
  public int getType() {
    return type;
  }
  public void setType(int m_) {
    type=m_;
  }
  public long getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(long m_) {
    timestamp=m_;
  }
  public String getMessage_name() {
    return message_name;
  }
  public void setMessage_name(String m_) {
    message_name=m_;
  }
  public String getUuid() {
    return uuid;
  }
  public void setUuid(String m_) {
    uuid=m_;
  }
  public String getService() {
    return service;
  }
  public void setService(String m_) {
    service=m_;
  }
  public String getProcessor() {
    return processor;
  }
  public void setProcessor(String m_) {
    processor=m_;
  }
  public org.apache.zookeeper.trace.TMB_Trace getTrace() {
    return null;
  }
  public void setTrace(org.apache.zookeeper.trace.TMB_Trace m_) {}
  public void serialize(OutputArchive a_, String tag) throws java.io.IOException {
    a_.startRecord(this,tag);
    a_.writeInt(type,"type");
    a_.writeLong(timestamp,"timestamp");
    a_.writeString(message_name,"message_name");
    a_.writeString(uuid,"uuid");
    a_.writeString(service,"service");
    a_.writeString(processor,"processor");
    a_.endRecord(this,tag);
  }
  public void deserialize(InputArchive a_, String tag) throws java.io.IOException {
    a_.startRecord(tag);
    type=a_.readInt("type");
    timestamp=a_.readLong("timestamp");
    message_name=a_.readString("message_name");
    uuid=a_.readString("uuid");
    service=a_.readString("service");
    processor=a_.readString("processor");
    a_.endRecord(tag);
}
  public String toString() {
    try {
      java.io.ByteArrayOutputStream s =
        new java.io.ByteArrayOutputStream();
      ToStringOutputArchive a_ = 
        new ToStringOutputArchive(s);
      a_.startRecord(this,"");
    a_.writeInt(type,"type");
    a_.writeLong(timestamp,"timestamp");
    a_.writeString(message_name,"message_name");
    a_.writeString(uuid,"uuid");
    a_.writeString(service,"service");
    a_.writeString(processor,"processor");
      a_.endRecord(this,"");
      return new String(s.toByteArray(), "UTF-8");
    } catch (Throwable ex) {
      ex.printStackTrace();
    }
    return "ERROR";
  }
  public void write(java.io.DataOutput out) throws java.io.IOException {
    BinaryOutputArchive archive = new BinaryOutputArchive(out);
    serialize(archive, "");
  }
  public void readFields(java.io.DataInput in) throws java.io.IOException {
    BinaryInputArchive archive = new BinaryInputArchive(in);
    deserialize(archive, "");
  }
  public int compareTo (Object peer_) throws ClassCastException {
    if (!(peer_ instanceof TMB_Event)) {
      throw new ClassCastException("Comparing different types of records.");
    }
    TMB_Event peer = (TMB_Event) peer_;
    int ret = 0;
    ret = (type == peer.type)? 0 :((type<peer.type)?-1:1);
    if (ret != 0) return ret;
    ret = (timestamp == peer.timestamp)? 0 :((timestamp<peer.timestamp)?-1:1);
    if (ret != 0) return ret;
    ret = message_name.compareTo(peer.message_name);
    if (ret != 0) return ret;
    ret = uuid.compareTo(peer.uuid);
    if (ret != 0) return ret;
    ret = service.compareTo(peer.service);
    if (ret != 0) return ret;
    ret = processor.compareTo(peer.processor);
    if (ret != 0) return ret;
     return ret;
  }
  public boolean equals(Object peer_) {
    if (!(peer_ instanceof TMB_Event)) {
      return false;
    }
    if (peer_ == this) {
      return true;
    }
    TMB_Event peer = (TMB_Event) peer_;
    boolean ret = false;
    ret = (type==peer.type);
    if (!ret) return ret;
    ret = (timestamp==peer.timestamp);
    if (!ret) return ret;
    ret = message_name.equals(peer.message_name);
    if (!ret) return ret;
    ret = uuid.equals(peer.uuid);
    if (!ret) return ret;
    ret = service.equals(peer.service);
    if (!ret) return ret;
    ret = processor.equals(peer.processor);
    if (!ret) return ret;
     return ret;
  }
  public int hashCode() {
    int result = 17;
    int ret;
    ret = (int)type;
    result = 37*result + ret;
    ret = (int) (timestamp^(timestamp>>>32));
    result = 37*result + ret;
    ret = message_name.hashCode();
    result = 37*result + ret;
    ret = uuid.hashCode();
    result = 37*result + ret;
    ret = service.hashCode();
    result = 37*result + ret;
    ret = processor.hashCode();
    result = 37*result + ret;
    return result;
  }
  public static String signature() {
    return "LTMB_Event(ilssss)";
  }
}
