package public

import "time"

const ENV_PROFILE_INTERVAL = 5 * time.Second
const CPU_PROFILE_DURATION = time.Second
const CPU_PROFILE_DURATION_MAX = 2 * CPU_PROFILE_DURATION

const TIME_FORMAT_DEFAULT = time.RFC3339
const TIME_FORMAT_RFC3339 = time.RFC3339

const PREREQUISITE_ACCOMPLISHED = -1
const CONFIGURE_ID_DEFAULT = -1
